-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_Interpolation_Filter.vhd
-- Created: 2025-10-27 18:12:29
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_Interpolation_Filter
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency 
-- and Coarse Phase Synchronizer/Time and Coarse Frequency Synchronizer/Symbol Synchronizer/Interpolation Filte
-- Hierarchy Level: 7
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_Interpolation_Filter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_8_0                         :   IN    std_logic;
        In_re                             :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
        In_im                             :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
        mu                                :   IN    std_logic_vector(10 DOWNTO 0);  -- sfix11_En10
        interpolant_re                    :   OUT   std_logic_vector(21 DOWNTO 0);  -- sfix22_En13
        interpolant_im                    :   OUT   std_logic_vector(21 DOWNTO 0)  -- sfix22_En13
        );
END dvbs2_ip_src_Interpolation_Filter;


ARCHITECTURE rtl OF dvbs2_ip_src_Interpolation_Filter IS

  -- Signals
  SIGNAL In_re_signed                     : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL In_im_signed                     : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay1_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay1_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay36_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay36_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay33_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay33_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay10_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay10_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay23_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay23_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay28_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay28_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay18_reg_re                   : vector_of_signed18(0 TO 1);  -- sfix18_En13 [2]
  SIGNAL Delay18_reg_im                   : vector_of_signed18(0 TO 1);  -- sfix18_En13 [2]
  SIGNAL Delay18_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay18_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay12_reg_re                   : vector_of_signed18(0 TO 1);  -- sfix18_En13 [2]
  SIGNAL Delay12_reg_im                   : vector_of_signed18(0 TO 1);  -- sfix18_En13 [2]
  SIGNAL Delay12_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay12_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay8_reg_re                    : vector_of_signed18(0 TO 1);  -- sfix18_En13 [2]
  SIGNAL Delay8_reg_im                    : vector_of_signed18(0 TO 1);  -- sfix18_En13 [2]
  SIGNAL Delay8_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay8_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay5_reg_re                    : vector_of_signed18(0 TO 1);  -- sfix18_En13 [2]
  SIGNAL Delay5_reg_im                    : vector_of_signed18(0 TO 1);  -- sfix18_En13 [2]
  SIGNAL Delay5_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay5_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Gain_cast                        : signed(18 DOWNTO 0);  -- sfix19_En14
  SIGNAL Gain_cast_1                      : signed(18 DOWNTO 0);  -- sfix19_En14
  SIGNAL Gain_out1_re                     : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Gain_out1_im                     : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay35_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay35_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Sum9_sub_cast                    : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Sum9_sub_cast_1                  : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Sum9_sub_cast_2                  : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Sum9_sub_cast_3                  : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Sum9_out1_re                     : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Sum9_out1_im                     : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Delay32_out1_re                  : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Delay32_out1_im                  : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Delay2_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay2_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay31_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay31_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Sum10_add_cast                   : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Sum10_add_cast_1                 : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Sum10_add_cast_2                 : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Sum10_add_cast_3                 : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Sum10_out1_re                    : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Sum10_out1_im                    : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Delay22_out1_re                  : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Delay22_out1_im                  : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Delay3_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay3_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay21_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay21_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Sum4_sub_cast                    : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum4_sub_cast_1                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum4_sub_cast_2                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum4_sub_cast_3                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum4_out1_re                     : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum4_out1_im                     : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Delay27_out1_re                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Delay27_out1_im                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Delay17_reg_re                   : vector_of_signed21(0 TO 1);  -- sfix21_En13 [2]
  SIGNAL Delay17_reg_im                   : vector_of_signed21(0 TO 1);  -- sfix21_En13 [2]
  SIGNAL Delay17_out1_re                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Delay17_out1_im                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Delay4_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay4_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay26_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay26_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay16_reg_re                   : vector_of_signed18(0 TO 1);  -- sfix18_En13 [2]
  SIGNAL Delay16_reg_im                   : vector_of_signed18(0 TO 1);  -- sfix18_En13 [2]
  SIGNAL Delay16_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay16_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Sum7_sub_cast                    : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum7_sub_cast_1                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum7_out1_re                     : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum7_out1_im                     : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Delay11_reg_re                   : vector_of_signed21(0 TO 1);  -- sfix21_En13 [2]
  SIGNAL Delay11_reg_im                   : vector_of_signed21(0 TO 1);  -- sfix21_En13 [2]
  SIGNAL Delay11_out1_re                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Delay11_out1_im                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Delay30_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay30_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Sum1_sub_cast                    : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Sum1_sub_cast_1                  : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Sum1_sub_cast_2                  : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Sum1_sub_cast_3                  : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Sum1_out1_re                     : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Sum1_out1_im                     : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Delay20_out1_re                  : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Delay20_out1_im                  : signed(18 DOWNTO 0);  -- sfix19_En13
  SIGNAL Sum5_sub_cast                    : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Sum5_sub_cast_1                  : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Sum5_sub_cast_2                  : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Sum5_sub_cast_3                  : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Sum5_out1_re                     : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Sum5_out1_im                     : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Delay25_out1_re                  : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Delay25_out1_im                  : signed(19 DOWNTO 0);  -- sfix20_En13
  SIGNAL Sum6_add_cast                    : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum6_add_cast_1                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum6_add_temp                    : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum6_add_cast_2                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum6_add_cast_3                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum6_add_temp_1                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum6_out1_re                     : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Sum6_out1_im                     : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay15_reg_re                   : vector_of_signed18(0 TO 1) := (OTHERS => to_signed(16#00000#, 18));  -- sfix18_En13 [2]
  SIGNAL Delay15_reg_im                   : vector_of_signed18(0 TO 1) := (OTHERS => to_signed(16#00000#, 18));  -- sfix18_En13 [2]
  SIGNAL Delay15_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay15_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL mu_signed                        : signed(10 DOWNTO 0);  -- sfix11_En10
  SIGNAL Delay34_out1                     : signed(10 DOWNTO 0);  -- sfix11_En10
  SIGNAL Delay29_out1                     : signed(10 DOWNTO 0);  -- sfix11_En10
  SIGNAL Delay19_out1                     : signed(10 DOWNTO 0);  -- sfix11_En10
  SIGNAL Delay24_out1                     : signed(10 DOWNTO 0);  -- sfix11_En10
  SIGNAL Delay14_reg                      : vector_of_signed11(0 TO 1) := (OTHERS => to_signed(16#000#, 11));  -- sfix11 [2]
  SIGNAL Delay14_out1                     : signed(10 DOWNTO 0);  -- sfix11_En10
  SIGNAL Product1_mul_temp                : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Product1_mul_temp_1              : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Product1_out1_re                 : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Product1_out1_im                 : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay9_reg_re                    : vector_of_signed18(0 TO 1) := (OTHERS => to_signed(16#00000#, 18));  -- sfix18_En13 [2]
  SIGNAL Delay9_reg_im                    : vector_of_signed18(0 TO 1) := (OTHERS => to_signed(16#00000#, 18));  -- sfix18_En13 [2]
  SIGNAL Delay9_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay9_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Sum3_add_cast                    : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum3_add_cast_1                  : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum3_out1_re                     : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum3_out1_im                     : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Delay6_reg_re                    : vector_of_signed21(0 TO 1) := (OTHERS => to_signed(16#000000#, 21));  -- sfix21_En13 [2]
  SIGNAL Delay6_reg_im                    : vector_of_signed21(0 TO 1) := (OTHERS => to_signed(16#000000#, 21));  -- sfix21_En13 [2]
  SIGNAL Delay6_out1_re                   : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Delay6_out1_im                   : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Delay13_reg                      : vector_of_signed11(0 TO 1);  -- sfix11 [2]
  SIGNAL Delay13_out1                     : signed(10 DOWNTO 0);  -- sfix11_En10
  SIGNAL Delay7_reg                       : vector_of_signed11(0 TO 1) := (OTHERS => to_signed(16#000#, 11));  -- sfix11 [2]
  SIGNAL Delay7_out1                      : signed(10 DOWNTO 0);  -- sfix11_En10
  SIGNAL Product2_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En23
  SIGNAL Product2_mul_temp_1              : signed(31 DOWNTO 0);  -- sfix32_En23
  SIGNAL Product2_out1_re                 : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Product2_out1_im                 : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Delay_reg_re                     : vector_of_signed21(0 TO 1) := (OTHERS => to_signed(16#000000#, 21));  -- sfix21_En13 [2]
  SIGNAL Delay_reg_im                     : vector_of_signed21(0 TO 1) := (OTHERS => to_signed(16#000000#, 21));  -- sfix21_En13 [2]
  SIGNAL Delay_out1_re                    : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Delay_out1_im                    : signed(20 DOWNTO 0);  -- sfix21_En13
  SIGNAL Sum2_add_cast                    : signed(21 DOWNTO 0);  -- sfix22_En13
  SIGNAL Sum2_add_cast_1                  : signed(21 DOWNTO 0);  -- sfix22_En13
  SIGNAL Sum2_add_cast_2                  : signed(21 DOWNTO 0);  -- sfix22_En13
  SIGNAL Sum2_add_cast_3                  : signed(21 DOWNTO 0);  -- sfix22_En13
  SIGNAL Sum2_out1_re                     : signed(21 DOWNTO 0);  -- sfix22_En13
  SIGNAL Sum2_out1_im                     : signed(21 DOWNTO 0);  -- sfix22_En13

BEGIN
  In_re_signed <= signed(In_re);

  In_im_signed <= signed(In_im);

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out1_re <= to_signed(16#00000#, 18);
        Delay1_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay1_out1_re <= In_re_signed;
        Delay1_out1_im <= In_im_signed;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  Delay36_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay36_out1_re <= to_signed(16#00000#, 18);
        Delay36_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay36_out1_re <= Delay1_out1_re;
        Delay36_out1_im <= Delay1_out1_im;
      END IF;
    END IF;
  END PROCESS Delay36_process;


  Delay33_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay33_out1_re <= to_signed(16#00000#, 18);
        Delay33_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay33_out1_re <= Delay36_out1_re;
        Delay33_out1_im <= Delay36_out1_im;
      END IF;
    END IF;
  END PROCESS Delay33_process;


  Delay10_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay10_out1_re <= to_signed(16#00000#, 18);
        Delay10_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay10_out1_re <= Delay33_out1_re;
        Delay10_out1_im <= Delay33_out1_im;
      END IF;
    END IF;
  END PROCESS Delay10_process;


  Delay23_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay23_out1_re <= to_signed(16#00000#, 18);
        Delay23_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay23_out1_re <= Delay10_out1_re;
        Delay23_out1_im <= Delay10_out1_im;
      END IF;
    END IF;
  END PROCESS Delay23_process;


  Delay28_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay28_out1_re <= to_signed(16#00000#, 18);
        Delay28_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay28_out1_re <= Delay23_out1_re;
        Delay28_out1_im <= Delay23_out1_im;
      END IF;
    END IF;
  END PROCESS Delay28_process;


  Delay18_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay18_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay18_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_8_0 = '1' THEN
        Delay18_reg_im(0) <= Delay28_out1_im;
        Delay18_reg_im(1) <= Delay18_reg_im(0);
        Delay18_reg_re(0) <= Delay28_out1_re;
        Delay18_reg_re(1) <= Delay18_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay18_process;

  Delay18_out1_re <= Delay18_reg_re(1);
  Delay18_out1_im <= Delay18_reg_im(1);

  Delay12_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay12_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay12_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_8_0 = '1' THEN
        Delay12_reg_im(0) <= Delay18_out1_im;
        Delay12_reg_im(1) <= Delay12_reg_im(0);
        Delay12_reg_re(0) <= Delay18_out1_re;
        Delay12_reg_re(1) <= Delay12_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay12_process;

  Delay12_out1_re <= Delay12_reg_re(1);
  Delay12_out1_im <= Delay12_reg_im(1);

  Delay8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay8_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay8_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_8_0 = '1' THEN
        Delay8_reg_im(0) <= Delay12_out1_im;
        Delay8_reg_im(1) <= Delay8_reg_im(0);
        Delay8_reg_re(0) <= Delay12_out1_re;
        Delay8_reg_re(1) <= Delay8_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay8_process;

  Delay8_out1_re <= Delay8_reg_re(1);
  Delay8_out1_im <= Delay8_reg_im(1);

  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay5_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_8_0 = '1' THEN
        Delay5_reg_im(0) <= Delay8_out1_im;
        Delay5_reg_im(1) <= Delay5_reg_im(0);
        Delay5_reg_re(0) <= Delay8_out1_re;
        Delay5_reg_re(1) <= Delay5_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay5_process;

  Delay5_out1_re <= Delay5_reg_re(1);
  Delay5_out1_im <= Delay5_reg_im(1);

  Gain_cast <= resize(In_re_signed, 19);
  Gain_out1_re <= Gain_cast(18 DOWNTO 1);
  Gain_cast_1 <= resize(In_im_signed, 19);
  Gain_out1_im <= Gain_cast_1(18 DOWNTO 1);

  Delay35_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay35_out1_re <= to_signed(16#00000#, 18);
        Delay35_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay35_out1_re <= Gain_out1_re;
        Delay35_out1_im <= Gain_out1_im;
      END IF;
    END IF;
  END PROCESS Delay35_process;


  Sum9_sub_cast <= resize(Delay36_out1_re, 19);
  Sum9_sub_cast_1 <= resize(Delay35_out1_re, 19);
  Sum9_out1_re <= Sum9_sub_cast - Sum9_sub_cast_1;
  Sum9_sub_cast_2 <= resize(Delay36_out1_im, 19);
  Sum9_sub_cast_3 <= resize(Delay35_out1_im, 19);
  Sum9_out1_im <= Sum9_sub_cast_2 - Sum9_sub_cast_3;

  Delay32_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay32_out1_re <= to_signed(16#00000#, 19);
        Delay32_out1_im <= to_signed(16#00000#, 19);
      ELSIF enb_1_8_0 = '1' THEN
        Delay32_out1_re <= Sum9_out1_re;
        Delay32_out1_im <= Sum9_out1_im;
      END IF;
    END IF;
  END PROCESS Delay32_process;


  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_out1_re <= to_signed(16#00000#, 18);
        Delay2_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay2_out1_re <= Delay35_out1_re;
        Delay2_out1_im <= Delay35_out1_im;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Delay31_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay31_out1_re <= to_signed(16#00000#, 18);
        Delay31_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay31_out1_re <= Delay2_out1_re;
        Delay31_out1_im <= Delay2_out1_im;
      END IF;
    END IF;
  END PROCESS Delay31_process;


  Sum10_add_cast <= resize(Delay32_out1_re, 20);
  Sum10_add_cast_1 <= resize(Delay31_out1_re, 20);
  Sum10_out1_re <= Sum10_add_cast + Sum10_add_cast_1;
  Sum10_add_cast_2 <= resize(Delay32_out1_im, 20);
  Sum10_add_cast_3 <= resize(Delay31_out1_im, 20);
  Sum10_out1_im <= Sum10_add_cast_2 + Sum10_add_cast_3;

  Delay22_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay22_out1_re <= to_signed(16#00000#, 20);
        Delay22_out1_im <= to_signed(16#00000#, 20);
      ELSIF enb_1_8_0 = '1' THEN
        Delay22_out1_re <= Sum10_out1_re;
        Delay22_out1_im <= Sum10_out1_im;
      END IF;
    END IF;
  END PROCESS Delay22_process;


  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_out1_re <= to_signed(16#00000#, 18);
        Delay3_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay3_out1_re <= Delay31_out1_re;
        Delay3_out1_im <= Delay31_out1_im;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  Delay21_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay21_out1_re <= to_signed(16#00000#, 18);
        Delay21_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay21_out1_re <= Delay3_out1_re;
        Delay21_out1_im <= Delay3_out1_im;
      END IF;
    END IF;
  END PROCESS Delay21_process;


  Sum4_sub_cast <= resize(Delay22_out1_re, 21);
  Sum4_sub_cast_1 <= resize(Delay21_out1_re, 21);
  Sum4_out1_re <= Sum4_sub_cast - Sum4_sub_cast_1;
  Sum4_sub_cast_2 <= resize(Delay22_out1_im, 21);
  Sum4_sub_cast_3 <= resize(Delay21_out1_im, 21);
  Sum4_out1_im <= Sum4_sub_cast_2 - Sum4_sub_cast_3;

  Delay27_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay27_out1_re <= to_signed(16#000000#, 21);
        Delay27_out1_im <= to_signed(16#000000#, 21);
      ELSIF enb_1_8_0 = '1' THEN
        Delay27_out1_re <= Sum4_out1_re;
        Delay27_out1_im <= Sum4_out1_im;
      END IF;
    END IF;
  END PROCESS Delay27_process;


  Delay17_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay17_reg_re <= (OTHERS => to_signed(16#000000#, 21));
        Delay17_reg_im <= (OTHERS => to_signed(16#000000#, 21));
      ELSIF enb_1_8_0 = '1' THEN
        Delay17_reg_im(0) <= Delay27_out1_im;
        Delay17_reg_im(1) <= Delay17_reg_im(0);
        Delay17_reg_re(0) <= Delay27_out1_re;
        Delay17_reg_re(1) <= Delay17_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay17_process;

  Delay17_out1_re <= Delay17_reg_re(1);
  Delay17_out1_im <= Delay17_reg_im(1);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_out1_re <= to_signed(16#00000#, 18);
        Delay4_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay4_out1_re <= Delay21_out1_re;
        Delay4_out1_im <= Delay21_out1_im;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  Delay26_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay26_out1_re <= to_signed(16#00000#, 18);
        Delay26_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay26_out1_re <= Delay4_out1_re;
        Delay26_out1_im <= Delay4_out1_im;
      END IF;
    END IF;
  END PROCESS Delay26_process;


  Delay16_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay16_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay16_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_8_0 = '1' THEN
        Delay16_reg_im(0) <= Delay26_out1_im;
        Delay16_reg_im(1) <= Delay16_reg_im(0);
        Delay16_reg_re(0) <= Delay26_out1_re;
        Delay16_reg_re(1) <= Delay16_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay16_process;

  Delay16_out1_re <= Delay16_reg_re(1);
  Delay16_out1_im <= Delay16_reg_im(1);

  Sum7_sub_cast <= resize(Delay16_out1_re, 21);
  Sum7_out1_re <= Delay17_out1_re - Sum7_sub_cast;
  Sum7_sub_cast_1 <= resize(Delay16_out1_im, 21);
  Sum7_out1_im <= Delay17_out1_im - Sum7_sub_cast_1;

  Delay11_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay11_reg_re <= (OTHERS => to_signed(16#000000#, 21));
        Delay11_reg_im <= (OTHERS => to_signed(16#000000#, 21));
      ELSIF enb_1_8_0 = '1' THEN
        Delay11_reg_im(0) <= Sum7_out1_im;
        Delay11_reg_im(1) <= Delay11_reg_im(0);
        Delay11_reg_re(0) <= Sum7_out1_re;
        Delay11_reg_re(1) <= Delay11_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay11_process;

  Delay11_out1_re <= Delay11_reg_re(1);
  Delay11_out1_im <= Delay11_reg_im(1);

  Delay30_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay30_out1_re <= to_signed(16#00000#, 18);
        Delay30_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay30_out1_re <= Delay35_out1_re;
        Delay30_out1_im <= Delay35_out1_im;
      END IF;
    END IF;
  END PROCESS Delay30_process;


  Sum1_sub_cast <= resize(Delay30_out1_re, 19);
  Sum1_sub_cast_1 <= resize(Delay31_out1_re, 19);
  Sum1_out1_re <= Sum1_sub_cast - Sum1_sub_cast_1;
  Sum1_sub_cast_2 <= resize(Delay30_out1_im, 19);
  Sum1_sub_cast_3 <= resize(Delay31_out1_im, 19);
  Sum1_out1_im <= Sum1_sub_cast_2 - Sum1_sub_cast_3;

  Delay20_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay20_out1_re <= to_signed(16#00000#, 19);
        Delay20_out1_im <= to_signed(16#00000#, 19);
      ELSIF enb_1_8_0 = '1' THEN
        Delay20_out1_re <= Sum1_out1_re;
        Delay20_out1_im <= Sum1_out1_im;
      END IF;
    END IF;
  END PROCESS Delay20_process;


  Sum5_sub_cast <= resize(Delay20_out1_re, 20);
  Sum5_sub_cast_1 <= resize(Delay21_out1_re, 20);
  Sum5_out1_re <= Sum5_sub_cast - Sum5_sub_cast_1;
  Sum5_sub_cast_2 <= resize(Delay20_out1_im, 20);
  Sum5_sub_cast_3 <= resize(Delay21_out1_im, 20);
  Sum5_out1_im <= Sum5_sub_cast_2 - Sum5_sub_cast_3;

  Delay25_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay25_out1_re <= to_signed(16#00000#, 20);
        Delay25_out1_im <= to_signed(16#00000#, 20);
      ELSIF enb_1_8_0 = '1' THEN
        Delay25_out1_re <= Sum5_out1_re;
        Delay25_out1_im <= Sum5_out1_im;
      END IF;
    END IF;
  END PROCESS Delay25_process;


  Sum6_add_cast <= resize(Delay26_out1_re, 21);
  Sum6_add_cast_1 <= resize(Delay25_out1_re, 21);
  Sum6_add_temp <= Sum6_add_cast + Sum6_add_cast_1;
  
  Sum6_out1_re <= "011111111111111111" WHEN (Sum6_add_temp(20) = '0') AND (Sum6_add_temp(19 DOWNTO 17) /= "000") ELSE
      "100000000000000000" WHEN (Sum6_add_temp(20) = '1') AND (Sum6_add_temp(19 DOWNTO 17) /= "111") ELSE
      Sum6_add_temp(17 DOWNTO 0);
  Sum6_add_cast_2 <= resize(Delay26_out1_im, 21);
  Sum6_add_cast_3 <= resize(Delay25_out1_im, 21);
  Sum6_add_temp_1 <= Sum6_add_cast_2 + Sum6_add_cast_3;
  
  Sum6_out1_im <= "011111111111111111" WHEN (Sum6_add_temp_1(20) = '0') AND (Sum6_add_temp_1(19 DOWNTO 17) /= "000") ELSE
      "100000000000000000" WHEN (Sum6_add_temp_1(20) = '1') AND (Sum6_add_temp_1(19 DOWNTO 17) /= "111") ELSE
      Sum6_add_temp_1(17 DOWNTO 0);

  Delay15_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb_1_8_0 = '1' THEN
        Delay15_reg_im(0) <= Sum6_out1_im;
        Delay15_reg_im(1) <= Delay15_reg_im(0);
        Delay15_reg_re(0) <= Sum6_out1_re;
        Delay15_reg_re(1) <= Delay15_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay15_process;

  Delay15_out1_re <= Delay15_reg_re(1);
  Delay15_out1_im <= Delay15_reg_im(1);

  mu_signed <= signed(mu);

  Delay34_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay34_out1 <= to_signed(16#000#, 11);
      ELSIF enb_1_8_0 = '1' THEN
        Delay34_out1 <= mu_signed;
      END IF;
    END IF;
  END PROCESS Delay34_process;


  Delay29_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay29_out1 <= to_signed(16#000#, 11);
      ELSIF enb_1_8_0 = '1' THEN
        Delay29_out1 <= Delay34_out1;
      END IF;
    END IF;
  END PROCESS Delay29_process;


  Delay19_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay19_out1 <= to_signed(16#000#, 11);
      ELSIF enb_1_8_0 = '1' THEN
        Delay19_out1 <= Delay29_out1;
      END IF;
    END IF;
  END PROCESS Delay19_process;


  Delay24_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay24_out1 <= to_signed(16#000#, 11);
      ELSIF enb_1_8_0 = '1' THEN
        Delay24_out1 <= Delay19_out1;
      END IF;
    END IF;
  END PROCESS Delay24_process;


  Delay14_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb_1_8_0 = '1' THEN
        Delay14_reg(0) <= Delay24_out1;
        Delay14_reg(1) <= Delay14_reg(0);
      END IF;
    END IF;
  END PROCESS Delay14_process;

  Delay14_out1 <= Delay14_reg(1);

  Product1_mul_temp <= Delay15_out1_re * Delay14_out1;
  Product1_out1_re <= Product1_mul_temp(27 DOWNTO 10) + ('0' & (Product1_mul_temp(28) AND (Product1_mul_temp(9) OR Product1_mul_temp(8) OR Product1_mul_temp(7) OR Product1_mul_temp(6) OR Product1_mul_temp(5) OR Product1_mul_temp(4) OR Product1_mul_temp(3) OR Product1_mul_temp(2) OR Product1_mul_temp(1) OR Product1_mul_temp(0))));
  Product1_mul_temp_1 <= Delay15_out1_im * Delay14_out1;
  Product1_out1_im <= Product1_mul_temp_1(27 DOWNTO 10) + ('0' & (Product1_mul_temp_1(28) AND (Product1_mul_temp_1(9) OR Product1_mul_temp_1(8) OR Product1_mul_temp_1(7) OR Product1_mul_temp_1(6) OR Product1_mul_temp_1(5) OR Product1_mul_temp_1(4) OR Product1_mul_temp_1(3) OR Product1_mul_temp_1(2) OR Product1_mul_temp_1(1) OR Product1_mul_temp_1(0))));

  Delay9_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb_1_8_0 = '1' THEN
        Delay9_reg_im(0) <= Product1_out1_im;
        Delay9_reg_im(1) <= Delay9_reg_im(0);
        Delay9_reg_re(0) <= Product1_out1_re;
        Delay9_reg_re(1) <= Delay9_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay9_process;

  Delay9_out1_re <= Delay9_reg_re(1);
  Delay9_out1_im <= Delay9_reg_im(1);

  Sum3_add_cast <= resize(Delay9_out1_re, 21);
  Sum3_out1_re <= Delay11_out1_re + Sum3_add_cast;
  Sum3_add_cast_1 <= resize(Delay9_out1_im, 21);
  Sum3_out1_im <= Delay11_out1_im + Sum3_add_cast_1;

  Delay6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb_1_8_0 = '1' THEN
        Delay6_reg_im(0) <= Sum3_out1_im;
        Delay6_reg_im(1) <= Delay6_reg_im(0);
        Delay6_reg_re(0) <= Sum3_out1_re;
        Delay6_reg_re(1) <= Delay6_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay6_process;

  Delay6_out1_re <= Delay6_reg_re(1);
  Delay6_out1_im <= Delay6_reg_im(1);

  Delay13_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay13_reg <= (OTHERS => to_signed(16#000#, 11));
      ELSIF enb_1_8_0 = '1' THEN
        Delay13_reg(0) <= Delay14_out1;
        Delay13_reg(1) <= Delay13_reg(0);
      END IF;
    END IF;
  END PROCESS Delay13_process;

  Delay13_out1 <= Delay13_reg(1);

  Delay7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb_1_8_0 = '1' THEN
        Delay7_reg(0) <= Delay13_out1;
        Delay7_reg(1) <= Delay7_reg(0);
      END IF;
    END IF;
  END PROCESS Delay7_process;

  Delay7_out1 <= Delay7_reg(1);

  Product2_mul_temp <= Delay6_out1_re * Delay7_out1;
  Product2_out1_re <= Product2_mul_temp(30 DOWNTO 10) + ('0' & (Product2_mul_temp(31) AND (Product2_mul_temp(9) OR Product2_mul_temp(8) OR Product2_mul_temp(7) OR Product2_mul_temp(6) OR Product2_mul_temp(5) OR Product2_mul_temp(4) OR Product2_mul_temp(3) OR Product2_mul_temp(2) OR Product2_mul_temp(1) OR Product2_mul_temp(0))));
  Product2_mul_temp_1 <= Delay6_out1_im * Delay7_out1;
  Product2_out1_im <= Product2_mul_temp_1(30 DOWNTO 10) + ('0' & (Product2_mul_temp_1(31) AND (Product2_mul_temp_1(9) OR Product2_mul_temp_1(8) OR Product2_mul_temp_1(7) OR Product2_mul_temp_1(6) OR Product2_mul_temp_1(5) OR Product2_mul_temp_1(4) OR Product2_mul_temp_1(3) OR Product2_mul_temp_1(2) OR Product2_mul_temp_1(1) OR Product2_mul_temp_1(0))));

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb_1_8_0 = '1' THEN
        Delay_reg_im(0) <= Product2_out1_im;
        Delay_reg_im(1) <= Delay_reg_im(0);
        Delay_reg_re(0) <= Product2_out1_re;
        Delay_reg_re(1) <= Delay_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay_process;

  Delay_out1_re <= Delay_reg_re(1);
  Delay_out1_im <= Delay_reg_im(1);

  Sum2_add_cast <= resize(Delay5_out1_re, 22);
  Sum2_add_cast_1 <= resize(Delay_out1_re, 22);
  Sum2_out1_re <= Sum2_add_cast + Sum2_add_cast_1;
  Sum2_add_cast_2 <= resize(Delay5_out1_im, 22);
  Sum2_add_cast_3 <= resize(Delay_out1_im, 22);
  Sum2_out1_im <= Sum2_add_cast_2 + Sum2_add_cast_3;

  interpolant_re <= std_logic_vector(Sum2_out1_re);

  interpolant_im <= std_logic_vector(Sum2_out1_im);

END rtl;

