-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_dut.vhd
-- Created: 2025-10-27 18:14:42
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_dut
-- Source Path: dvbs2_ip/dvbs2_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dvbs2_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        rxdataInI_0                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
        rxdataInI_1                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
        rxdataInI_2                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
        rxdataInI_3                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
        rxdataInQ_0                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
        rxdataInQ_1                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
        rxdataInQ_2                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
        rxdataInQ_3                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
        rxvalidIn                         :   IN    std_logic;  -- ufix1
        adc_dac_loopback                  :   IN    std_logic;  -- ufix1
        enbNoise                          :   IN    std_logic;  -- ufix1
        snrdB                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En9
        CFO                               :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En21
        CPO                               :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En21
        modcodidx                         :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
        resetFCPO                         :   IN    std_logic;  -- ufix1
        resetDisplay                      :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        txdataIOut_0                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
        txdataIOut_1                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
        txdataIOut_2                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
        txdataIOut_3                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
        txdataQOut_0                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
        txdataQOut_1                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
        txdataQOut_2                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
        txdataQOut_3                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
        txvalidOut                        :   OUT   std_logic;  -- ufix1
        RxDataI_Out                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        RxValid_Out                       :   OUT   std_logic;  -- ufix1
        nframesSync                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        modcod                            :   OUT   std_logic_vector(4 DOWNTO 0);  -- ufix5
        fecframe                          :   OUT   std_logic;  -- ufix1
        FreqEst                           :   OUT   std_logic_vector(20 DOWNTO 0);  -- sfix21_En21
        TSorGS                            :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        UPL                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        DFL                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        SYNC                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        bitsReceived                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        bitsErrored                       :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
        );
END dvbs2_ip_dut;


ARCHITECTURE rtl OF dvbs2_ip_dut IS

  -- Component Declarations
  COMPONENT dvbs2_ip_src_DVBS2
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          rxdataInI_0                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          rxdataInI_1                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          rxdataInI_2                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          rxdataInI_3                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          rxdataInQ_0                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          rxdataInQ_1                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          rxdataInQ_2                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          rxdataInQ_3                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          rxvalidIn                       :   IN    std_logic;  -- ufix1
          adc_dac_loopback                :   IN    std_logic;  -- ufix1
          enbNoise                        :   IN    std_logic;  -- ufix1
          snrdB                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En9
          CFO                             :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En21
          CPO                             :   IN    std_logic_vector(20 DOWNTO 0);  -- sfix21_En21
          modcodidx                       :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
          resetFCPO                       :   IN    std_logic;  -- ufix1
          resetDisplay                    :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          txdataIOut_0                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          txdataIOut_1                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          txdataIOut_2                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          txdataIOut_3                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          txdataQOut_0                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          txdataQOut_1                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          txdataQOut_2                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          txdataQOut_3                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          txvalidOut                      :   OUT   std_logic;  -- ufix1
          RxDataI_Out                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          RxValid_Out                     :   OUT   std_logic;  -- ufix1
          nframesSync                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          modcod                          :   OUT   std_logic_vector(4 DOWNTO 0);  -- ufix5
          fecframe                        :   OUT   std_logic;  -- ufix1
          FreqEst                         :   OUT   std_logic_vector(20 DOWNTO 0);  -- sfix21_En21
          TSorGS                          :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          UPL                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          DFL                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          SYNC                            :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
          bitsReceived                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          bitsErrored                     :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dvbs2_ip_src_DVBS2
    USE ENTITY work.dvbs2_ip_src_DVBS2(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL rxvalidIn_sig                    : std_logic;  -- ufix1
  SIGNAL adc_dac_loopback_sig             : std_logic;  -- ufix1
  SIGNAL enbNoise_sig                     : std_logic;  -- ufix1
  SIGNAL resetFCPO_sig                    : std_logic;  -- ufix1
  SIGNAL resetDisplay_sig                 : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL txdataIOut_0_sig                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL txdataIOut_1_sig                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL txdataIOut_2_sig                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL txdataIOut_3_sig                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL txdataQOut_0_sig                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL txdataQOut_1_sig                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL txdataQOut_2_sig                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL txdataQOut_3_sig                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL txvalidOut_sig                   : std_logic;  -- ufix1
  SIGNAL RxDataI_Out_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL RxValid_Out_sig                  : std_logic;  -- ufix1
  SIGNAL nframesSync_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL modcod_sig                       : std_logic_vector(4 DOWNTO 0);  -- ufix5
  SIGNAL fecframe_sig                     : std_logic;  -- ufix1
  SIGNAL FreqEst_sig                      : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL TSorGS_sig                       : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL UPL_sig                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL DFL_sig                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SYNC_sig                         : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL bitsReceived_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL bitsErrored_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_dvbs2_ip_src_DVBS2 : dvbs2_ip_src_DVBS2
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              rxdataInI_0 => rxdataInI_0,  -- sfix16
              rxdataInI_1 => rxdataInI_1,  -- sfix16
              rxdataInI_2 => rxdataInI_2,  -- sfix16
              rxdataInI_3 => rxdataInI_3,  -- sfix16
              rxdataInQ_0 => rxdataInQ_0,  -- sfix16
              rxdataInQ_1 => rxdataInQ_1,  -- sfix16
              rxdataInQ_2 => rxdataInQ_2,  -- sfix16
              rxdataInQ_3 => rxdataInQ_3,  -- sfix16
              rxvalidIn => rxvalidIn_sig,  -- ufix1
              adc_dac_loopback => adc_dac_loopback_sig,  -- ufix1
              enbNoise => enbNoise_sig,  -- ufix1
              snrdB => snrdB,  -- sfix16_En9
              CFO => CFO,  -- sfix21_En21
              CPO => CPO,  -- sfix21_En21
              modcodidx => modcodidx,  -- ufix5
              resetFCPO => resetFCPO_sig,  -- ufix1
              resetDisplay => resetDisplay_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              txdataIOut_0 => txdataIOut_0_sig,  -- sfix16
              txdataIOut_1 => txdataIOut_1_sig,  -- sfix16
              txdataIOut_2 => txdataIOut_2_sig,  -- sfix16
              txdataIOut_3 => txdataIOut_3_sig,  -- sfix16
              txdataQOut_0 => txdataQOut_0_sig,  -- sfix16
              txdataQOut_1 => txdataQOut_1_sig,  -- sfix16
              txdataQOut_2 => txdataQOut_2_sig,  -- sfix16
              txdataQOut_3 => txdataQOut_3_sig,  -- sfix16
              txvalidOut => txvalidOut_sig,  -- ufix1
              RxDataI_Out => RxDataI_Out_sig,  -- ufix32
              RxValid_Out => RxValid_Out_sig,  -- ufix1
              nframesSync => nframesSync_sig,  -- ufix32
              modcod => modcod_sig,  -- ufix5
              fecframe => fecframe_sig,  -- ufix1
              FreqEst => FreqEst_sig,  -- sfix21_En21
              TSorGS => TSorGS_sig,  -- ufix2
              UPL => UPL_sig,  -- ufix16
              DFL => DFL_sig,  -- ufix16
              SYNC => SYNC_sig,  -- ufix8
              bitsReceived => bitsReceived_sig,  -- ufix32
              bitsErrored => bitsErrored_sig  -- ufix32
              );

  rxvalidIn_sig <= rxvalidIn;

  adc_dac_loopback_sig <= adc_dac_loopback;

  enbNoise_sig <= enbNoise;

  resetFCPO_sig <= resetFCPO;

  resetDisplay_sig <= resetDisplay;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  txdataIOut_0 <= txdataIOut_0_sig;

  txdataIOut_1 <= txdataIOut_1_sig;

  txdataIOut_2 <= txdataIOut_2_sig;

  txdataIOut_3 <= txdataIOut_3_sig;

  txdataQOut_0 <= txdataQOut_0_sig;

  txdataQOut_1 <= txdataQOut_1_sig;

  txdataQOut_2 <= txdataQOut_2_sig;

  txdataQOut_3 <= txdataQOut_3_sig;

  txvalidOut <= txvalidOut_sig;

  RxDataI_Out <= RxDataI_Out_sig;

  RxValid_Out <= RxValid_Out_sig;

  nframesSync <= nframesSync_sig;

  modcod <= modcod_sig;

  fecframe <= fecframe_sig;

  FreqEst <= FreqEst_sig;

  TSorGS <= TSorGS_sig;

  UPL <= UPL_sig;

  DFL <= DFL_sig;

  SYNC <= SYNC_sig;

  bitsReceived <= bitsReceived_sig;

  bitsErrored <= bitsErrored_sig;

END rtl;

