-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_RangeReduction_block.vhd
-- Created: 2025-10-27 18:12:26
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_RangeReduction_block
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/logImplementation/log/RangeReduction
-- Hierarchy Level: 7
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_RangeReduction_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_8_0                         :   IN    std_logic;
        x                                 :   IN    std_logic_vector(47 DOWNTO 0);  -- ufix48_En48
        x_e                               :   OUT   std_logic_vector(48 DOWNTO 0);  -- ufix49_En48
        exp_e                             :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END dvbs2_ip_src_RangeReduction_block;


ARCHITECTURE rtl OF dvbs2_ip_src_RangeReduction_block IS

  -- Component Declarations
  COMPONENT dvbs2_ip_src_leadingZeroDetector_block
    PORT( x                               :   IN    std_logic_vector(47 DOWNTO 0);  -- ufix48_En48
          exp_e                           :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dvbs2_ip_src_leadingZeroDetector_block
    USE ENTITY work.dvbs2_ip_src_leadingZeroDetector_block(rtl);

  -- Signals
  SIGNAL x_unsigned                       : unsigned(47 DOWNTO 0);  -- ufix48_En48
  SIGNAL Delay3_out1                      : unsigned(47 DOWNTO 0);  -- ufix48_En48
  SIGNAL Delay_reg                        : vector_of_unsigned48(0 TO 1);  -- ufix48 [2]
  SIGNAL Delay_out1                       : unsigned(47 DOWNTO 0);  -- ufix48_En48
  SIGNAL Delay1_out1                      : unsigned(47 DOWNTO 0);  -- ufix48_En48
  SIGNAL exp_e_1                          : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL exp_e_unsigned                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay2_reg                       : vector_of_unsigned8(0 TO 1);  -- ufix8 [2]
  SIGNAL Delay2_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL x_e_1                            : unsigned(47 DOWNTO 0);  -- ufix48_En48
  SIGNAL Delay4_out1                      : unsigned(47 DOWNTO 0);  -- ufix48_En48
  SIGNAL Constant_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add_add_cast                     : unsigned(55 DOWNTO 0);  -- ufix56_En48
  SIGNAL Add_add_cast_1                   : unsigned(55 DOWNTO 0);  -- ufix56_En48
  SIGNAL Add_add_temp                     : unsigned(55 DOWNTO 0);  -- ufix56_En48
  SIGNAL Add_out1                         : unsigned(48 DOWNTO 0);  -- ufix49_En48
  SIGNAL Delay6_out1                      : unsigned(48 DOWNTO 0);  -- ufix49_En48
  SIGNAL Delay5_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay7_out1                      : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  -- Range of x_e=[1,2)

  u_leadingZeroDetector : dvbs2_ip_src_leadingZeroDetector_block
    PORT MAP( x => std_logic_vector(Delay1_out1),  -- ufix48_En48
              exp_e => exp_e_1  -- uint8
              );

  x_unsigned <= unsigned(x);

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_out1 <= to_unsigned(0, 48);
      ELSIF enb_1_8_0 = '1' THEN
        Delay3_out1 <= x_unsigned;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_reg <= (OTHERS => to_unsigned(0, 48));
      ELSIF enb_1_8_0 = '1' THEN
        Delay_reg(0) <= Delay3_out1;
        Delay_reg(1) <= Delay_reg(0);
      END IF;
    END IF;
  END PROCESS Delay_process;

  Delay_out1 <= Delay_reg(1);

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out1 <= to_unsigned(0, 48);
      ELSIF enb_1_8_0 = '1' THEN
        Delay1_out1 <= x_unsigned;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  exp_e_unsigned <= unsigned(exp_e_1);

  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_reg <= (OTHERS => to_unsigned(16#00#, 8));
      ELSIF enb_1_8_0 = '1' THEN
        Delay2_reg(0) <= exp_e_unsigned;
        Delay2_reg(1) <= Delay2_reg(0);
      END IF;
    END IF;
  END PROCESS Delay2_process;

  Delay2_out1 <= Delay2_reg(1);

  x_e_1 <= Delay_out1 sll to_integer(Delay2_out1);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_out1 <= to_unsigned(0, 48);
      ELSIF enb_1_8_0 = '1' THEN
        Delay4_out1 <= x_e_1;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  Constant_out1 <= to_unsigned(16#01#, 8);

  Add_add_cast <= resize(Delay4_out1, 56);
  Add_add_cast_1 <= Constant_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  Add_add_temp <= Add_add_cast + Add_add_cast_1;
  Add_out1 <= Add_add_temp(48 DOWNTO 0);

  Delay6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay6_out1 <= to_unsigned(0, 49);
      ELSIF enb_1_8_0 = '1' THEN
        Delay6_out1 <= Add_out1;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  x_e <= std_logic_vector(Delay6_out1);

  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_out1 <= to_unsigned(16#00#, 8);
      ELSIF enb_1_8_0 = '1' THEN
        Delay5_out1 <= Delay2_out1;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  Delay7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay7_out1 <= to_unsigned(16#00#, 8);
      ELSIF enb_1_8_0 = '1' THEN
        Delay7_out1 <= Delay5_out1;
      END IF;
    END IF;
  END PROCESS Delay7_process;


  exp_e <= std_logic_vector(Delay7_out1);

END rtl;

