-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_Quadrant_Correction.vhd
-- Created: 2025-10-27 18:12:28
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_Quadrant_Correction
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency 
-- and Coarse Phase Synchronizer/Coarse Phase Synchronizer/Unwrapping algorithm/HDL_CMA_core/Quadrant_Correctio
-- Hierarchy Level: 8
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dvbs2_ip_src_Quadrant_Correction IS
  PORT( zin                               :   IN    std_logic_vector(19 DOWNTO 0);  -- sfix20_En19
        QA_Control                        :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
        zout                              :   OUT   std_logic_vector(19 DOWNTO 0)  -- sfix20_En19
        );
END dvbs2_ip_src_Quadrant_Correction;


ARCHITECTURE rtl OF dvbs2_ip_src_Quadrant_Correction IS

  -- Signals
  SIGNAL QA_Control_unsigned              : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL yZeroXPositive                   : std_logic;  -- ufix1
  SIGNAL yZeroXNegative                   : std_logic;  -- ufix1
  SIGNAL xyNegative                       : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL AbsRel                           : std_logic;  -- ufix1
  SIGNAL pidivtwo                         : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL zin_signed                       : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL pivdivtwosubout                  : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL mux1out                          : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL Negation_cast                    : signed(20 DOWNTO 0);  -- sfix21_En19
  SIGNAL Negation_cast_1                  : signed(20 DOWNTO 0);  -- sfix21_En19
  SIGNAL Negation_cast_2                  : signed(21 DOWNTO 0);  -- sfix22_En19
  SIGNAL mux1out_negate                   : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL pionepos                         : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL pi_subtraction                   : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL pioneneg                         : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL negpi_addition                   : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL mux2out                          : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL mux5out                          : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL zero                             : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL mux6out                          : signed(19 DOWNTO 0);  -- sfix20_En19

BEGIN
  QA_Control_unsigned <= unsigned(QA_Control);

  yZeroXPositive <= QA_Control_unsigned(4);

  yZeroXNegative <= QA_Control_unsigned(3);

  xyNegative <= QA_Control_unsigned(1 DOWNTO 0);

  AbsRel <= QA_Control_unsigned(2);

  pidivtwo <= to_signed(16#40000#, 20);

  zin_signed <= signed(zin);

  pivdivtwosubout <= pidivtwo - zin_signed;

  
  mux1out <= pivdivtwosubout WHEN AbsRel = '0' ELSE
      zin_signed;

  Negation_cast <= resize(mux1out, 21);
  Negation_cast_1 <=  - (Negation_cast);
  Negation_cast_2 <= resize(Negation_cast_1, 22);
  mux1out_negate <= Negation_cast_2(19 DOWNTO 0);

  pionepos <= to_signed(16#7FFFF#, 20);

  pi_subtraction <= pionepos - mux1out;

  pioneneg <= to_signed(-16#80000#, 20);

  negpi_addition <= pioneneg + mux1out;

  
  mux2out <= mux1out WHEN xyNegative = to_unsigned(16#0#, 2) ELSE
      mux1out_negate WHEN xyNegative = to_unsigned(16#1#, 2) ELSE
      pi_subtraction WHEN xyNegative = to_unsigned(16#2#, 2) ELSE
      negpi_addition;

  
  mux5out <= mux2out WHEN yZeroXNegative = '0' ELSE
      pionepos;

  zero <= to_signed(16#00000#, 20);

  
  mux6out <= mux5out WHEN yZeroXPositive = '0' ELSE
      zero;

  zout <= std_logic_vector(mux6out);

END rtl;

