-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_FilterTapSystolicPreAddWvlIn.vhd
-- Created: 2025-10-27 18:12:29
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_FilterTapSystolicPreAddWvlIn
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency 
-- and Coarse Phase Synchronizer/Time and Coarse Frequency Synchronizer/RRC Receive Matched Filter/Filter/subFilter/FilterTapSystolicPreAddWvlIn
-- Hierarchy Level: 9
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_FilterTapSystolicPreAddWvlIn IS
  PORT( clk                               :   IN    std_logic;
        enb_1_8_0                         :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        dinPreAdd                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        coefIn_0                          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En17
        addin                             :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48_En32
        dinRegVld                         :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        dinDly2                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        tapout                            :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En32
        );
END dvbs2_ip_src_FilterTapSystolicPreAddWvlIn;


ARCHITECTURE rtl OF dvbs2_ip_src_FilterTapSystolicPreAddWvlIn IS

  -- Signals
  SIGNAL dinReg2_0_re_signed              : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL dinPreAdd_signed                 : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL coefIn_0_signed                  : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL addin_signed                     : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL fTap_mult_reg                    : signed(36 DOWNTO 0) := to_signed(0, 37);  -- sfix37
  SIGNAL fTap_din1_reg1                   : signed(17 DOWNTO 0) := to_signed(16#00000#, 18);  -- sfix18
  SIGNAL fTap_din1_reg2                   : signed(17 DOWNTO 0) := to_signed(16#00000#, 18);  -- sfix18
  SIGNAL fTap_din2_reg1                   : signed(17 DOWNTO 0) := to_signed(16#00000#, 18);  -- sfix18
  SIGNAL fTap_preAdd_reg                  : signed(18 DOWNTO 0) := to_signed(16#00000#, 19);  -- sfix19
  SIGNAL fTap_addout_reg                  : signed(47 DOWNTO 0) := to_signed(0, 48);  -- sfix48
  SIGNAL fTap_coef_reg1                   : signed(17 DOWNTO 0) := to_signed(16#00000#, 18);  -- sfix18
  SIGNAL fTap_coef_reg2                   : signed(17 DOWNTO 0) := to_signed(16#00000#, 18);  -- sfix18
  SIGNAL fTap_mult_reg_next               : signed(36 DOWNTO 0);  -- sfix37_En32
  SIGNAL fTap_din1_reg1_next              : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL fTap_din1_reg2_next              : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL fTap_din2_reg1_next              : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL fTap_preAdd_reg_next             : signed(18 DOWNTO 0);  -- sfix19_En15
  SIGNAL fTap_addout_reg_next             : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL fTap_coef_reg1_next              : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL fTap_coef_reg2_next              : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL dinDly2_tmp                      : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL tapout_tmp                       : signed(47 DOWNTO 0);  -- sfix48_En32

BEGIN
  dinReg2_0_re_signed <= signed(dinReg2_0_re);

  dinPreAdd_signed <= signed(dinPreAdd);

  coefIn_0_signed <= signed(coefIn_0);

  addin_signed <= signed(addin);

  -- FilterTapSystolicPreAddWvldIn
  fTap_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb_1_8_0 = '1' THEN
        IF syncReset = '1' THEN
          fTap_din1_reg1 <= to_signed(16#00000#, 18);
          fTap_din1_reg2 <= to_signed(16#00000#, 18);
          fTap_din2_reg1 <= to_signed(16#00000#, 18);
          fTap_preAdd_reg <= to_signed(16#00000#, 19);
          fTap_coef_reg1 <= to_signed(16#00000#, 18);
          fTap_coef_reg2 <= to_signed(16#00000#, 18);
          fTap_mult_reg <= to_signed(0, 37);
          fTap_addout_reg <= to_signed(0, 48);
        ELSE 
          fTap_mult_reg <= fTap_mult_reg_next;
          fTap_din1_reg1 <= fTap_din1_reg1_next;
          fTap_din1_reg2 <= fTap_din1_reg2_next;
          fTap_din2_reg1 <= fTap_din2_reg1_next;
          fTap_preAdd_reg <= fTap_preAdd_reg_next;
          fTap_addout_reg <= fTap_addout_reg_next;
          fTap_coef_reg1 <= fTap_coef_reg1_next;
          fTap_coef_reg2 <= fTap_coef_reg2_next;
        END IF;
      END IF;
    END IF;
  END PROCESS fTap_process;

  fTap_output : PROCESS (addin_signed, coefIn_0_signed, dinPreAdd_signed, dinReg2_0_re_signed,
       dinRegVld, fTap_addout_reg, fTap_coef_reg1, fTap_coef_reg2,
       fTap_din1_reg1, fTap_din1_reg2, fTap_din2_reg1, fTap_mult_reg,
       fTap_preAdd_reg)
    VARIABLE add_cast : signed(47 DOWNTO 0);
    VARIABLE add_cast_0 : signed(18 DOWNTO 0);
    VARIABLE add_cast_1 : signed(18 DOWNTO 0);
  BEGIN
    add_cast := to_signed(0, 48);
    add_cast_0 := to_signed(16#00000#, 19);
    add_cast_1 := to_signed(16#00000#, 19);
    fTap_mult_reg_next <= fTap_mult_reg;
    fTap_din1_reg1_next <= fTap_din1_reg1;
    fTap_din1_reg2_next <= fTap_din1_reg2;
    fTap_din2_reg1_next <= fTap_din2_reg1;
    fTap_preAdd_reg_next <= fTap_preAdd_reg;
    fTap_addout_reg_next <= fTap_addout_reg;
    fTap_coef_reg1_next <= fTap_coef_reg1;
    fTap_coef_reg2_next <= fTap_coef_reg2;
    IF dinRegVld = '1' THEN 
      add_cast := resize(fTap_mult_reg, 48);
      fTap_addout_reg_next <= add_cast + addin_signed;
      fTap_mult_reg_next <= fTap_preAdd_reg * fTap_coef_reg2;
      add_cast_0 := resize(fTap_din1_reg2, 19);
      add_cast_1 := resize(fTap_din2_reg1, 19);
      fTap_preAdd_reg_next <= add_cast_0 + add_cast_1;
      fTap_din1_reg2_next <= fTap_din1_reg1;
      fTap_din1_reg1_next <= dinReg2_0_re_signed;
      fTap_din2_reg1_next <= dinPreAdd_signed;
      fTap_coef_reg2_next <= fTap_coef_reg1;
      fTap_coef_reg1_next <= coefIn_0_signed;
    END IF;
    dinDly2_tmp <= fTap_din1_reg2;
    tapout_tmp <= fTap_addout_reg;
  END PROCESS fTap_output;


  dinDly2 <= std_logic_vector(dinDly2_tmp);

  tapout <= std_logic_vector(tapout_tmp);

END rtl;

