-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_symDemodPiBy2BPSKSc.vhd
-- Created: 2025-10-27 18:12:27
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_symDemodPiBy2BPSKSc
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/Symbol Demodulaor/DVBS2 
-- Symbol Demodulator/symDemodPiBy2BPSKS
-- Hierarchy Level: 6
-- Model version: 9.0
-- 
-- Pi/2 BPSK scalar Demodulation
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_symDemodPiBy2BPSKSc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
        dataIn_im                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
        validIn                           :   IN    std_logic;  -- ufix1
        dataOut                           :   OUT   std_logic_vector(20 DOWNTO 0);  -- sfix21_En14
        validOut                          :   OUT   std_logic  -- ufix1
        );
END dvbs2_ip_src_symDemodPiBy2BPSKSc;


ARCHITECTURE rtl OF dvbs2_ip_src_symDemodPiBy2BPSKSc IS

  -- Signals
  SIGNAL delayMatch1_reg                  : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL delayMatch1_out1                 : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Constant2_out1                   : std_logic;
  SIGNAL Even_sym_counter_out1            : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL delayMatch_reg                   : vector_of_unsigned8(0 TO 1);  -- ufix8 [2]
  SIGNAL delayMatch_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL dataIn_im_signed                 : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL HwModeRegister2_out1             : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Constant1_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL HwModeRegister3_out1             : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Product1_out1                    : signed(33 DOWNTO 0);  -- sfix34_En27
  SIGNAL PipelineRegister1_out1           : signed(33 DOWNTO 0);  -- sfix34_En27
  SIGNAL Constant_out1                    : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL HwModeRegister_out1              : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL dataIn_re_signed                 : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL HwModeRegister1_out1             : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Product_out1                     : signed(33 DOWNTO 0);  -- sfix34_En27
  SIGNAL PipelineRegister_out1            : signed(33 DOWNTO 0);  -- sfix34_En27
  SIGNAL Add1_sub_cast                    : signed(34 DOWNTO 0);  -- sfix35_En27
  SIGNAL Add1_sub_cast_1                  : signed(34 DOWNTO 0);  -- sfix35_En27
  SIGNAL Add1_out1                        : signed(34 DOWNTO 0);  -- sfix35_En27
  SIGNAL Constant10_out1                  : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL Add_add_cast                     : signed(34 DOWNTO 0);  -- sfix35_En27
  SIGNAL Add_add_cast_1                   : signed(34 DOWNTO 0);  -- sfix35_En27
  SIGNAL Add_out1                         : signed(34 DOWNTO 0);  -- sfix35_En27
  SIGNAL Switch_out1                      : signed(34 DOWNTO 0);  -- sfix35_En27
  SIGNAL Data_Type_Conversion_out1        : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL Switch1_out1                     : signed(20 DOWNTO 0);  -- sfix21_En14
  SIGNAL delayMatch2_reg                  : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL delayMatch2_out1                 : std_logic;

BEGIN
  delayMatch1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delayMatch1_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        delayMatch1_reg(0) <= validIn;
        delayMatch1_reg(1) <= delayMatch1_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch1_process;

  delayMatch1_out1 <= delayMatch1_reg(1);

  
  switch_compare_1 <= '1' WHEN delayMatch1_out1 > '0' ELSE
      '0';

  Constant2_out1 <= '0';

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = -1
  --  count to value  = 0
  Even_sym_counter_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Even_sym_counter_out1 <= to_unsigned(16#01#, 8);
      ELSIF enb = '1' THEN
        IF Constant2_out1 = '1' THEN 
          Even_sym_counter_out1 <= to_unsigned(16#01#, 8);
        ELSIF validIn = '1' THEN 
          IF Even_sym_counter_out1 = to_unsigned(16#00#, 8) THEN 
            Even_sym_counter_out1 <= to_unsigned(16#01#, 8);
          ELSE 
            Even_sym_counter_out1 <= Even_sym_counter_out1 + to_unsigned(16#FF#, 8);
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS Even_sym_counter_process;


  delayMatch_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delayMatch_reg <= (OTHERS => to_unsigned(16#00#, 8));
      ELSIF enb = '1' THEN
        delayMatch_reg(0) <= Even_sym_counter_out1;
        delayMatch_reg(1) <= delayMatch_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  delayMatch_out1 <= delayMatch_reg(1);

  
  switch_compare_1_1 <= '1' WHEN delayMatch_out1 > to_unsigned(16#00#, 8) ELSE
      '0';

  dataIn_im_signed <= signed(dataIn_im);

  HwModeRegister2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        HwModeRegister2_out1 <= to_signed(16#00000#, 18);
      ELSIF enb = '1' THEN
        HwModeRegister2_out1 <= dataIn_im_signed;
      END IF;
    END IF;
  END PROCESS HwModeRegister2_process;


  Constant1_out1 <= to_signed(16#5A82#, 16);

  HwModeRegister3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        HwModeRegister3_out1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        HwModeRegister3_out1 <= Constant1_out1;
      END IF;
    END IF;
  END PROCESS HwModeRegister3_process;


  Product1_out1 <= HwModeRegister2_out1 * HwModeRegister3_out1;

  PipelineRegister1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        PipelineRegister1_out1 <= to_signed(0, 34);
      ELSIF enb = '1' THEN
        PipelineRegister1_out1 <= Product1_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister1_process;


  Constant_out1 <= to_signed(16#5A82#, 16);

  HwModeRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        HwModeRegister_out1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        HwModeRegister_out1 <= Constant_out1;
      END IF;
    END IF;
  END PROCESS HwModeRegister_process;


  dataIn_re_signed <= signed(dataIn_re);

  HwModeRegister1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        HwModeRegister1_out1 <= to_signed(16#00000#, 18);
      ELSIF enb = '1' THEN
        HwModeRegister1_out1 <= dataIn_re_signed;
      END IF;
    END IF;
  END PROCESS HwModeRegister1_process;


  Product_out1 <= HwModeRegister_out1 * HwModeRegister1_out1;

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        PipelineRegister_out1 <= to_signed(0, 34);
      ELSIF enb = '1' THEN
        PipelineRegister_out1 <= Product_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  Add1_sub_cast <= resize(PipelineRegister1_out1, 35);
  Add1_sub_cast_1 <= resize(PipelineRegister_out1, 35);
  Add1_out1 <= Add1_sub_cast - Add1_sub_cast_1;

  Constant10_out1 <= to_signed(16#000000#, 21);

  Add_add_cast <= resize(PipelineRegister_out1, 35);
  Add_add_cast_1 <= resize(PipelineRegister1_out1, 35);
  Add_out1 <= Add_add_cast + Add_add_cast_1;

  
  Switch_out1 <= Add1_out1 WHEN switch_compare_1_1 = '0' ELSE
      Add_out1;

  Data_Type_Conversion_out1 <= Switch_out1(33 DOWNTO 13);

  
  Switch1_out1 <= Constant10_out1 WHEN switch_compare_1 = '0' ELSE
      Data_Type_Conversion_out1;

  dataOut <= std_logic_vector(Switch1_out1);

  delayMatch2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delayMatch2_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        delayMatch2_reg(0) <= validIn;
        delayMatch2_reg(1) <= delayMatch2_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch2_process;

  delayMatch2_out1 <= delayMatch2_reg(1);

  validOut <= delayMatch2_out1;

END rtl;

