-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_L_and_R_Algorithm_18_point.vhd
-- Created: 2025-10-27 18:12:29
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_L_and_R_Algorithm_18_point
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency 
-- and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point
-- Hierarchy Level: 7
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_L_and_R_Algorithm_18_point IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_32_0                        :   IN    std_logic;
        z_re                              :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
        z_im                              :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
        zvalid                            :   IN    std_logic;
        dataIn_re                         :   OUT   std_logic_vector(37 DOWNTO 0);  -- sfix38_En22
        dataIn_im                         :   OUT   std_logic_vector(37 DOWNTO 0)  -- sfix38_En22
        );
END dvbs2_ip_src_L_and_R_Algorithm_18_point;


ARCHITECTURE rtl OF dvbs2_ip_src_L_and_R_Algorithm_18_point IS

  -- Component Declarations
  COMPONENT dvbs2_ip_src_Compute_R_m_for_1_to_6
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          z_re                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          z_im                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          zvalid                          :   IN    std_logic;
          sum_re                          :   OUT   std_logic_vector(35 DOWNTO 0);  -- sfix36_En22
          sum_im                          :   OUT   std_logic_vector(35 DOWNTO 0)  -- sfix36_En22
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_Compute_R_m_for_7_to_12
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          z_re                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          z_im                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          zvalid                          :   IN    std_logic;
          sum_re                          :   OUT   std_logic_vector(35 DOWNTO 0);  -- sfix36_En22
          sum_im                          :   OUT   std_logic_vector(35 DOWNTO 0)  -- sfix36_En22
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_Compute_R_m_for_13_to_18
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          z_re                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          z_im                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          zvalid                          :   IN    std_logic;
          sum_re                          :   OUT   std_logic_vector(35 DOWNTO 0);  -- sfix36_En22
          sum_im                          :   OUT   std_logic_vector(35 DOWNTO 0)  -- sfix36_En22
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dvbs2_ip_src_Compute_R_m_for_1_to_6
    USE ENTITY work.dvbs2_ip_src_Compute_R_m_for_1_to_6(rtl);

  FOR ALL : dvbs2_ip_src_Compute_R_m_for_7_to_12
    USE ENTITY work.dvbs2_ip_src_Compute_R_m_for_7_to_12(rtl);

  FOR ALL : dvbs2_ip_src_Compute_R_m_for_13_to_18
    USE ENTITY work.dvbs2_ip_src_Compute_R_m_for_13_to_18(rtl);

  -- Signals
  SIGNAL z_re_signed                      : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL z_im_signed                      : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Data_Type_Conversion_out1_re     : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Data_Type_Conversion_out1_im     : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Delay3_reg_re                    : vector_of_signed16(0 TO 1);  -- sfix16_En11 [2]
  SIGNAL Delay3_reg_im                    : vector_of_signed16(0 TO 1);  -- sfix16_En11 [2]
  SIGNAL Delay3_out1_re                   : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Delay3_out1_im                   : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Delay1_reg                       : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay1_out1                      : std_logic;
  SIGNAL Compute_R_m_for_1_to_6_sum_re    : std_logic_vector(35 DOWNTO 0);  -- ufix36
  SIGNAL Compute_R_m_for_1_to_6_sum_im    : std_logic_vector(35 DOWNTO 0);  -- ufix36
  SIGNAL Compute_R_m_for_1_to_6_sum_re_signed : signed(35 DOWNTO 0);  -- sfix36_En22
  SIGNAL Compute_R_m_for_1_to_6_sum_im_signed : signed(35 DOWNTO 0);  -- sfix36_En22
  SIGNAL Delay2_reg_re                    : vector_of_signed36(0 TO 1);  -- sfix36_En22 [2]
  SIGNAL Delay2_reg_im                    : vector_of_signed36(0 TO 1);  -- sfix36_En22 [2]
  SIGNAL Delay2_out1_re                   : signed(35 DOWNTO 0);  -- sfix36_En22
  SIGNAL Delay2_out1_im                   : signed(35 DOWNTO 0);  -- sfix36_En22
  SIGNAL Compute_R_m_for_7_to_12_sum_re   : std_logic_vector(35 DOWNTO 0);  -- ufix36
  SIGNAL Compute_R_m_for_7_to_12_sum_im   : std_logic_vector(35 DOWNTO 0);  -- ufix36
  SIGNAL Compute_R_m_for_7_to_12_sum_re_signed : signed(35 DOWNTO 0);  -- sfix36_En22
  SIGNAL Compute_R_m_for_7_to_12_sum_im_signed : signed(35 DOWNTO 0);  -- sfix36_En22
  SIGNAL Delay4_reg_re                    : vector_of_signed36(0 TO 1);  -- sfix36_En22 [2]
  SIGNAL Delay4_reg_im                    : vector_of_signed36(0 TO 1);  -- sfix36_En22 [2]
  SIGNAL Delay4_out1_re                   : signed(35 DOWNTO 0);  -- sfix36_En22
  SIGNAL Delay4_out1_im                   : signed(35 DOWNTO 0);  -- sfix36_En22
  SIGNAL Add_stage2_add_cast              : signed(36 DOWNTO 0);  -- sfix37_En22
  SIGNAL Add_stage2_add_cast_1            : signed(36 DOWNTO 0);  -- sfix37_En22
  SIGNAL Add_stage2_add_cast_2            : signed(36 DOWNTO 0);  -- sfix37_En22
  SIGNAL Add_stage2_add_cast_3            : signed(36 DOWNTO 0);  -- sfix37_En22
  SIGNAL Add_op_stage1_re                 : signed(36 DOWNTO 0);  -- sfix37_En22
  SIGNAL Add_op_stage1_im                 : signed(36 DOWNTO 0);  -- sfix37_En22
  SIGNAL Compute_R_m_for_13_to_18_sum_re  : std_logic_vector(35 DOWNTO 0);  -- ufix36
  SIGNAL Compute_R_m_for_13_to_18_sum_im  : std_logic_vector(35 DOWNTO 0);  -- ufix36
  SIGNAL Compute_R_m_for_13_to_18_sum_re_signed : signed(35 DOWNTO 0);  -- sfix36_En22
  SIGNAL Compute_R_m_for_13_to_18_sum_im_signed : signed(35 DOWNTO 0);  -- sfix36_En22
  SIGNAL Delay5_reg_re                    : vector_of_signed36(0 TO 1);  -- sfix36_En22 [2]
  SIGNAL Delay5_reg_im                    : vector_of_signed36(0 TO 1);  -- sfix36_En22 [2]
  SIGNAL Delay5_out1_re                   : signed(35 DOWNTO 0);  -- sfix36_En22
  SIGNAL Delay5_out1_im                   : signed(35 DOWNTO 0);  -- sfix36_En22
  SIGNAL Add_stage3_add_cast              : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Add_stage3_add_cast_1            : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Add_stage3_add_cast_2            : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Add_stage3_add_cast_3            : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Add_out1_re                      : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Add_out1_im                      : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Delay6_reg_re                    : vector_of_signed38(0 TO 1);  -- sfix38_En22 [2]
  SIGNAL Delay6_reg_im                    : vector_of_signed38(0 TO 1);  -- sfix38_En22 [2]
  SIGNAL Delay6_out1_re                   : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Delay6_out1_im                   : signed(37 DOWNTO 0);  -- sfix38_En22

BEGIN
  u_Compute_R_m_for_1_to_6 : dvbs2_ip_src_Compute_R_m_for_1_to_6
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              z_re => std_logic_vector(Delay3_out1_re),  -- sfix16_En11
              z_im => std_logic_vector(Delay3_out1_im),  -- sfix16_En11
              zvalid => Delay1_out1,
              sum_re => Compute_R_m_for_1_to_6_sum_re,  -- sfix36_En22
              sum_im => Compute_R_m_for_1_to_6_sum_im  -- sfix36_En22
              );

  u_Compute_R_m_for_7_to_12 : dvbs2_ip_src_Compute_R_m_for_7_to_12
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              z_re => std_logic_vector(Delay3_out1_re),  -- sfix16_En11
              z_im => std_logic_vector(Delay3_out1_im),  -- sfix16_En11
              zvalid => Delay1_out1,
              sum_re => Compute_R_m_for_7_to_12_sum_re,  -- sfix36_En22
              sum_im => Compute_R_m_for_7_to_12_sum_im  -- sfix36_En22
              );

  u_Compute_R_m_for_13_to_18 : dvbs2_ip_src_Compute_R_m_for_13_to_18
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              z_re => std_logic_vector(Delay3_out1_re),  -- sfix16_En11
              z_im => std_logic_vector(Delay3_out1_im),  -- sfix16_En11
              zvalid => Delay1_out1,
              sum_re => Compute_R_m_for_13_to_18_sum_re,  -- sfix36_En22
              sum_im => Compute_R_m_for_13_to_18_sum_im  -- sfix36_En22
              );

  z_re_signed <= signed(z_re);

  z_im_signed <= signed(z_im);

  Data_Type_Conversion_out1_re <= z_re_signed(17 DOWNTO 2);
  Data_Type_Conversion_out1_im <= z_im_signed(17 DOWNTO 2);

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_reg_re <= (OTHERS => to_signed(16#0000#, 16));
        Delay3_reg_im <= (OTHERS => to_signed(16#0000#, 16));
      ELSIF enb_1_32_0 = '1' THEN
        Delay3_reg_im(0) <= Data_Type_Conversion_out1_im;
        Delay3_reg_im(1) <= Delay3_reg_im(0);
        Delay3_reg_re(0) <= Data_Type_Conversion_out1_re;
        Delay3_reg_re(1) <= Delay3_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay3_process;

  Delay3_out1_re <= Delay3_reg_re(1);
  Delay3_out1_im <= Delay3_reg_im(1);

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_reg <= (OTHERS => '0');
      ELSIF enb_1_32_0 = '1' THEN
        Delay1_reg(0) <= zvalid;
        Delay1_reg(1) <= Delay1_reg(0);
      END IF;
    END IF;
  END PROCESS Delay1_process;

  Delay1_out1 <= Delay1_reg(1);

  Compute_R_m_for_1_to_6_sum_re_signed <= signed(Compute_R_m_for_1_to_6_sum_re);

  Compute_R_m_for_1_to_6_sum_im_signed <= signed(Compute_R_m_for_1_to_6_sum_im);

  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_reg_re <= (OTHERS => to_signed(0, 36));
        Delay2_reg_im <= (OTHERS => to_signed(0, 36));
      ELSIF enb_1_32_0 = '1' THEN
        Delay2_reg_im(0) <= Compute_R_m_for_1_to_6_sum_im_signed;
        Delay2_reg_im(1) <= Delay2_reg_im(0);
        Delay2_reg_re(0) <= Compute_R_m_for_1_to_6_sum_re_signed;
        Delay2_reg_re(1) <= Delay2_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay2_process;

  Delay2_out1_re <= Delay2_reg_re(1);
  Delay2_out1_im <= Delay2_reg_im(1);

  Compute_R_m_for_7_to_12_sum_re_signed <= signed(Compute_R_m_for_7_to_12_sum_re);

  Compute_R_m_for_7_to_12_sum_im_signed <= signed(Compute_R_m_for_7_to_12_sum_im);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_reg_re <= (OTHERS => to_signed(0, 36));
        Delay4_reg_im <= (OTHERS => to_signed(0, 36));
      ELSIF enb_1_32_0 = '1' THEN
        Delay4_reg_im(0) <= Compute_R_m_for_7_to_12_sum_im_signed;
        Delay4_reg_im(1) <= Delay4_reg_im(0);
        Delay4_reg_re(0) <= Compute_R_m_for_7_to_12_sum_re_signed;
        Delay4_reg_re(1) <= Delay4_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay4_process;

  Delay4_out1_re <= Delay4_reg_re(1);
  Delay4_out1_im <= Delay4_reg_im(1);

  Add_stage2_add_cast <= resize(Delay2_out1_re, 37);
  Add_stage2_add_cast_1 <= resize(Delay4_out1_re, 37);
  Add_op_stage1_re <= Add_stage2_add_cast + Add_stage2_add_cast_1;
  Add_stage2_add_cast_2 <= resize(Delay2_out1_im, 37);
  Add_stage2_add_cast_3 <= resize(Delay4_out1_im, 37);
  Add_op_stage1_im <= Add_stage2_add_cast_2 + Add_stage2_add_cast_3;

  Compute_R_m_for_13_to_18_sum_re_signed <= signed(Compute_R_m_for_13_to_18_sum_re);

  Compute_R_m_for_13_to_18_sum_im_signed <= signed(Compute_R_m_for_13_to_18_sum_im);

  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_reg_re <= (OTHERS => to_signed(0, 36));
        Delay5_reg_im <= (OTHERS => to_signed(0, 36));
      ELSIF enb_1_32_0 = '1' THEN
        Delay5_reg_im(0) <= Compute_R_m_for_13_to_18_sum_im_signed;
        Delay5_reg_im(1) <= Delay5_reg_im(0);
        Delay5_reg_re(0) <= Compute_R_m_for_13_to_18_sum_re_signed;
        Delay5_reg_re(1) <= Delay5_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay5_process;

  Delay5_out1_re <= Delay5_reg_re(1);
  Delay5_out1_im <= Delay5_reg_im(1);

  Add_stage3_add_cast <= resize(Add_op_stage1_re, 38);
  Add_stage3_add_cast_1 <= resize(Delay5_out1_re, 38);
  Add_out1_re <= Add_stage3_add_cast + Add_stage3_add_cast_1;
  Add_stage3_add_cast_2 <= resize(Add_op_stage1_im, 38);
  Add_stage3_add_cast_3 <= resize(Delay5_out1_im, 38);
  Add_out1_im <= Add_stage3_add_cast_2 + Add_stage3_add_cast_3;

  Delay6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay6_reg_re <= (OTHERS => to_signed(0, 38));
        Delay6_reg_im <= (OTHERS => to_signed(0, 38));
      ELSIF enb_1_32_0 = '1' THEN
        Delay6_reg_im(0) <= Add_out1_im;
        Delay6_reg_im(1) <= Delay6_reg_im(0);
        Delay6_reg_re(0) <= Add_out1_re;
        Delay6_reg_re(1) <= Delay6_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay6_process;

  Delay6_out1_re <= Delay6_reg_re(1);
  Delay6_out1_im <= Delay6_reg_im(1);

  dataIn_re <= std_logic_vector(Delay6_out1_re);

  dataIn_im <= std_logic_vector(Delay6_out1_im);

END rtl;

