open_system('gm_resource_sharing_multi_module_phase_shift_generator_base');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_resource_sharing_multi_module_phase_shift_generator_base/pwm_generator/Product', 'user2');
annotate_port('gm_resource_sharing_multi_module_phase_shift_generator_base/pwm_generator/Product', 0, 1, 'cp : 9.272 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_resource_sharing_multi_module_phase_shift_generator_base/pwm_generator/ctr_0_2', 'user1');
annotate_port('gm_resource_sharing_multi_module_phase_shift_generator_base/pwm_generator/ctr_0_2', 0, 1, 'cp : 0.84 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_resource_sharing_multi_module_phase_shift_generator_base/pwm_generator/Serializer_Subnetwork', 'user2');
annotate_port('gm_resource_sharing_multi_module_phase_shift_generator_base/pwm_generator/Serializer_Subnetwork', 0, 1, 'cp : 3.526 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_resource_sharing_multi_module_phase_shift_generator_base/pwm_generator/Deserializer_Subnetwork', 'user2');
annotate_port('gm_resource_sharing_multi_module_phase_shift_generator_base/pwm_generator/Deserializer_Subnetwork', 1, 1, 'cp : 9.606 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_resource_sharing_multi_module_phase_shift_generator_base/pwm_generator/Serializer_Subnetwork/splitcomp_multiport', 'user2');
annotate_port('gm_resource_sharing_multi_module_phase_shift_generator_base/pwm_generator/Serializer_Subnetwork/splitcomp_multiport', 0, 1, 'cp : 3.526 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_resource_sharing_multi_module_phase_shift_generator_base/pwm_generator/Deserializer_Subnetwork/tapped_delay', 'user1');
annotate_port('gm_resource_sharing_multi_module_phase_shift_generator_base/pwm_generator/Deserializer_Subnetwork/tapped_delay', 1, 1, 'cp : 9.606 ns');
