-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\resource_sharing_multi_module_phase_shift_generator_base\pwm_generator_pkg.vhd
-- Created: 2026-04-13 16:31:22
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE pwm_generator_pkg IS
  TYPE vector_of_unsigned32 IS ARRAY (NATURAL RANGE <>) OF unsigned(31 DOWNTO 0);
  TYPE vector_of_unsigned16 IS ARRAY (NATURAL RANGE <>) OF unsigned(15 DOWNTO 0);
END pwm_generator_pkg;

