open_system('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/Data Type Conversion2', 'user2');
annotate_port('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/Data Type Conversion2', 0, 1, 'cp : 9.834 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/Relational Operator3', 'user2');
annotate_port('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/Relational Operator3', 0, 1, 'cp : 11.638 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/Product1_out_dtc', 'user2');
annotate_port('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/Product1_out_dtc', 0, 1, 'cp : 9.834 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/crp_temp_shared', 'user2');
annotate_port('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/crp_temp_shared', 0, 3, 'cp : 9.834 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/t2', 'user1');
annotate_port('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/t2', 1, 1, 'cp : 11.972 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/ctr_0_2', 'user1');
annotate_port('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/ctr_0_2', 0, 1, 'cp : 0.84 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/crp_temp_shared/Product2', 'user2');
annotate_port('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/crp_temp_shared/Product2', 0, 1, 'cp : 9.272 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/crp_temp_shared/Serializer_Subnetwork', 'user2');
annotate_port('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/crp_temp_shared/Serializer_Subnetwork', 0, 1, 'cp : 3.526 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/crp_temp_shared/Product1_out1_bypass', 'user2');
annotate_port('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/crp_temp_shared/Product1_out1_bypass', 0, 1, 'cp : 9.834 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/crp_temp_shared/Serializer_Subnetwork/splitcomp_multiport', 'user2');
annotate_port('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/crp_temp_shared/Serializer_Subnetwork/splitcomp_multiport', 0, 1, 'cp : 3.526 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/crp_temp_shared/Product1_out1_bypass/Product1_out1_enb', 'user2');
annotate_port('gm_optimized_area_multi_module_phase_shift_generator_built_in_counter/pwm/crp_temp_shared/Product1_out1_bypass/Product1_out1_enb', 0, 1, 'cp : 9.834 ns');
