-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_Discard_Unsupported_Frames.vhd
-- Created: 2025-10-27 18:12:26
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_Discard_Unsupported_Frames
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/Discard Unsupported 
-- Frame
-- Hierarchy Level: 4
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dvbs2_ip_src_Discard_Unsupported_Frames IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        endOfPLSC                         :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
        dataIn_im                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
        validIn                           :   IN    std_logic;
        MODCOD                            :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
        dataOut_re                        :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
        dataOut_im                        :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
        validOut                          :   OUT   std_logic;
        paramCapture                      :   OUT   std_logic;
        modIdx                            :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        codIdx                            :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        FECFrameOut                       :   OUT   std_logic
        );
END dvbs2_ip_src_Discard_Unsupported_Frames;


ARCHITECTURE rtl OF dvbs2_ip_src_Discard_Unsupported_Frames IS

  -- Component Declarations
  COMPONENT dvbs2_ip_src_convertMODCOD
    PORT( modcod                          :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
          modIdx                          :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          codIdx                          :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dvbs2_ip_src_convertMODCOD
    USE ENTITY work.dvbs2_ip_src_convertMODCOD(rtl);

  -- Signals
  SIGNAL Delay5_out1                      : std_logic;
  SIGNAL Delay4_out1                      : std_logic;
  SIGNAL Delay10_reg                      : std_logic_vector(7 DOWNTO 0);  -- ufix1 [8]
  SIGNAL Delay10_out1                     : std_logic;
  SIGNAL Delay7_out1                      : std_logic;
  SIGNAL MODCOD_unsigned                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Unit_Delay_Enabled_Synchronous_out1 : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL Compare_To_Constant5_out1        : std_logic;
  SIGNAL Logical_Operator4_out1           : std_logic;
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL Compare_To_Constant2_out1        : std_logic;
  SIGNAL Compare_To_Constant3_out1        : std_logic;
  SIGNAL Compare_To_Constant4_out1        : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL Constant1_out1                   : std_logic;
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1 : std_logic;
  SIGNAL Logical_Operator1_out1           : std_logic;
  SIGNAL Logical_Operator3_out1           : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable_Synchronous_out1 : std_logic;
  SIGNAL Logical_Operator2_out1           : std_logic;
  SIGNAL Constant_out1_re                 : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Constant_out1_im                 : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL dataIn_re_signed                 : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL dataIn_im_signed                 : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Delay6_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Delay6_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Delay8_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Delay8_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Switch_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Switch_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Delay9_out1                      : std_logic;
  SIGNAL Logical_Operator5_out1           : std_logic;
  SIGNAL Delay3_out1                      : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Delay2_out1                      : std_logic;

BEGIN
  u_convertMODCOD : dvbs2_ip_src_convertMODCOD
    PORT MAP( modcod => std_logic_vector(Delay3_out1),  -- ufix5
              modIdx => modIdx,  -- ufix2
              codIdx => codIdx  -- ufix4
              );

  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay5_out1 <= validIn;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay4_out1 <= Delay5_out1;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  Delay10_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay10_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        Delay10_reg(0) <= endOfPLSC;
        Delay10_reg(7 DOWNTO 1) <= Delay10_reg(6 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay10_process;

  Delay10_out1 <= Delay10_reg(7);

  Delay7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay7_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay7_out1 <= Delay10_out1;
      END IF;
    END IF;
  END PROCESS Delay7_process;


  MODCOD_unsigned <= unsigned(MODCOD);

  Unit_Delay_Enabled_Synchronous_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1 <= to_unsigned(16#00#, 5);
      ELSIF enb = '1' AND Delay10_out1 = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1 <= MODCOD_unsigned;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous_process;


  
  Compare_To_Constant_out1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1 = to_unsigned(16#00#, 5) ELSE
      '0';

  
  Compare_To_Constant5_out1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1 > to_unsigned(16#1C#, 5) ELSE
      '0';

  Logical_Operator4_out1 <= Compare_To_Constant_out1 OR Compare_To_Constant5_out1;

  
  Compare_To_Constant1_out1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1 = to_unsigned(16#0B#, 5) ELSE
      '0';

  
  Compare_To_Constant2_out1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1 = to_unsigned(16#11#, 5) ELSE
      '0';

  
  Compare_To_Constant3_out1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1 = to_unsigned(16#17#, 5) ELSE
      '0';

  
  Compare_To_Constant4_out1 <= '1' WHEN Unit_Delay_Enabled_Synchronous_out1 = to_unsigned(16#1C#, 5) ELSE
      '0';

  Logical_Operator_out1 <= Compare_To_Constant4_out1 OR (Compare_To_Constant3_out1 OR (Compare_To_Constant1_out1 OR Compare_To_Constant2_out1));

  Constant1_out1 <= '1';

  Unit_Delay_Enabled_Synchronous1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1 <= '0';
      ELSIF enb = '1' AND Delay10_out1 = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1 <= Constant1_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous1_process;


  Logical_Operator1_out1 <= Logical_Operator_out1 AND Unit_Delay_Enabled_Synchronous1_out1;

  Logical_Operator3_out1 <= Logical_Operator4_out1 OR Logical_Operator1_out1;

  Unit_Delay_Enabled_Resettable_Synchronous_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Resettable_Synchronous_out1 <= '0';
      ELSIF enb = '1' THEN
        IF Logical_Operator3_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable_Synchronous_out1 <= '0';
        ELSIF Delay7_out1 = '1' THEN
          Unit_Delay_Enabled_Resettable_Synchronous_out1 <= Delay7_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable_Synchronous_process;


  Logical_Operator2_out1 <= Delay4_out1 AND Unit_Delay_Enabled_Resettable_Synchronous_out1;

  Constant_out1_re <= to_signed(16#00000#, 18);
  Constant_out1_im <= to_signed(16#00000#, 18);

  dataIn_re_signed <= signed(dataIn_re);

  dataIn_im_signed <= signed(dataIn_im);

  Delay6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay6_out1_re <= to_signed(16#00000#, 18);
        Delay6_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb = '1' THEN
        Delay6_out1_re <= dataIn_re_signed;
        Delay6_out1_im <= dataIn_im_signed;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  Delay8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay8_out1_re <= to_signed(16#00000#, 18);
        Delay8_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb = '1' THEN
        Delay8_out1_re <= Delay6_out1_re;
        Delay8_out1_im <= Delay6_out1_im;
      END IF;
    END IF;
  END PROCESS Delay8_process;


  
  Switch_out1_re <= Constant_out1_re WHEN Logical_Operator2_out1 = '0' ELSE
      Delay8_out1_re;
  
  Switch_out1_im <= Constant_out1_im WHEN Logical_Operator2_out1 = '0' ELSE
      Delay8_out1_im;

  dataOut_re <= std_logic_vector(Switch_out1_re);

  dataOut_im <= std_logic_vector(Switch_out1_im);

  Delay9_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay9_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay9_out1 <= Delay7_out1;
      END IF;
    END IF;
  END PROCESS Delay9_process;


  Logical_Operator5_out1 <= Delay9_out1 AND Unit_Delay_Enabled_Resettable_Synchronous_out1;

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_out1 <= to_unsigned(16#00#, 5);
      ELSIF enb = '1' THEN
        Delay3_out1 <= Unit_Delay_Enabled_Synchronous_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay2_out1 <= Unit_Delay_Enabled_Synchronous1_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  validOut <= Logical_Operator2_out1;

  paramCapture <= Logical_Operator5_out1;

  FECFrameOut <= Delay2_out1;

END rtl;

