-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_Moving_Average.vhd
-- Created: 2025-10-27 18:12:29
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_Moving_Average
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency 
-- and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/Moving Averag
-- Hierarchy Level: 7
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_Moving_Average IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_32_0                        :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(37 DOWNTO 0);  -- sfix38_En22
        dataIn_im                         :   IN    std_logic_vector(37 DOWNTO 0);  -- sfix38_En22
        validIn                           :   IN    std_logic;
        dataOut_re                        :   OUT   std_logic_vector(52 DOWNTO 0);  -- sfix53_En36
        dataOut_im                        :   OUT   std_logic_vector(52 DOWNTO 0);  -- sfix53_En36
        validOut                          :   OUT   std_logic
        );
END dvbs2_ip_src_Moving_Average;


ARCHITECTURE rtl OF dvbs2_ip_src_Moving_Average IS

  -- Signals
  SIGNAL dataIn_re_signed                 : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL dataIn_im_signed                 : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Delay5_out1_re                   : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Delay5_out1_im                   : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Delay_bypass_delay_re            : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Delay_bypass_delay_im            : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Delay_reg_re                     : vector_of_signed38(0 TO 511);  -- sfix38_En22 [512]
  SIGNAL Delay_reg_im                     : vector_of_signed38(0 TO 511);  -- sfix38_En22 [512]
  SIGNAL Delay_out1_re                    : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Delay_out1_im                    : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Delay6_out1_re                   : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Delay6_out1_im                   : signed(37 DOWNTO 0);  -- sfix38_En22
  SIGNAL Add1_sub_cast                    : signed(38 DOWNTO 0);  -- sfix39_En22
  SIGNAL Add1_sub_cast_1                  : signed(38 DOWNTO 0);  -- sfix39_En22
  SIGNAL Add1_sub_cast_2                  : signed(38 DOWNTO 0);  -- sfix39_En22
  SIGNAL Add1_sub_cast_3                  : signed(38 DOWNTO 0);  -- sfix39_En22
  SIGNAL Add1_out1_re                     : signed(38 DOWNTO 0);  -- sfix39_En22
  SIGNAL Add1_out1_im                     : signed(38 DOWNTO 0);  -- sfix39_En22
  SIGNAL Data_Type_Conversion1_out1_re    : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Data_Type_Conversion1_out1_im    : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Delay3_reg_re                    : vector_of_signed53(0 TO 1);  -- sfix53_En36 [2]
  SIGNAL Delay3_reg_im                    : vector_of_signed53(0 TO 1);  -- sfix53_En36 [2]
  SIGNAL Delay3_out1_re                   : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Delay3_out1_im                   : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Gain_cast                        : signed(62 DOWNTO 0);  -- sfix63_En45
  SIGNAL Gain_cast_1                      : signed(61 DOWNTO 0);  -- sfix62_En45
  SIGNAL Gain_cast_2                      : signed(62 DOWNTO 0);  -- sfix63_En45
  SIGNAL Gain_cast_3                      : signed(61 DOWNTO 0);  -- sfix62_En45
  SIGNAL Gain_out1_re                     : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Gain_out1_im                     : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Delay7_out1                      : std_logic;
  SIGNAL Delay2_reg                       : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay2_out1                      : std_logic;
  SIGNAL Add_out1_re                      : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Add_out1_im                      : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Delay1_bypass_delay_re           : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Delay1_bypass_delay_im           : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Delay1_reg_re                    : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Delay1_reg_im                    : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Delay1_out1_re                   : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Delay1_out1_im                   : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Delay4_out1_re                   : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Delay4_out1_im                   : signed(52 DOWNTO 0);  -- sfix53_En36
  SIGNAL Delay8_out1                      : std_logic;

BEGIN
  dataIn_re_signed <= signed(dataIn_re);

  dataIn_im_signed <= signed(dataIn_im);

  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_out1_re <= to_signed(0, 38);
        Delay5_out1_im <= to_signed(0, 38);
      ELSIF enb_1_32_0 = '1' THEN
        Delay5_out1_re <= dataIn_re_signed;
        Delay5_out1_im <= dataIn_im_signed;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_bypass_delay_re <= to_signed(0, 38);
        Delay_bypass_delay_im <= to_signed(0, 38);
        Delay_reg_re <= (OTHERS => to_signed(0, 38));
        Delay_reg_im <= (OTHERS => to_signed(0, 38));
      ELSIF enb_1_32_0 = '1' AND validIn = '1' THEN
        Delay_bypass_delay_im <= Delay_reg_im(511);
        Delay_reg_im(0) <= dataIn_im_signed;
        Delay_reg_im(1 TO 511) <= Delay_reg_im(0 TO 510);
        Delay_bypass_delay_re <= Delay_reg_re(511);
        Delay_reg_re(0) <= dataIn_re_signed;
        Delay_reg_re(1 TO 511) <= Delay_reg_re(0 TO 510);
      END IF;
    END IF;
  END PROCESS Delay_process;

  
  Delay_out1_re <= Delay_reg_re(511) WHEN validIn = '1' ELSE
      Delay_bypass_delay_re;
  
  Delay_out1_im <= Delay_reg_im(511) WHEN validIn = '1' ELSE
      Delay_bypass_delay_im;

  Delay6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay6_out1_re <= to_signed(0, 38);
        Delay6_out1_im <= to_signed(0, 38);
      ELSIF enb_1_32_0 = '1' THEN
        Delay6_out1_re <= Delay_out1_re;
        Delay6_out1_im <= Delay_out1_im;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  Add1_sub_cast <= resize(Delay5_out1_re, 39);
  Add1_sub_cast_1 <= resize(Delay6_out1_re, 39);
  Add1_out1_re <= Add1_sub_cast - Add1_sub_cast_1;
  Add1_sub_cast_2 <= resize(Delay5_out1_im, 39);
  Add1_sub_cast_3 <= resize(Delay6_out1_im, 39);
  Add1_out1_im <= Add1_sub_cast_2 - Add1_sub_cast_3;

  Data_Type_Conversion1_out1_re <= Add1_out1_re & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  Data_Type_Conversion1_out1_im <= Add1_out1_im & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_reg_re <= (OTHERS => to_signed(0, 53));
        Delay3_reg_im <= (OTHERS => to_signed(0, 53));
      ELSIF enb_1_32_0 = '1' THEN
        Delay3_reg_im(0) <= Data_Type_Conversion1_out1_im;
        Delay3_reg_im(1) <= Delay3_reg_im(0);
        Delay3_reg_re(0) <= Data_Type_Conversion1_out1_re;
        Delay3_reg_re(1) <= Delay3_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay3_process;

  Delay3_out1_re <= Delay3_reg_re(1);
  Delay3_out1_im <= Delay3_reg_im(1);

  Gain_cast <= resize(Delay3_out1_re, 63);
  Gain_cast_1 <= Gain_cast(61 DOWNTO 0);
  Gain_out1_re <= Gain_cast_1(61 DOWNTO 9);
  Gain_cast_2 <= resize(Delay3_out1_im, 63);
  Gain_cast_3 <= Gain_cast_2(61 DOWNTO 0);
  Gain_out1_im <= Gain_cast_3(61 DOWNTO 9);

  Delay7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay7_out1 <= '0';
      ELSIF enb_1_32_0 = '1' THEN
        Delay7_out1 <= validIn;
      END IF;
    END IF;
  END PROCESS Delay7_process;


  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_reg <= (OTHERS => '0');
      ELSIF enb_1_32_0 = '1' THEN
        Delay2_reg(0) <= Delay7_out1;
        Delay2_reg(1) <= Delay2_reg(0);
      END IF;
    END IF;
  END PROCESS Delay2_process;

  Delay2_out1 <= Delay2_reg(1);

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_bypass_delay_re <= to_signed(0, 53);
        Delay1_bypass_delay_im <= to_signed(0, 53);
        Delay1_reg_re <= to_signed(0, 53);
        Delay1_reg_im <= to_signed(0, 53);
      ELSIF enb_1_32_0 = '1' AND Delay2_out1 = '1' THEN
        Delay1_bypass_delay_im <= Delay1_reg_im;
        Delay1_reg_im <= Add_out1_im;
        Delay1_bypass_delay_re <= Delay1_reg_re;
        Delay1_reg_re <= Add_out1_re;
      END IF;
    END IF;
  END PROCESS Delay1_process;

  
  Delay1_out1_re <= Delay1_reg_re WHEN Delay2_out1 = '1' ELSE
      Delay1_bypass_delay_re;
  
  Delay1_out1_im <= Delay1_reg_im WHEN Delay2_out1 = '1' ELSE
      Delay1_bypass_delay_im;

  Add_out1_re <= Gain_out1_re + Delay1_out1_re;
  Add_out1_im <= Gain_out1_im + Delay1_out1_im;

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_out1_re <= to_signed(0, 53);
        Delay4_out1_im <= to_signed(0, 53);
      ELSIF enb_1_32_0 = '1' THEN
        Delay4_out1_re <= Add_out1_re;
        Delay4_out1_im <= Add_out1_im;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  dataOut_re <= std_logic_vector(Delay4_out1_re);

  dataOut_im <= std_logic_vector(Delay4_out1_im);

  Delay8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay8_out1 <= '0';
      ELSIF enb_1_32_0 = '1' THEN
        Delay8_out1 <= Delay2_out1;
      END IF;
    END IF;
  END PROCESS Delay8_process;


  validOut <= Delay8_out1;

END rtl;

