-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_subFilter_block8.vhd
-- Created: 2025-10-27 18:12:30
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_subFilter_block8
-- Source Path: soc_dvbs2_fpga/DVBS2/Vector Interpolation/FIR Interpolator/FIRFilter2/Filter/subFilter
-- Hierarchy Level: 5
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_subFilter_block8 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
        coefIn                            :   IN    vector_of_std_logic_vector16(0 TO 31);  -- sfix16_En15 [32]
        dinRegVld                         :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        dout_1_re                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16
        );
END dvbs2_ip_src_subFilter_block8;


ARCHITECTURE rtl OF dvbs2_ip_src_subFilter_block8 IS

  -- Component Declarations
  COMPONENT dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16
          coefIn_0                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          addin                           :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48_En15
          dinRegVld                       :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dinDly2                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16
          tapout                          :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En15
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    USE ENTITY work.dvbs2_ip_src_FilterTapSystolicWvldin_block4(rtl);

  -- Signals
  SIGNAL intdelay_reg                     : std_logic_vector(34 DOWNTO 0);  -- ufix1 [35]
  SIGNAL vldShift                         : std_logic;
  SIGNAL vldOutTmp                        : std_logic;
  SIGNAL addin                            : signed(47 DOWNTO 0);  -- sfix48_En15
  SIGNAL dinDly2                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout                           : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_1                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_1                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_2                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_2                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_3                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_3                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_4                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_4                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_5                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_5                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_6                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_6                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_7                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_7                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_8                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_8                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_9                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_9                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_10                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_10                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_11                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_11                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_12                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_12                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_13                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_13                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_14                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_14                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_15                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_15                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_16                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_16                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_17                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_17                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_18                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_18                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_19                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_19                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_20                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_20                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_21                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_21                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_22                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_22                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_23                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_23                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_24                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_24                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_25                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_25                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_26                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_26                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_27                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_27                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_28                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_28                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_29                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_29                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_30                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_30                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL ZERO_OUT                         : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL dinDly2deadOut                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_31                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_signed                    : signed(47 DOWNTO 0);  -- sfix48_En15
  SIGNAL dout_cast                        : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL muxOut                           : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL dout_1_re_tmp                    : signed(15 DOWNTO 0);  -- sfix16

BEGIN
  u_FilterTap_1 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix16
              coefIn_0 => coefIn(0),  -- sfix16_En15
              addin => std_logic_vector(addin),  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2,  -- sfix16
              tapout => tapout  -- sfix48_En15
              );

  u_FilterTap_2 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2,  -- sfix16
              coefIn_0 => coefIn(1),  -- sfix16_En15
              addin => tapout,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_1,  -- sfix16
              tapout => tapout_1  -- sfix48_En15
              );

  u_FilterTap_3 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_1,  -- sfix16
              coefIn_0 => coefIn(2),  -- sfix16_En15
              addin => tapout_1,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_2,  -- sfix16
              tapout => tapout_2  -- sfix48_En15
              );

  u_FilterTap_4 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_2,  -- sfix16
              coefIn_0 => coefIn(3),  -- sfix16_En15
              addin => tapout_2,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_3,  -- sfix16
              tapout => tapout_3  -- sfix48_En15
              );

  u_FilterTap_5 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_3,  -- sfix16
              coefIn_0 => coefIn(4),  -- sfix16_En15
              addin => tapout_3,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_4,  -- sfix16
              tapout => tapout_4  -- sfix48_En15
              );

  u_FilterTap_6 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_4,  -- sfix16
              coefIn_0 => coefIn(5),  -- sfix16_En15
              addin => tapout_4,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_5,  -- sfix16
              tapout => tapout_5  -- sfix48_En15
              );

  u_FilterTap_7 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_5,  -- sfix16
              coefIn_0 => coefIn(6),  -- sfix16_En15
              addin => tapout_5,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_6,  -- sfix16
              tapout => tapout_6  -- sfix48_En15
              );

  u_FilterTap_8 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_6,  -- sfix16
              coefIn_0 => coefIn(7),  -- sfix16_En15
              addin => tapout_6,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_7,  -- sfix16
              tapout => tapout_7  -- sfix48_En15
              );

  u_FilterTap_9 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_7,  -- sfix16
              coefIn_0 => coefIn(8),  -- sfix16_En15
              addin => tapout_7,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_8,  -- sfix16
              tapout => tapout_8  -- sfix48_En15
              );

  u_FilterTap_10 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_8,  -- sfix16
              coefIn_0 => coefIn(9),  -- sfix16_En15
              addin => tapout_8,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_9,  -- sfix16
              tapout => tapout_9  -- sfix48_En15
              );

  u_FilterTap_11 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_9,  -- sfix16
              coefIn_0 => coefIn(10),  -- sfix16_En15
              addin => tapout_9,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_10,  -- sfix16
              tapout => tapout_10  -- sfix48_En15
              );

  u_FilterTap_12 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_10,  -- sfix16
              coefIn_0 => coefIn(11),  -- sfix16_En15
              addin => tapout_10,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_11,  -- sfix16
              tapout => tapout_11  -- sfix48_En15
              );

  u_FilterTap_13 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_11,  -- sfix16
              coefIn_0 => coefIn(12),  -- sfix16_En15
              addin => tapout_11,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_12,  -- sfix16
              tapout => tapout_12  -- sfix48_En15
              );

  u_FilterTap_14 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_12,  -- sfix16
              coefIn_0 => coefIn(13),  -- sfix16_En15
              addin => tapout_12,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_13,  -- sfix16
              tapout => tapout_13  -- sfix48_En15
              );

  u_FilterTap_15 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_13,  -- sfix16
              coefIn_0 => coefIn(14),  -- sfix16_En15
              addin => tapout_13,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_14,  -- sfix16
              tapout => tapout_14  -- sfix48_En15
              );

  u_FilterTap_16 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_14,  -- sfix16
              coefIn_0 => coefIn(15),  -- sfix16_En15
              addin => tapout_14,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_15,  -- sfix16
              tapout => tapout_15  -- sfix48_En15
              );

  u_FilterTap_17 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_15,  -- sfix16
              coefIn_0 => coefIn(16),  -- sfix16_En15
              addin => tapout_15,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_16,  -- sfix16
              tapout => tapout_16  -- sfix48_En15
              );

  u_FilterTap_18 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_16,  -- sfix16
              coefIn_0 => coefIn(17),  -- sfix16_En15
              addin => tapout_16,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_17,  -- sfix16
              tapout => tapout_17  -- sfix48_En15
              );

  u_FilterTap_19 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_17,  -- sfix16
              coefIn_0 => coefIn(18),  -- sfix16_En15
              addin => tapout_17,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_18,  -- sfix16
              tapout => tapout_18  -- sfix48_En15
              );

  u_FilterTap_20 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_18,  -- sfix16
              coefIn_0 => coefIn(19),  -- sfix16_En15
              addin => tapout_18,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_19,  -- sfix16
              tapout => tapout_19  -- sfix48_En15
              );

  u_FilterTap_21 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_19,  -- sfix16
              coefIn_0 => coefIn(20),  -- sfix16_En15
              addin => tapout_19,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_20,  -- sfix16
              tapout => tapout_20  -- sfix48_En15
              );

  u_FilterTap_22 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_20,  -- sfix16
              coefIn_0 => coefIn(21),  -- sfix16_En15
              addin => tapout_20,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_21,  -- sfix16
              tapout => tapout_21  -- sfix48_En15
              );

  u_FilterTap_23 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_21,  -- sfix16
              coefIn_0 => coefIn(22),  -- sfix16_En15
              addin => tapout_21,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_22,  -- sfix16
              tapout => tapout_22  -- sfix48_En15
              );

  u_FilterTap_24 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_22,  -- sfix16
              coefIn_0 => coefIn(23),  -- sfix16_En15
              addin => tapout_22,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_23,  -- sfix16
              tapout => tapout_23  -- sfix48_En15
              );

  u_FilterTap_25 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_23,  -- sfix16
              coefIn_0 => coefIn(24),  -- sfix16_En15
              addin => tapout_23,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_24,  -- sfix16
              tapout => tapout_24  -- sfix48_En15
              );

  u_FilterTap_26 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_24,  -- sfix16
              coefIn_0 => coefIn(25),  -- sfix16_En15
              addin => tapout_24,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_25,  -- sfix16
              tapout => tapout_25  -- sfix48_En15
              );

  u_FilterTap_27 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_25,  -- sfix16
              coefIn_0 => coefIn(26),  -- sfix16_En15
              addin => tapout_25,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_26,  -- sfix16
              tapout => tapout_26  -- sfix48_En15
              );

  u_FilterTap_28 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_26,  -- sfix16
              coefIn_0 => coefIn(27),  -- sfix16_En15
              addin => tapout_26,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_27,  -- sfix16
              tapout => tapout_27  -- sfix48_En15
              );

  u_FilterTap_29 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_27,  -- sfix16
              coefIn_0 => coefIn(28),  -- sfix16_En15
              addin => tapout_27,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_28,  -- sfix16
              tapout => tapout_28  -- sfix48_En15
              );

  u_FilterTap_30 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_28,  -- sfix16
              coefIn_0 => coefIn(29),  -- sfix16_En15
              addin => tapout_28,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_29,  -- sfix16
              tapout => tapout_29  -- sfix48_En15
              );

  u_FilterTap_31 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_29,  -- sfix16
              coefIn_0 => coefIn(30),  -- sfix16_En15
              addin => tapout_29,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_30,  -- sfix16
              tapout => tapout_30  -- sfix48_En15
              );

  u_FilterTap_32 : dvbs2_ip_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_30,  -- sfix16
              coefIn_0 => coefIn(31),  -- sfix16_En15
              addin => tapout_30,  -- sfix48_En15
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2deadOut,  -- sfix16
              tapout => tapout_31  -- sfix48_En15
              );

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        intdelay_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          intdelay_reg <= (OTHERS => '0');
        ELSIF dinRegVld = '1' THEN
          intdelay_reg(0) <= dinRegVld;
          intdelay_reg(34 DOWNTO 1) <= intdelay_reg(33 DOWNTO 0);
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;

  vldShift <= intdelay_reg(34);

  vldOutTmp <= dinRegVld AND vldShift;

  addin <= to_signed(0, 48);

  ZERO_OUT <= to_signed(16#0000#, 16);

  tapout_signed <= signed(tapout_31);

  dout_cast <= tapout_signed(30 DOWNTO 15);

  
  muxOut <= ZERO_OUT WHEN vldOutTmp = '0' ELSE
      dout_cast;

  intdelay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dout_1_re_tmp <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dout_1_re_tmp <= to_signed(16#0000#, 16);
        ELSE 
          dout_1_re_tmp <= muxOut;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  dout_1_re <= std_logic_vector(dout_1_re_tmp);

END rtl;

