-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_Synchronizer_and_PL_Header_Decoder.vhd
-- Created: 2025-10-27 18:12:30
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_Synchronizer_and_PL_Header_Decoder
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder
-- Hierarchy Level: 3
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_Synchronizer_and_PL_Header_Decoder IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_8_1                         :   IN    std_logic;
        enb_1_32_0                        :   IN    std_logic;
        enb_1_32_1                        :   IN    std_logic;
        enb_1_8_0                         :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        dataIn_im                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        validIn                           :   IN    std_logic;
        rstFCPO                           :   IN    std_logic;
        dataOut_re                        :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
        dataOut_im                        :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
        validOut                          :   OUT   std_logic;
        endOfPLSC                         :   OUT   std_logic;
        headerInfo_MODCOD                 :   OUT   std_logic_vector(4 DOWNTO 0);  -- ufix5
        headerInfo_FECFrame               :   OUT   std_logic;  -- ufix1
        diagBus_NormalizedFrequencyEstimates_NormalizedFineFrequencyEstimate :   OUT   std_logic_vector(20 DOWNTO 0)  -- sfix21_En21
        );
END dvbs2_ip_src_Synchronizer_and_PL_Header_Decoder;


ARCHITECTURE rtl OF dvbs2_ip_src_Synchronizer_and_PL_Header_Decoder IS

  -- Component Declarations
  COMPONENT dvbs2_ip_src_Time_Frequency_and_Coarse_Phase_Synchronizer
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_8_1                       :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          enb_1_32_1                      :   IN    std_logic;
          enb_1_8_0                       :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          dataIn_im                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          validIn                         :   IN    std_logic;
          finePhaseEn                     :   OUT   std_logic;
          dataOut_re                      :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
          dataOut_im                      :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
          validOut                        :   OUT   std_logic;
          endOfSOF                        :   OUT   std_logic;
          hasPilots                       :   OUT   std_logic;
          normFineFreqEst                 :   OUT   std_logic_vector(20 DOWNTO 0);  -- sfix21_En21
          enbMODCOD                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_PL_Header_Recovery
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
          dataIn_im                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
          validIn                         :   IN    std_logic;
          endOfSOF                        :   IN    std_logic;
          hasPilots                       :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
          dataOut_im                      :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
          validOut                        :   OUT   std_logic;
          endOfPLSC                       :   OUT   std_logic;
          modcod                          :   OUT   std_logic_vector(4 DOWNTO 0);  -- ufix5
          FEC                             :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_Source_Encoding
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          modcod                          :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
          mod_rsvd                        :   OUT   std_logic_vector(1 DOWNTO 0)  -- ufix2
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_Fine_Phase_Synchronizer
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
          dataIn_im                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
          validIn                         :   IN    std_logic;
          endOfPLSCIn                     :   IN    std_logic;
          mod_rsvd                        :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          En                              :   IN    std_logic;
          rst                             :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
          dataOut_im                      :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
          validOut                        :   OUT   std_logic;
          endOfPLSC                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_Enable_MODCOD
    PORT( modcod                          :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
          enb_1                           :   IN    std_logic;
          modcodOut                       :   OUT   std_logic_vector(4 DOWNTO 0)  -- ufix5
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dvbs2_ip_src_Time_Frequency_and_Coarse_Phase_Synchronizer
    USE ENTITY work.dvbs2_ip_src_Time_Frequency_and_Coarse_Phase_Synchronizer(rtl);

  FOR ALL : dvbs2_ip_src_PL_Header_Recovery
    USE ENTITY work.dvbs2_ip_src_PL_Header_Recovery(rtl);

  FOR ALL : dvbs2_ip_src_Source_Encoding
    USE ENTITY work.dvbs2_ip_src_Source_Encoding(rtl);

  FOR ALL : dvbs2_ip_src_Fine_Phase_Synchronizer
    USE ENTITY work.dvbs2_ip_src_Fine_Phase_Synchronizer(rtl);

  FOR ALL : dvbs2_ip_src_Enable_MODCOD
    USE ENTITY work.dvbs2_ip_src_Enable_MODCOD(rtl);

  -- Signals
  SIGNAL dataIn_re_signed                 : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL dataIn_im_signed                 : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay20_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay20_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay3_out1                      : std_logic;
  SIGNAL Time_Frequency_and_Coarse_Phase_Synchronizer_finePhaseEn : std_logic;
  SIGNAL Time_Frequency_and_Coarse_Phase_Synchronizer_dataOut_re : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL Time_Frequency_and_Coarse_Phase_Synchronizer_dataOut_im : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL Time_Frequency_and_Coarse_Phase_Synchronizer_validOut : std_logic;
  SIGNAL Time_Frequency_and_Coarse_Phase_Synchronizer_endOfSOF : std_logic;
  SIGNAL Time_Frequency_and_Coarse_Phase_Synchronizer_hasPilots : std_logic;
  SIGNAL NormalizedFineFrequencyEstimate  : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL Time_Frequency_and_Coarse_Phase_Synchronizer_enbMODCOD : std_logic;
  SIGNAL Time_Frequency_and_Coarse_Phase_Synchronizer_dataOut_re_signed : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Time_Frequency_and_Coarse_Phase_Synchronizer_dataOut_im_signed : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay13_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay13_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay14_out1                     : std_logic;
  SIGNAL Delay15_out1                     : std_logic;
  SIGNAL Delay16_out1                     : std_logic;
  SIGNAL PL_Header_Recovery_dataOut_re    : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL PL_Header_Recovery_dataOut_im    : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL PL_Header_Recovery_validOut      : std_logic;
  SIGNAL PL_Header_Recovery_endOfPLSC     : std_logic;
  SIGNAL PL_Header_Recovery_modcod        : std_logic_vector(4 DOWNTO 0);  -- ufix5
  SIGNAL PL_Header_Recovery_FEC           : std_logic;  -- ufix1
  SIGNAL PL_Header_Recovery_dataOut_re_signed : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL PL_Header_Recovery_dataOut_im_signed : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay12_reg_re                   : vector_of_signed18(0 TO 1);  -- sfix18_En13 [2]
  SIGNAL Delay12_reg_im                   : vector_of_signed18(0 TO 1);  -- sfix18_En13 [2]
  SIGNAL Delay12_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay12_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay4_reg                       : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay4_out1                      : std_logic;
  SIGNAL Delay5_reg                       : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay5_out1                      : std_logic;
  SIGNAL Source_Encoding_mod              : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL Delay24_out1                     : std_logic;
  SIGNAL Downsample_bypass_reg            : std_logic;  -- ufix1
  SIGNAL Downsample_out1                  : std_logic;
  SIGNAL Fine_Phase_Synchronizer_dataOut_re : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL Fine_Phase_Synchronizer_dataOut_im : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL Fine_Phase_Synchronizer_validOut : std_logic;
  SIGNAL Fine_Phase_Synchronizer_endOfPLSC : std_logic;
  SIGNAL Fine_Phase_Synchronizer_dataOut_re_signed : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Fine_Phase_Synchronizer_dataOut_im_signed : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Delay17_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Delay17_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Delay18_out1                     : std_logic;
  SIGNAL Delay19_out1                     : std_logic;
  SIGNAL PL_Header_Recovery_modcod_unsigned : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Delay6_reg                       : vector_of_unsigned5(0 TO 1);  -- ufix5 [2]
  SIGNAL Delay6_out1                      : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Delay9_reg                       : vector_of_unsigned5(0 TO 5);  -- ufix5 [6]
  SIGNAL Delay9_out1                      : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL MODCOD                           : std_logic_vector(4 DOWNTO 0);  -- ufix5
  SIGNAL MODCOD_unsigned                  : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL MODCOD_1                         : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Delay7_reg                       : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay7_out1                      : std_logic;  -- ufix1
  SIGNAL Delay10_reg                      : std_logic_vector(5 DOWNTO 0);  -- ufix1 [6]
  SIGNAL FECFrame                         : std_logic;  -- ufix1
  SIGNAL FECFrame_1                       : std_logic;  -- ufix1
  SIGNAL NormalizedFineFrequencyEstimate_signed : signed(20 DOWNTO 0);  -- sfix21_En21
  SIGNAL NormalizedFineFrequencyEstimate_1 : signed(20 DOWNTO 0);  -- sfix21_En21

BEGIN
  u_Time_Frequency_and_Coarse_Phase_Synchronizer : dvbs2_ip_src_Time_Frequency_and_Coarse_Phase_Synchronizer
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_8_1 => enb_1_8_1,
              enb_1_32_0 => enb_1_32_0,
              enb_1_32_1 => enb_1_32_1,
              enb_1_8_0 => enb_1_8_0,
              dataIn_re => std_logic_vector(Delay20_out1_re),  -- sfix18_En15
              dataIn_im => std_logic_vector(Delay20_out1_im),  -- sfix18_En15
              validIn => Delay3_out1,
              finePhaseEn => Time_Frequency_and_Coarse_Phase_Synchronizer_finePhaseEn,
              dataOut_re => Time_Frequency_and_Coarse_Phase_Synchronizer_dataOut_re,  -- sfix18_En13
              dataOut_im => Time_Frequency_and_Coarse_Phase_Synchronizer_dataOut_im,  -- sfix18_En13
              validOut => Time_Frequency_and_Coarse_Phase_Synchronizer_validOut,
              endOfSOF => Time_Frequency_and_Coarse_Phase_Synchronizer_endOfSOF,
              hasPilots => Time_Frequency_and_Coarse_Phase_Synchronizer_hasPilots,
              normFineFreqEst => NormalizedFineFrequencyEstimate,  -- sfix21_En21
              enbMODCOD => Time_Frequency_and_Coarse_Phase_Synchronizer_enbMODCOD
              );

  u_PL_Header_Recovery : dvbs2_ip_src_PL_Header_Recovery
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              dataIn_re => std_logic_vector(Delay13_out1_re),  -- sfix18_En13
              dataIn_im => std_logic_vector(Delay13_out1_im),  -- sfix18_En13
              validIn => Delay14_out1,
              endOfSOF => Delay15_out1,
              hasPilots => Delay16_out1,
              dataOut_re => PL_Header_Recovery_dataOut_re,  -- sfix18_En13
              dataOut_im => PL_Header_Recovery_dataOut_im,  -- sfix18_En13
              validOut => PL_Header_Recovery_validOut,
              endOfPLSC => PL_Header_Recovery_endOfPLSC,
              modcod => PL_Header_Recovery_modcod,  -- ufix5
              FEC => PL_Header_Recovery_FEC  -- ufix1
              );

  u_Source_Encoding : dvbs2_ip_src_Source_Encoding
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              modcod => PL_Header_Recovery_modcod,  -- ufix5
              mod_rsvd => Source_Encoding_mod  -- ufix2
              );

  u_Fine_Phase_Synchronizer : dvbs2_ip_src_Fine_Phase_Synchronizer
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              dataIn_re => std_logic_vector(Delay12_out1_re),  -- sfix18_En13
              dataIn_im => std_logic_vector(Delay12_out1_im),  -- sfix18_En13
              validIn => Delay4_out1,
              endOfPLSCIn => Delay5_out1,
              mod_rsvd => Source_Encoding_mod,  -- ufix2
              En => Time_Frequency_and_Coarse_Phase_Synchronizer_finePhaseEn,
              rst => Downsample_out1,
              dataOut_re => Fine_Phase_Synchronizer_dataOut_re,  -- sfix18_En14
              dataOut_im => Fine_Phase_Synchronizer_dataOut_im,  -- sfix18_En14
              validOut => Fine_Phase_Synchronizer_validOut,
              endOfPLSC => Fine_Phase_Synchronizer_endOfPLSC
              );

  u_Enable_MODCOD : dvbs2_ip_src_Enable_MODCOD
    PORT MAP( modcod => std_logic_vector(Delay9_out1),  -- ufix5
              enb_1 => Time_Frequency_and_Coarse_Phase_Synchronizer_enbMODCOD,
              modcodOut => MODCOD  -- ufix5
              );

  dataIn_re_signed <= signed(dataIn_re);

  dataIn_im_signed <= signed(dataIn_im);

  Delay20_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay20_out1_re <= to_signed(16#00000#, 18);
        Delay20_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_8_0 = '1' THEN
        Delay20_out1_re <= dataIn_re_signed;
        Delay20_out1_im <= dataIn_im_signed;
      END IF;
    END IF;
  END PROCESS Delay20_process;


  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_out1 <= '0';
      ELSIF enb_1_8_0 = '1' THEN
        Delay3_out1 <= validIn;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  Time_Frequency_and_Coarse_Phase_Synchronizer_dataOut_re_signed <= signed(Time_Frequency_and_Coarse_Phase_Synchronizer_dataOut_re);

  Time_Frequency_and_Coarse_Phase_Synchronizer_dataOut_im_signed <= signed(Time_Frequency_and_Coarse_Phase_Synchronizer_dataOut_im);

  Delay13_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay13_out1_re <= to_signed(16#00000#, 18);
        Delay13_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_32_0 = '1' THEN
        Delay13_out1_re <= Time_Frequency_and_Coarse_Phase_Synchronizer_dataOut_re_signed;
        Delay13_out1_im <= Time_Frequency_and_Coarse_Phase_Synchronizer_dataOut_im_signed;
      END IF;
    END IF;
  END PROCESS Delay13_process;


  Delay14_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay14_out1 <= '0';
      ELSIF enb_1_32_0 = '1' THEN
        Delay14_out1 <= Time_Frequency_and_Coarse_Phase_Synchronizer_validOut;
      END IF;
    END IF;
  END PROCESS Delay14_process;


  Delay15_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay15_out1 <= '0';
      ELSIF enb_1_32_0 = '1' THEN
        Delay15_out1 <= Time_Frequency_and_Coarse_Phase_Synchronizer_endOfSOF;
      END IF;
    END IF;
  END PROCESS Delay15_process;


  Delay16_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay16_out1 <= '0';
      ELSIF enb_1_32_0 = '1' THEN
        Delay16_out1 <= Time_Frequency_and_Coarse_Phase_Synchronizer_hasPilots;
      END IF;
    END IF;
  END PROCESS Delay16_process;


  PL_Header_Recovery_dataOut_re_signed <= signed(PL_Header_Recovery_dataOut_re);

  PL_Header_Recovery_dataOut_im_signed <= signed(PL_Header_Recovery_dataOut_im);

  Delay12_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay12_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay12_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_32_0 = '1' THEN
        Delay12_reg_im(0) <= PL_Header_Recovery_dataOut_im_signed;
        Delay12_reg_im(1) <= Delay12_reg_im(0);
        Delay12_reg_re(0) <= PL_Header_Recovery_dataOut_re_signed;
        Delay12_reg_re(1) <= Delay12_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay12_process;

  Delay12_out1_re <= Delay12_reg_re(1);
  Delay12_out1_im <= Delay12_reg_im(1);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_reg <= (OTHERS => '0');
      ELSIF enb_1_32_0 = '1' THEN
        Delay4_reg(0) <= PL_Header_Recovery_validOut;
        Delay4_reg(1) <= Delay4_reg(0);
      END IF;
    END IF;
  END PROCESS Delay4_process;

  Delay4_out1 <= Delay4_reg(1);

  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_reg <= (OTHERS => '0');
      ELSIF enb_1_32_0 = '1' THEN
        Delay5_reg(0) <= PL_Header_Recovery_endOfPLSC;
        Delay5_reg(1) <= Delay5_reg(0);
      END IF;
    END IF;
  END PROCESS Delay5_process;

  Delay5_out1 <= Delay5_reg(1);

  Delay24_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay24_out1 <= '0';
      ELSIF enb_1_8_0 = '1' THEN
        Delay24_out1 <= rstFCPO;
      END IF;
    END IF;
  END PROCESS Delay24_process;


  -- Downsample: Downsample by 4, Sample offset 0 
  -- Downsample bypass register
  Downsample_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Downsample_bypass_reg <= '0';
      ELSIF enb_1_32_1 = '1' THEN
        Downsample_bypass_reg <= Delay24_out1;
      END IF;
    END IF;
  END PROCESS Downsample_bypass_process;

  
  Downsample_out1 <= Delay24_out1 WHEN enb_1_32_1 = '1' ELSE
      Downsample_bypass_reg;

  Fine_Phase_Synchronizer_dataOut_re_signed <= signed(Fine_Phase_Synchronizer_dataOut_re);

  Fine_Phase_Synchronizer_dataOut_im_signed <= signed(Fine_Phase_Synchronizer_dataOut_im);

  Delay17_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay17_out1_re <= to_signed(16#00000#, 18);
        Delay17_out1_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_32_0 = '1' THEN
        Delay17_out1_re <= Fine_Phase_Synchronizer_dataOut_re_signed;
        Delay17_out1_im <= Fine_Phase_Synchronizer_dataOut_im_signed;
      END IF;
    END IF;
  END PROCESS Delay17_process;


  dataOut_re <= std_logic_vector(Delay17_out1_re);

  dataOut_im <= std_logic_vector(Delay17_out1_im);

  Delay18_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay18_out1 <= '0';
      ELSIF enb_1_32_0 = '1' THEN
        Delay18_out1 <= Fine_Phase_Synchronizer_validOut;
      END IF;
    END IF;
  END PROCESS Delay18_process;


  Delay19_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay19_out1 <= '0';
      ELSIF enb_1_32_0 = '1' THEN
        Delay19_out1 <= Fine_Phase_Synchronizer_endOfPLSC;
      END IF;
    END IF;
  END PROCESS Delay19_process;


  PL_Header_Recovery_modcod_unsigned <= unsigned(PL_Header_Recovery_modcod);

  Delay6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay6_reg <= (OTHERS => to_unsigned(16#00#, 5));
      ELSIF enb_1_32_0 = '1' THEN
        Delay6_reg(0) <= PL_Header_Recovery_modcod_unsigned;
        Delay6_reg(1) <= Delay6_reg(0);
      END IF;
    END IF;
  END PROCESS Delay6_process;

  Delay6_out1 <= Delay6_reg(1);

  Delay9_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay9_reg <= (OTHERS => to_unsigned(16#00#, 5));
      ELSIF enb_1_32_0 = '1' THEN
        Delay9_reg(0) <= Delay6_out1;
        Delay9_reg(1 TO 5) <= Delay9_reg(0 TO 4);
      END IF;
    END IF;
  END PROCESS Delay9_process;

  Delay9_out1 <= Delay9_reg(5);

  MODCOD_unsigned <= unsigned(MODCOD);

  Delay21_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        MODCOD_1 <= to_unsigned(16#00#, 5);
      ELSIF enb_1_32_0 = '1' THEN
        MODCOD_1 <= MODCOD_unsigned;
      END IF;
    END IF;
  END PROCESS Delay21_1_process;


  headerInfo_MODCOD <= std_logic_vector(MODCOD_1);

  Delay7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay7_reg <= (OTHERS => '0');
      ELSIF enb_1_32_0 = '1' THEN
        Delay7_reg(0) <= PL_Header_Recovery_FEC;
        Delay7_reg(1) <= Delay7_reg(0);
      END IF;
    END IF;
  END PROCESS Delay7_process;

  Delay7_out1 <= Delay7_reg(1);

  Delay10_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay10_reg <= (OTHERS => '0');
      ELSIF enb_1_32_0 = '1' THEN
        Delay10_reg(0) <= Delay7_out1;
        Delay10_reg(5 DOWNTO 1) <= Delay10_reg(4 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay10_process;

  FECFrame <= Delay10_reg(5);

  Delay21_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        FECFrame_1 <= '0';
      ELSIF enb_1_32_0 = '1' THEN
        FECFrame_1 <= FECFrame;
      END IF;
    END IF;
  END PROCESS Delay21_2_process;


  NormalizedFineFrequencyEstimate_signed <= signed(NormalizedFineFrequencyEstimate);

  Delay11_4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        NormalizedFineFrequencyEstimate_1 <= to_signed(16#000000#, 21);
      ELSIF enb_1_32_0 = '1' THEN
        NormalizedFineFrequencyEstimate_1 <= NormalizedFineFrequencyEstimate_signed;
      END IF;
    END IF;
  END PROCESS Delay11_4_process;


  diagBus_NormalizedFrequencyEstimates_NormalizedFineFrequencyEstimate <= std_logic_vector(NormalizedFineFrequencyEstimate_1);

  validOut <= Delay18_out1;

  endOfPLSC <= Delay19_out1;

  headerInfo_FECFrame <= FECFrame_1;

END rtl;

