-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_Y_PN_Generator_M_0.vhd
-- Created: 2025-10-27 18:12:30
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_Y_PN_Generator_M_0
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency 
-- and Coarse Phase Synchronizer/Time and Coarse Frequency Synchronizer/PL Data Descrambler and Pilot Valid Indicator/PL 
-- Data Descrambler/PL Scrambler Gold Sequence Generator/Subsystem/Y PN Generator M_
-- Hierarchy Level: 10
-- Model version: 9.0
-- 
-- PN Sequence Generator
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_Y_PN_Generator_M_0 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_32_0                        :   IN    std_logic;
        inportReset                       :   IN    std_logic;
        PN_Sequence                       :   OUT   std_logic
        );
END dvbs2_ip_src_Y_PN_Generator_M_0;


ARCHITECTURE rtl OF dvbs2_ip_src_Y_PN_Generator_M_0 IS

  -- Constants
  CONSTANT selShift_data                  : vector_of_signed8(0 TO 3) := 
    (to_signed(16#08#, 8), to_signed(16#0B#, 8), to_signed(16#0D#, 8), to_signed(16#12#, 8));  -- int8 [4]
  CONSTANT c_OutputMask_data              : std_logic_vector(17 DOWNTO 0) := 
    ('1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');  -- ufix1 [18]

  -- Signals
  SIGNAL InitStates                       : std_logic_vector(17 DOWNTO 0);  -- boolean [18]
  SIGNAL TDL                              : std_logic_vector(17 DOWNTO 0);  -- boolean [18]
  SIGNAL ShiftTerms                       : std_logic_vector(16 DOWNTO 0);  -- boolean [17]
  SIGNAL PolyTerms                        : std_logic_vector(3 DOWNTO 0);  -- boolean [4]
  SIGNAL PolyTerms_3                      : std_logic;
  SIGNAL PolyTerms_2                      : std_logic;
  SIGNAL PolyTerms_1                      : std_logic;
  SIGNAL PolyTerms_0                      : std_logic;
  SIGNAL PNSeqOut                         : std_logic;
  SIGNAL TDL_1                            : std_logic_vector(17 DOWNTO 0);  -- boolean [18]
  SIGNAL TDLPrevious                      : std_logic_vector(17 DOWNTO 0);  -- boolean [18]
  SIGNAL OutputMask                       : std_logic_vector(17 DOWNTO 0);  -- boolean [18]
  SIGNAL MaskANDtoXOR                     : std_logic_vector(17 DOWNTO 0);  -- boolean [18]
  SIGNAL MaskANDtoXOR_0                   : std_logic;
  SIGNAL MaskANDtoXOR_1                   : std_logic;
  SIGNAL MaskANDtoXOR_2                   : std_logic;
  SIGNAL MaskANDtoXOR_3                   : std_logic;
  SIGNAL MaskANDtoXOR_4                   : std_logic;
  SIGNAL MaskANDtoXOR_5                   : std_logic;
  SIGNAL MaskANDtoXOR_6                   : std_logic;
  SIGNAL MaskANDtoXOR_7                   : std_logic;
  SIGNAL MaskANDtoXOR_8                   : std_logic;
  SIGNAL MaskANDtoXOR_9                   : std_logic;
  SIGNAL MaskANDtoXOR_10                  : std_logic;
  SIGNAL MaskANDtoXOR_11                  : std_logic;
  SIGNAL MaskANDtoXOR_12                  : std_logic;
  SIGNAL MaskANDtoXOR_13                  : std_logic;
  SIGNAL MaskANDtoXOR_14                  : std_logic;
  SIGNAL MaskANDtoXOR_15                  : std_logic;
  SIGNAL MaskANDtoXOR_16                  : std_logic;
  SIGNAL MaskANDtoXOR_17                  : std_logic;
  SIGNAL PNSeqBits                        : std_logic;
  SIGNAL PNUfix                           : std_logic;  -- ufix1

BEGIN
  InitStates <= (OTHERS => '1');

  ShiftTerms(16 DOWNTO 0) <= TDL(16 DOWNTO 0);

  PolyTerms_3 <= PolyTerms(3);

  PolyTerms_2 <= PolyTerms(2);

  PolyTerms_1 <= PolyTerms(1);


  PolyTerms_gen: FOR jj_select IN 0 TO 3 GENERATE
    PolyTerms(jj_select) <= TDL(to_integer(resize(selShift_data(jj_select), 32) - 1));
  END GENERATE PolyTerms_gen;


  PolyTerms_0 <= PolyTerms(0);

  PNSeqOut <= PolyTerms_3 XOR (PolyTerms_2 XOR (PolyTerms_0 XOR PolyTerms_1));

  TDL_1(0) <= PNSeqOut;
  TDL_1_gen: FOR idx0 IN 0 TO 16 GENERATE
    TDL_1(idx0 + 1) <= ShiftTerms(idx0);
  END GENERATE;

  VectorTDL_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        TDLPrevious <= (OTHERS => '1');
      ELSIF enb_1_32_0 = '1' THEN
        TDLPrevious <= TDL_1;
      END IF;
    END IF;
  END PROCESS VectorTDL_process;


  
  TDL <= TDLPrevious WHEN inportReset = '0' ELSE
      InitStates;

  OutputMask <= c_OutputMask_data;


  MaskANDtoXOR_gen: FOR t_0 IN 0 TO 17 GENERATE
    MaskANDtoXOR(t_0) <= TDL(t_0) AND OutputMask(t_0);
  END GENERATE MaskANDtoXOR_gen;


  MaskANDtoXOR_0 <= MaskANDtoXOR(0);

  MaskANDtoXOR_1 <= MaskANDtoXOR(1);

  MaskANDtoXOR_2 <= MaskANDtoXOR(2);

  MaskANDtoXOR_3 <= MaskANDtoXOR(3);

  MaskANDtoXOR_4 <= MaskANDtoXOR(4);

  MaskANDtoXOR_5 <= MaskANDtoXOR(5);

  MaskANDtoXOR_6 <= MaskANDtoXOR(6);

  MaskANDtoXOR_7 <= MaskANDtoXOR(7);

  MaskANDtoXOR_8 <= MaskANDtoXOR(8);

  MaskANDtoXOR_9 <= MaskANDtoXOR(9);

  MaskANDtoXOR_10 <= MaskANDtoXOR(10);

  MaskANDtoXOR_11 <= MaskANDtoXOR(11);

  MaskANDtoXOR_12 <= MaskANDtoXOR(12);

  MaskANDtoXOR_13 <= MaskANDtoXOR(13);

  MaskANDtoXOR_14 <= MaskANDtoXOR(14);

  MaskANDtoXOR_15 <= MaskANDtoXOR(15);

  MaskANDtoXOR_16 <= MaskANDtoXOR(16);

  MaskANDtoXOR_17 <= MaskANDtoXOR(17);

  xorMask_output : PROCESS (MaskANDtoXOR_0, MaskANDtoXOR_1, MaskANDtoXOR_10, MaskANDtoXOR_11,
       MaskANDtoXOR_12, MaskANDtoXOR_13, MaskANDtoXOR_14, MaskANDtoXOR_15,
       MaskANDtoXOR_16, MaskANDtoXOR_17, MaskANDtoXOR_2, MaskANDtoXOR_3,
       MaskANDtoXOR_4, MaskANDtoXOR_5, MaskANDtoXOR_6, MaskANDtoXOR_7,
       MaskANDtoXOR_8, MaskANDtoXOR_9)
    VARIABLE t : std_logic;
  BEGIN
    t := MaskANDtoXOR_16 XOR (MaskANDtoXOR_15 XOR (MaskANDtoXOR_14 XOR (MaskANDtoXOR_13 XOR (MaskANDtoXOR_12 XOR (MaskANDtoXOR_11 XOR (MaskANDtoXOR_10 XOR (MaskANDtoXOR_9 XOR (MaskANDtoXOR_8 XOR (MaskANDtoXOR_7 XOR (MaskANDtoXOR_6 XOR (MaskANDtoXOR_5 XOR (MaskANDtoXOR_4 XOR (MaskANDtoXOR_3 XOR (MaskANDtoXOR_2 XOR (MaskANDtoXOR_0 XOR MaskANDtoXOR_1)))))))))))))));
    t := MaskANDtoXOR_17 XOR t;
    PNSeqBits <= t;
  END PROCESS xorMask_output;


  PNUfix <= PNSeqBits;

  PN_Sequence <= PNUfix;

END rtl;

