-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_Subsystem4.vhd
-- Created: 2025-10-27 18:12:30
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_Subsystem4
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4
-- Hierarchy Level: 4
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dvbs2_ip_src_Subsystem4 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_32_0                        :   IN    std_logic;
        rst                               :   IN    std_logic;
        enb_1                             :   IN    std_logic;
        modcodidx                         :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
        Out2_re                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        Out2_im                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        Out3_re                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        Out3_im                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        Out4_re                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        Out4_im                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        Out5_re                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        Out5_im                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        Out6_re                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        Out6_im                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        Out7_re                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        Out7_im                           :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
        Out1                              :   OUT   std_logic
        );
END dvbs2_ip_src_Subsystem4;


ARCHITECTURE rtl OF dvbs2_ip_src_Subsystem4 IS

  -- Component Declarations
  COMPONENT dvbs2_ip_src_txLUT1_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          rst                             :   IN    std_logic;
          enb_1                           :   IN    std_logic;
          Out1_re                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          Out1_im                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          endOfLUT                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_txLUT2_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          rst                             :   IN    std_logic;
          enb_1                           :   IN    std_logic;
          Out1_re                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          Out1_im                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          endOfLUT                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_txLUT3_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          rst                             :   IN    std_logic;
          enb_1                           :   IN    std_logic;
          Out1_re                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          Out1_im                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          endOfLUT                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_txLUT4_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          rst                             :   IN    std_logic;
          enb_1                           :   IN    std_logic;
          Out1_re                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          Out1_im                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          endOfLUT                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_txLUT5_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          rst                             :   IN    std_logic;
          enb_1                           :   IN    std_logic;
          Out1_re                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          Out1_im                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          endOfLUT                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_txLUT6_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          rst                             :   IN    std_logic;
          enb_1                           :   IN    std_logic;
          Out1_re                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          Out1_im                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En16
          endOfLUT                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dvbs2_ip_src_txLUT1_block
    USE ENTITY work.dvbs2_ip_src_txLUT1_block(rtl);

  FOR ALL : dvbs2_ip_src_txLUT2_block
    USE ENTITY work.dvbs2_ip_src_txLUT2_block(rtl);

  FOR ALL : dvbs2_ip_src_txLUT3_block
    USE ENTITY work.dvbs2_ip_src_txLUT3_block(rtl);

  FOR ALL : dvbs2_ip_src_txLUT4_block
    USE ENTITY work.dvbs2_ip_src_txLUT4_block(rtl);

  FOR ALL : dvbs2_ip_src_txLUT5_block
    USE ENTITY work.dvbs2_ip_src_txLUT5_block(rtl);

  FOR ALL : dvbs2_ip_src_txLUT6_block
    USE ENTITY work.dvbs2_ip_src_txLUT6_block(rtl);

  -- Signals
  SIGNAL txLUT1_Out1_re                   : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL txLUT1_Out1_im                   : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL txLUT1_endOfLUT                  : std_logic;
  SIGNAL txLUT2_Out1_re                   : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL txLUT2_Out1_im                   : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL txLUT2_endOfLUT                  : std_logic;
  SIGNAL txLUT3_Out1_re                   : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL txLUT3_Out1_im                   : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL txLUT3_endOfLUT                  : std_logic;
  SIGNAL txLUT4_Out1_re                   : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL txLUT4_Out1_im                   : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL txLUT4_endOfLUT                  : std_logic;
  SIGNAL txLUT5_Out1_re                   : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL txLUT5_Out1_im                   : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL txLUT5_endOfLUT                  : std_logic;
  SIGNAL txLUT6_Out1_re                   : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL txLUT6_Out1_im                   : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL txLUT6_endOfLUT                  : std_logic;
  SIGNAL modcodidx_unsigned               : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL Logical_Operator1_out1           : std_logic;
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL Logical_Operator2_out1           : std_logic;
  SIGNAL Compare_To_Constant2_out1        : std_logic;
  SIGNAL Logical_Operator3_out1           : std_logic;
  SIGNAL Compare_To_Constant3_out1        : std_logic;
  SIGNAL Logical_Operator4_out1           : std_logic;
  SIGNAL Compare_To_Constant4_out1        : std_logic;
  SIGNAL Logical_Operator5_out1           : std_logic;
  SIGNAL Compare_To_Constant5_out1        : std_logic;
  SIGNAL Logical_Operator6_out1           : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;

BEGIN
  u_txLUT1 : dvbs2_ip_src_txLUT1_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              rst => rst,
              enb_1 => enb_1,
              Out1_re => txLUT1_Out1_re,  -- sfix18_En16
              Out1_im => txLUT1_Out1_im,  -- sfix18_En16
              endOfLUT => txLUT1_endOfLUT
              );

  u_txLUT2 : dvbs2_ip_src_txLUT2_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              rst => rst,
              enb_1 => enb_1,
              Out1_re => txLUT2_Out1_re,  -- sfix18_En16
              Out1_im => txLUT2_Out1_im,  -- sfix18_En16
              endOfLUT => txLUT2_endOfLUT
              );

  u_txLUT3 : dvbs2_ip_src_txLUT3_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              rst => rst,
              enb_1 => enb_1,
              Out1_re => txLUT3_Out1_re,  -- sfix18_En16
              Out1_im => txLUT3_Out1_im,  -- sfix18_En16
              endOfLUT => txLUT3_endOfLUT
              );

  u_txLUT4 : dvbs2_ip_src_txLUT4_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              rst => rst,
              enb_1 => enb_1,
              Out1_re => txLUT4_Out1_re,  -- sfix18_En16
              Out1_im => txLUT4_Out1_im,  -- sfix18_En16
              endOfLUT => txLUT4_endOfLUT
              );

  u_txLUT5 : dvbs2_ip_src_txLUT5_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              rst => rst,
              enb_1 => enb_1,
              Out1_re => txLUT5_Out1_re,  -- sfix18_En16
              Out1_im => txLUT5_Out1_im,  -- sfix18_En16
              endOfLUT => txLUT5_endOfLUT
              );

  u_txLUT6 : dvbs2_ip_src_txLUT6_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              rst => rst,
              enb_1 => enb_1,
              Out1_re => txLUT6_Out1_re,  -- sfix18_En16
              Out1_im => txLUT6_Out1_im,  -- sfix18_En16
              endOfLUT => txLUT6_endOfLUT
              );

  modcodidx_unsigned <= unsigned(modcodidx);

  
  Compare_To_Constant_out1 <= '1' WHEN modcodidx_unsigned = to_unsigned(16#0C#, 5) ELSE
      '0';

  Logical_Operator1_out1 <= txLUT1_endOfLUT AND Compare_To_Constant_out1;

  
  Compare_To_Constant1_out1 <= '1' WHEN modcodidx_unsigned = to_unsigned(16#0D#, 5) ELSE
      '0';

  Logical_Operator2_out1 <= txLUT2_endOfLUT AND Compare_To_Constant1_out1;

  
  Compare_To_Constant2_out1 <= '1' WHEN modcodidx_unsigned = to_unsigned(16#0E#, 5) ELSE
      '0';

  Logical_Operator3_out1 <= txLUT3_endOfLUT AND Compare_To_Constant2_out1;

  
  Compare_To_Constant3_out1 <= '1' WHEN modcodidx_unsigned = to_unsigned(16#0F#, 5) ELSE
      '0';

  Logical_Operator4_out1 <= txLUT4_endOfLUT AND Compare_To_Constant3_out1;

  
  Compare_To_Constant4_out1 <= '1' WHEN modcodidx_unsigned = to_unsigned(16#10#, 5) ELSE
      '0';

  Logical_Operator5_out1 <= txLUT5_endOfLUT AND Compare_To_Constant4_out1;

  
  Compare_To_Constant5_out1 <= '1' WHEN modcodidx_unsigned = to_unsigned(16#11#, 5) ELSE
      '0';

  Logical_Operator6_out1 <= txLUT6_endOfLUT AND Compare_To_Constant5_out1;

  Logical_Operator_out1 <= Logical_Operator6_out1 OR (Logical_Operator5_out1 OR (Logical_Operator4_out1 OR (Logical_Operator3_out1 OR (Logical_Operator1_out1 OR Logical_Operator2_out1))));

  Out2_re <= txLUT1_Out1_re;

  Out2_im <= txLUT1_Out1_im;

  Out3_re <= txLUT2_Out1_re;

  Out3_im <= txLUT2_Out1_im;

  Out4_re <= txLUT3_Out1_re;

  Out4_im <= txLUT3_Out1_im;

  Out5_re <= txLUT4_Out1_re;

  Out5_im <= txLUT4_Out1_im;

  Out6_re <= txLUT5_Out1_re;

  Out6_im <= txLUT5_Out1_im;

  Out7_re <= txLUT6_Out1_re;

  Out7_im <= txLUT6_Out1_im;

  Out1 <= Logical_Operator_out1;

END rtl;

