-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_DVB_S2_HDL_Receiver.vhd
-- Created: 2025-10-27 18:12:30
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_DVB_S2_HDL_Receiver
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver
-- Hierarchy Level: 2
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dvbs2_ip_src_DVB_S2_HDL_Receiver IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        enb_1_8_1                         :   IN    std_logic;
        enb_1_32_0                        :   IN    std_logic;
        enb_1_32_1                        :   IN    std_logic;
        enb_1_1_1                         :   IN    std_logic;
        enb_1_8_0                         :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        dataIn_im                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        validIn                           :   IN    std_logic;
        rstFCPO                           :   IN    std_logic;
        syncSymb_re                       :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
        syncSymb_im                       :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
        syncSymbValid                     :   OUT   std_logic;
        numSynced                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        MODCOD                            :   OUT   std_logic_vector(4 DOWNTO 0);  -- ufix5
        fecFrame                          :   OUT   std_logic;  -- ufix1
        fineFreqEst                       :   OUT   std_logic_vector(20 DOWNTO 0);  -- sfix21_En21
        bitsOut                           :   OUT   std_logic;
        startOut                          :   OUT   std_logic;
        endOut                            :   OUT   std_logic;
        validOut                          :   OUT   std_logic;
        invalidPkt                        :   OUT   std_logic;
        BBheaderParams_TSorGS             :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        BBheaderParams_UPL                :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        BBheaderParams_DFL                :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        BBheaderParams_SYNC               :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END dvbs2_ip_src_DVB_S2_HDL_Receiver;


ARCHITECTURE rtl OF dvbs2_ip_src_DVB_S2_HDL_Receiver IS

  -- Component Declarations
  COMPONENT dvbs2_ip_src_Synchronizer_and_PL_Header_Decoder
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_8_1                       :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          enb_1_32_1                      :   IN    std_logic;
          enb_1_8_0                       :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          dataIn_im                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          validIn                         :   IN    std_logic;
          rstFCPO                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
          dataOut_im                      :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
          validOut                        :   OUT   std_logic;
          endOfPLSC                       :   OUT   std_logic;
          headerInfo_MODCOD               :   OUT   std_logic_vector(4 DOWNTO 0);  -- ufix5
          headerInfo_FECFrame             :   OUT   std_logic;  -- ufix1
          diagBus_NormalizedFrequencyEstimates_NormalizedFineFrequencyEstimate :   OUT   std_logic_vector(20 DOWNTO 0)  -- sfix21_En21
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_Demod_Deinterleave_and_FECDecode
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
          dataIn_im                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En14
          validIn                         :   IN    std_logic;
          endOfPLSC                       :   IN    std_logic;
          MODCOD                          :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
          bitsOut                         :   OUT   std_logic;
          ctrl_start                      :   OUT   std_logic;
          ctrl_valid                      :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_Stream_Recovery
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          bitsIn                          :   IN    std_logic;
          startIn                         :   IN    std_logic;
          validIn                         :   IN    std_logic;
          bitsOut                         :   OUT   std_logic;
          startOut                        :   OUT   std_logic;
          endOut                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic;
          invalidPkt                      :   OUT   std_logic;
          TSorGS                          :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          UPL                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          DFL                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          SYNC                            :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dvbs2_ip_src_Synchronizer_and_PL_Header_Decoder
    USE ENTITY work.dvbs2_ip_src_Synchronizer_and_PL_Header_Decoder(rtl);

  FOR ALL : dvbs2_ip_src_Demod_Deinterleave_and_FECDecode
    USE ENTITY work.dvbs2_ip_src_Demod_Deinterleave_and_FECDecode(rtl);

  FOR ALL : dvbs2_ip_src_Stream_Recovery
    USE ENTITY work.dvbs2_ip_src_Stream_Recovery(rtl);

  -- Signals
  SIGNAL SymbolDemodInDataOut_re          : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL SymbolDemodInDataOut_im          : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL SymbolDemodInValidOut            : std_logic;
  SIGNAL EndOfPLSC                        : std_logic;
  SIGNAL HeaderInformation_MODCOD         : std_logic_vector(4 DOWNTO 0);  -- ufix5
  SIGNAL HeaderInformation_FECFrame       : std_logic;  -- ufix1
  SIGNAL diagBusPLHeaderEx_NormalizedFrequencyEstimates_NormalizedFineFrequencyEstimate : std_logic_vector(20 DOWNTO 0);  -- ufix21
  SIGNAL count_step                       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL HDL_Counter_out1                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL count                            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL count_1                          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL FECFrame_1                       : std_logic;  -- ufix1
  SIGNAL NormalizedFineFrequencyEstimate  : signed(20 DOWNTO 0);  -- sfix21_En21
  SIGNAL SymbolDemodInDataOut_re_signed   : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL SymbolDemodInDataOut_im_signed   : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Upsample_zero_re                 : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Upsample_zero_im                 : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Upsample_muxout_re               : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Upsample_muxout_im               : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Upsample_bypass_reg_re           : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Upsample_bypass_reg_im           : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Upsample_bypassout_re            : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Upsample_bypassout_im            : signed(17 DOWNTO 0);  -- sfix18_En14
  SIGNAL Upsample1_zero                   : std_logic;
  SIGNAL Upsample1_muxout                 : std_logic;
  SIGNAL Upsample1_bypass_reg             : std_logic;  -- ufix1
  SIGNAL Upsample1_bypassout              : std_logic;
  SIGNAL Upsample2_zero                   : std_logic;
  SIGNAL Upsample2_muxout                 : std_logic;
  SIGNAL Upsample2_bypass_reg             : std_logic;  -- ufix1
  SIGNAL Upsample2_bypassout              : std_logic;
  SIGNAL MODCOD_tmp                       : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Repeat1_out1                     : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Repeat1_out1_1                   : std_logic_vector(4 DOWNTO 0);  -- ufix5
  SIGNAL Demod_Deinterleave_and_FECDecode_bitsOut : std_logic;
  SIGNAL Demod_Deinterleave_and_FECDecode_ctrl_start : std_logic;
  SIGNAL Demod_Deinterleave_and_FECDecode_ctrl_valid : std_logic;
  SIGNAL start                            : std_logic;
  SIGNAL valid                            : std_logic;
  SIGNAL Stream_Recovery_bitsOut          : std_logic;
  SIGNAL Stream_Recovery_startOut         : std_logic;
  SIGNAL Stream_Recovery_endOut           : std_logic;
  SIGNAL Stream_Recovery_validOut         : std_logic;
  SIGNAL Stream_Recovery_invalidPkt       : std_logic;
  SIGNAL TSorGS                           : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL UPL                              : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL DFL                              : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL SYNC                             : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  -- Use this port to enable the CCFO 
  -- for higer carrier offsets
  -- Use this port to enable the CCFO 
  -- for higer carrier offsets

  u_Synchronizer_and_PL_Header_Decoder : dvbs2_ip_src_Synchronizer_and_PL_Header_Decoder
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_8_1 => enb_1_8_1,
              enb_1_32_0 => enb_1_32_0,
              enb_1_32_1 => enb_1_32_1,
              enb_1_8_0 => enb_1_8_0,
              dataIn_re => dataIn_re,  -- sfix18_En15
              dataIn_im => dataIn_im,  -- sfix18_En15
              validIn => validIn,
              rstFCPO => rstFCPO,
              dataOut_re => SymbolDemodInDataOut_re,  -- sfix18_En14
              dataOut_im => SymbolDemodInDataOut_im,  -- sfix18_En14
              validOut => SymbolDemodInValidOut,
              endOfPLSC => EndOfPLSC,
              headerInfo_MODCOD => HeaderInformation_MODCOD,  -- ufix5
              headerInfo_FECFrame => HeaderInformation_FECFrame,  -- ufix1
              diagBus_NormalizedFrequencyEstimates_NormalizedFineFrequencyEstimate => diagBusPLHeaderEx_NormalizedFrequencyEstimates_NormalizedFineFrequencyEstimate  -- sfix21_En21
              );

  u_Demod_Deinterleave_and_FECDecode : dvbs2_ip_src_Demod_Deinterleave_and_FECDecode
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn_re => std_logic_vector(Upsample_bypassout_re),  -- sfix18_En14
              dataIn_im => std_logic_vector(Upsample_bypassout_im),  -- sfix18_En14
              validIn => Upsample1_bypassout,
              endOfPLSC => Upsample2_bypassout,
              MODCOD => Repeat1_out1_1,  -- ufix5
              bitsOut => Demod_Deinterleave_and_FECDecode_bitsOut,
              ctrl_start => Demod_Deinterleave_and_FECDecode_ctrl_start,
              ctrl_valid => Demod_Deinterleave_and_FECDecode_ctrl_valid
              );

  u_Stream_Recovery : dvbs2_ip_src_Stream_Recovery
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              bitsIn => Demod_Deinterleave_and_FECDecode_bitsOut,
              startIn => start,
              validIn => valid,
              bitsOut => Stream_Recovery_bitsOut,
              startOut => Stream_Recovery_startOut,
              endOut => Stream_Recovery_endOut,
              validOut => Stream_Recovery_validOut,
              invalidPkt => Stream_Recovery_invalidPkt,
              TSorGS => TSorGS,  -- ufix2
              UPL => UPL,  -- uint16
              DFL => DFL,  -- uint16
              SYNC => SYNC  -- uint8
              );

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  count_step <= to_unsigned(1, 32);

  count <= HDL_Counter_out1 + count_step;

  
  count_1 <= HDL_Counter_out1 WHEN EndOfPLSC = '0' ELSE
      count;

  HDL_Counter_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        HDL_Counter_out1 <= to_unsigned(0, 32);
      ELSIF enb_1_32_0 = '1' THEN
        HDL_Counter_out1 <= count_1;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  numSynced <= std_logic_vector(HDL_Counter_out1);

  FECFrame_1 <= HeaderInformation_FECFrame;

  NormalizedFineFrequencyEstimate <= signed(diagBusPLHeaderEx_NormalizedFrequencyEstimates_NormalizedFineFrequencyEstimate);

  fineFreqEst <= std_logic_vector(NormalizedFineFrequencyEstimate);

  SymbolDemodInDataOut_re_signed <= signed(SymbolDemodInDataOut_re);

  SymbolDemodInDataOut_im_signed <= signed(SymbolDemodInDataOut_im);

  Upsample_zero_re <= to_signed(16#00000#, 18);
  Upsample_zero_im <= to_signed(16#00000#, 18);

  -- Upsample: Upsample by 32, Sample offset 0 
  
  Upsample_muxout_re <= SymbolDemodInDataOut_re_signed WHEN enb_1_32_1 = '1' ELSE
      Upsample_zero_re;
  
  Upsample_muxout_im <= SymbolDemodInDataOut_im_signed WHEN enb_1_32_1 = '1' ELSE
      Upsample_zero_im;

  -- Upsample bypass register
  Upsample_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Upsample_bypass_reg_re <= to_signed(16#00000#, 18);
        Upsample_bypass_reg_im <= to_signed(16#00000#, 18);
      ELSIF enb_1_1_1 = '1' THEN
        Upsample_bypass_reg_im <= Upsample_muxout_im;
        Upsample_bypass_reg_re <= Upsample_muxout_re;
      END IF;
    END IF;
  END PROCESS Upsample_bypass_process;

  
  Upsample_bypassout_re <= Upsample_muxout_re WHEN enb_1_1_1 = '1' ELSE
      Upsample_bypass_reg_re;
  
  Upsample_bypassout_im <= Upsample_muxout_im WHEN enb_1_1_1 = '1' ELSE
      Upsample_bypass_reg_im;

  Upsample1_zero <= '0';

  -- Upsample1: Upsample by 32, Sample offset 0 
  
  Upsample1_muxout <= SymbolDemodInValidOut WHEN enb_1_32_1 = '1' ELSE
      Upsample1_zero;

  -- Upsample bypass register
  Upsample1_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Upsample1_bypass_reg <= '0';
      ELSIF enb_1_1_1 = '1' THEN
        Upsample1_bypass_reg <= Upsample1_muxout;
      END IF;
    END IF;
  END PROCESS Upsample1_bypass_process;

  
  Upsample1_bypassout <= Upsample1_muxout WHEN enb_1_1_1 = '1' ELSE
      Upsample1_bypass_reg;

  Upsample2_zero <= '0';

  -- Upsample2: Upsample by 32, Sample offset 0 
  
  Upsample2_muxout <= EndOfPLSC WHEN enb_1_32_1 = '1' ELSE
      Upsample2_zero;

  -- Upsample bypass register
  Upsample2_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Upsample2_bypass_reg <= '0';
      ELSIF enb_1_1_1 = '1' THEN
        Upsample2_bypass_reg <= Upsample2_muxout;
      END IF;
    END IF;
  END PROCESS Upsample2_bypass_process;

  
  Upsample2_bypassout <= Upsample2_muxout WHEN enb_1_1_1 = '1' ELSE
      Upsample2_bypass_reg;

  MODCOD_tmp <= unsigned(HeaderInformation_MODCOD);

  Repeat1_out1 <= MODCOD_tmp;

  Repeat1_out1_1 <= std_logic_vector(Repeat1_out1);

  start <= Demod_Deinterleave_and_FECDecode_ctrl_start;

  valid <= Demod_Deinterleave_and_FECDecode_ctrl_valid;

  syncSymb_re <= SymbolDemodInDataOut_re;

  syncSymb_im <= SymbolDemodInDataOut_im;

  syncSymbValid <= SymbolDemodInValidOut;

  MODCOD <= HeaderInformation_MODCOD;

  fecFrame <= FECFrame_1;

  bitsOut <= Stream_Recovery_bitsOut;

  startOut <= Stream_Recovery_startOut;

  endOut <= Stream_Recovery_endOut;

  validOut <= Stream_Recovery_validOut;

  invalidPkt <= Stream_Recovery_invalidPkt;

  BBheaderParams_TSorGS <= TSorGS;

  BBheaderParams_UPL <= UPL;

  BBheaderParams_DFL <= DFL;

  BBheaderParams_SYNC <= SYNC;

END rtl;

