-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_Indicate_End_of_Every_ShortFrame_Length_Samples.vhd
-- Created: 2025-10-27 18:12:26
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_Indicate_End_of_Every_ShortFrame_Length_Samples
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM 
-- Address Generator/Generate and Add Read Base Address/Indicate End of Every ShortFrame Length Sample
-- Hierarchy Level: 7
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dvbs2_ip_src_Indicate_End_of_Every_ShortFrame_Length_Samples IS
  PORT( readAddr                          :   IN    std_logic_vector(16 DOWNTO 0);  -- ufix17
        endIndicate                       :   OUT   std_logic
        );
END dvbs2_ip_src_Indicate_End_of_Every_ShortFrame_Length_Samples;


ARCHITECTURE rtl OF dvbs2_ip_src_Indicate_End_of_Every_ShortFrame_Length_Samples IS

  -- Signals
  SIGNAL readAddr_unsigned                : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL Compare_To_Constant2_out1        : std_logic;
  SIGNAL Compare_To_Constant3_out1        : std_logic;
  SIGNAL Logical_Operator1_out1           : std_logic;

BEGIN
  readAddr_unsigned <= unsigned(readAddr);

  
  Compare_To_Constant_out1 <= '1' WHEN readAddr_unsigned = to_unsigned(16#03F47#, 17) ELSE
      '0';

  
  Compare_To_Constant1_out1 <= '1' WHEN readAddr_unsigned = to_unsigned(16#07E8F#, 17) ELSE
      '0';

  
  Compare_To_Constant2_out1 <= '1' WHEN readAddr_unsigned = to_unsigned(16#0BDD7#, 17) ELSE
      '0';

  
  Compare_To_Constant3_out1 <= '1' WHEN readAddr_unsigned = to_unsigned(16#0FD1F#, 17) ELSE
      '0';

  Logical_Operator1_out1 <= Compare_To_Constant3_out1 OR (Compare_To_Constant2_out1 OR (Compare_To_Constant_out1 OR Compare_To_Constant1_out1));

  endIndicate <= Logical_Operator1_out1;

END rtl;

