-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_leadingZeroDetector_block.vhd
-- Created: 2025-10-27 18:12:26
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_leadingZeroDetector_block
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/logImplementation/log/RangeReduction/leadingZeroDetector
-- Hierarchy Level: 8
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dvbs2_ip_src_leadingZeroDetector_block IS
  PORT( x                                 :   IN    std_logic_vector(47 DOWNTO 0);  -- ufix48_En48
        exp_e                             :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END dvbs2_ip_src_leadingZeroDetector_block;


ARCHITECTURE rtl OF dvbs2_ip_src_leadingZeroDetector_block IS

  -- Signals
  SIGNAL x_unsigned                       : unsigned(47 DOWNTO 0);  -- ufix48_En48
  SIGNAL s                                : std_logic;
  SIGNAL p148_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En47
  SIGNAL temp                             : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_1                              : std_logic;
  SIGNAL p145_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En48
  SIGNAL temp_1                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp                              : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_2                              : std_logic;
  SIGNAL p142_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En49
  SIGNAL temp_2                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_1                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_3                              : std_logic;
  SIGNAL p139_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En50
  SIGNAL temp_3                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_2                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_4                              : std_logic;
  SIGNAL p136_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En51
  SIGNAL temp_4                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_3                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_5                              : std_logic;
  SIGNAL p133_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En52
  SIGNAL temp_5                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_4                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_6                              : std_logic;
  SIGNAL p130_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En53
  SIGNAL temp_6                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_5                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_7                              : std_logic;
  SIGNAL p127_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En54
  SIGNAL temp_7                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_6                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_8                              : std_logic;
  SIGNAL p124_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En55
  SIGNAL temp_8                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_7                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_9                              : std_logic;
  SIGNAL p121_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En56
  SIGNAL temp_9                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_8                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_10                             : std_logic;
  SIGNAL p118_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En57
  SIGNAL temp_10                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_9                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_11                             : std_logic;
  SIGNAL p115_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En58
  SIGNAL temp_11                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_10                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_12                             : std_logic;
  SIGNAL p112_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En59
  SIGNAL temp_12                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_11                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_13                             : std_logic;
  SIGNAL p109_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En60
  SIGNAL temp_13                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_12                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_14                             : std_logic;
  SIGNAL p106_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En61
  SIGNAL temp_14                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_13                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_15                             : std_logic;
  SIGNAL p103_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En62
  SIGNAL temp_15                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_14                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_16                             : std_logic;
  SIGNAL p100_cast                        : unsigned(95 DOWNTO 0);  -- ufix96_En63
  SIGNAL temp_16                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_15                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_17                             : std_logic;
  SIGNAL p97_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En64
  SIGNAL temp_17                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_16                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_18                             : std_logic;
  SIGNAL p94_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En65
  SIGNAL temp_18                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_17                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_19                             : std_logic;
  SIGNAL p91_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En66
  SIGNAL temp_19                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_18                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_20                             : std_logic;
  SIGNAL p88_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En67
  SIGNAL temp_20                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_19                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_21                             : std_logic;
  SIGNAL p85_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En68
  SIGNAL temp_21                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_20                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_22                             : std_logic;
  SIGNAL p82_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En69
  SIGNAL temp_22                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_21                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_23                             : std_logic;
  SIGNAL p79_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En70
  SIGNAL temp_23                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_22                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_24                             : std_logic;
  SIGNAL p76_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En71
  SIGNAL temp_24                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_23                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_25                             : std_logic;
  SIGNAL p73_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En72
  SIGNAL temp_25                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_24                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_26                             : std_logic;
  SIGNAL p70_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En73
  SIGNAL temp_26                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_25                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_27                             : std_logic;
  SIGNAL p67_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En74
  SIGNAL temp_27                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_26                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_28                             : std_logic;
  SIGNAL p64_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En75
  SIGNAL temp_28                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_27                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_29                             : std_logic;
  SIGNAL p61_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En76
  SIGNAL temp_29                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_28                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_30                             : std_logic;
  SIGNAL p58_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En77
  SIGNAL temp_30                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_29                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_31                             : std_logic;
  SIGNAL p55_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En78
  SIGNAL temp_31                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_30                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_32                             : std_logic;
  SIGNAL p52_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En79
  SIGNAL temp_32                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_31                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_33                             : std_logic;
  SIGNAL p49_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En80
  SIGNAL temp_33                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_32                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_34                             : std_logic;
  SIGNAL p46_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En81
  SIGNAL temp_34                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_33                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_35                             : std_logic;
  SIGNAL p43_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En82
  SIGNAL temp_35                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_34                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_36                             : std_logic;
  SIGNAL p40_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En83
  SIGNAL temp_36                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_35                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_37                             : std_logic;
  SIGNAL p37_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En84
  SIGNAL temp_37                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_36                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_38                             : std_logic;
  SIGNAL p34_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En85
  SIGNAL temp_38                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_37                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_39                             : std_logic;
  SIGNAL p31_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En86
  SIGNAL temp_39                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_38                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_40                             : std_logic;
  SIGNAL p28_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En87
  SIGNAL temp_40                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_39                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_41                             : std_logic;
  SIGNAL p25_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En88
  SIGNAL temp_41                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_40                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_42                             : std_logic;
  SIGNAL p22_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En89
  SIGNAL temp_42                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_41                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_43                             : std_logic;
  SIGNAL p19_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En90
  SIGNAL temp_43                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_42                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_44                             : std_logic;
  SIGNAL p16_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En91
  SIGNAL temp_44                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_43                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_45                             : std_logic;
  SIGNAL p13_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En92
  SIGNAL temp_45                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_44                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_46                             : std_logic;
  SIGNAL p10_cast                         : unsigned(95 DOWNTO 0);  -- ufix96_En93
  SIGNAL temp_46                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_45                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_47                             : std_logic;
  SIGNAL p7_cast                          : unsigned(95 DOWNTO 0);  -- ufix96_En94
  SIGNAL temp_47                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_46                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_48                             : std_logic;
  SIGNAL temp_48                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_47                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL temp_49                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_48                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL exp_e_tmp                        : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  x_unsigned <= unsigned(x);

  p148_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s <= '1' WHEN p148_cast > unsigned'(X"000000000000800000000000") ELSE
      '0';

  temp <= to_signed(16#00000000#, 32);

  p145_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_1 <= '1' WHEN p145_cast > unsigned'(X"000000000001000000000000") ELSE
      '0';

  temp_1 <= to_signed(16#00000030#, 32);

  
  tmp <= temp WHEN s = '0' ELSE
      temp_1;

  p142_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_2 <= '1' WHEN p142_cast > unsigned'(X"000000000002000000000000") ELSE
      '0';

  temp_2 <= to_signed(16#0000002F#, 32);

  
  tmp_1 <= tmp WHEN s_1 = '0' ELSE
      temp_2;

  p139_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_3 <= '1' WHEN p139_cast > unsigned'(X"000000000004000000000000") ELSE
      '0';

  temp_3 <= to_signed(16#0000002E#, 32);

  
  tmp_2 <= tmp_1 WHEN s_2 = '0' ELSE
      temp_3;

  p136_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_4 <= '1' WHEN p136_cast > unsigned'(X"000000000008000000000000") ELSE
      '0';

  temp_4 <= to_signed(16#0000002D#, 32);

  
  tmp_3 <= tmp_2 WHEN s_3 = '0' ELSE
      temp_4;

  p133_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_5 <= '1' WHEN p133_cast > unsigned'(X"000000000010000000000000") ELSE
      '0';

  temp_5 <= to_signed(16#0000002C#, 32);

  
  tmp_4 <= tmp_3 WHEN s_4 = '0' ELSE
      temp_5;

  p130_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_6 <= '1' WHEN p130_cast > unsigned'(X"000000000020000000000000") ELSE
      '0';

  temp_6 <= to_signed(16#0000002B#, 32);

  
  tmp_5 <= tmp_4 WHEN s_5 = '0' ELSE
      temp_6;

  p127_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_7 <= '1' WHEN p127_cast > unsigned'(X"000000000040000000000000") ELSE
      '0';

  temp_7 <= to_signed(16#0000002A#, 32);

  
  tmp_6 <= tmp_5 WHEN s_6 = '0' ELSE
      temp_7;

  p124_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_8 <= '1' WHEN p124_cast > unsigned'(X"000000000080000000000000") ELSE
      '0';

  temp_8 <= to_signed(16#00000029#, 32);

  
  tmp_7 <= tmp_6 WHEN s_7 = '0' ELSE
      temp_8;

  p121_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_9 <= '1' WHEN p121_cast > unsigned'(X"000000000100000000000000") ELSE
      '0';

  temp_9 <= to_signed(16#00000028#, 32);

  
  tmp_8 <= tmp_7 WHEN s_8 = '0' ELSE
      temp_9;

  p118_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_10 <= '1' WHEN p118_cast > unsigned'(X"000000000200000000000000") ELSE
      '0';

  temp_10 <= to_signed(16#00000027#, 32);

  
  tmp_9 <= tmp_8 WHEN s_9 = '0' ELSE
      temp_10;

  p115_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_11 <= '1' WHEN p115_cast > unsigned'(X"000000000400000000000000") ELSE
      '0';

  temp_11 <= to_signed(16#00000008#, 32);

  
  tmp_10 <= tmp_9 WHEN s_10 = '0' ELSE
      temp_11;

  p112_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_12 <= '1' WHEN p112_cast > unsigned'(X"000000000800000000000000") ELSE
      '0';

  temp_12 <= to_signed(16#00000025#, 32);

  
  tmp_11 <= tmp_10 WHEN s_11 = '0' ELSE
      temp_12;

  p109_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_13 <= '1' WHEN p109_cast > unsigned'(X"000000001000000000000000") ELSE
      '0';

  temp_13 <= to_signed(16#00000024#, 32);

  
  tmp_12 <= tmp_11 WHEN s_12 = '0' ELSE
      temp_13;

  p106_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_14 <= '1' WHEN p106_cast > unsigned'(X"000000002000000000000000") ELSE
      '0';

  temp_14 <= to_signed(16#00000023#, 32);

  
  tmp_13 <= tmp_12 WHEN s_13 = '0' ELSE
      temp_14;

  p103_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_15 <= '1' WHEN p103_cast > unsigned'(X"000000004000000000000000") ELSE
      '0';

  temp_15 <= to_signed(16#00000022#, 32);

  
  tmp_14 <= tmp_13 WHEN s_14 = '0' ELSE
      temp_15;

  p100_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_16 <= '1' WHEN p100_cast > unsigned'(X"000000008000000000000000") ELSE
      '0';

  temp_16 <= to_signed(16#00000021#, 32);

  
  tmp_15 <= tmp_14 WHEN s_15 = '0' ELSE
      temp_16;

  p97_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_17 <= '1' WHEN p97_cast > unsigned'(X"000000010000000000000000") ELSE
      '0';

  temp_17 <= to_signed(16#00000020#, 32);

  
  tmp_16 <= tmp_15 WHEN s_16 = '0' ELSE
      temp_17;

  p94_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_18 <= '1' WHEN p94_cast > unsigned'(X"000000020000000000000000") ELSE
      '0';

  temp_18 <= to_signed(16#0000001F#, 32);

  
  tmp_17 <= tmp_16 WHEN s_17 = '0' ELSE
      temp_18;

  p91_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_19 <= '1' WHEN p91_cast > unsigned'(X"000000040000000000000000") ELSE
      '0';

  temp_19 <= to_signed(16#0000001E#, 32);

  
  tmp_18 <= tmp_17 WHEN s_18 = '0' ELSE
      temp_19;

  p88_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_20 <= '1' WHEN p88_cast > unsigned'(X"000000080000000000000000") ELSE
      '0';

  temp_20 <= to_signed(16#0000001D#, 32);

  
  tmp_19 <= tmp_18 WHEN s_19 = '0' ELSE
      temp_20;

  p85_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_21 <= '1' WHEN p85_cast > unsigned'(X"000000100000000000000000") ELSE
      '0';

  temp_21 <= to_signed(16#0000001C#, 32);

  
  tmp_20 <= tmp_19 WHEN s_20 = '0' ELSE
      temp_21;

  p82_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_22 <= '1' WHEN p82_cast > unsigned'(X"000000200000000000000000") ELSE
      '0';

  temp_22 <= to_signed(16#0000001B#, 32);

  
  tmp_21 <= tmp_20 WHEN s_21 = '0' ELSE
      temp_22;

  p79_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_23 <= '1' WHEN p79_cast > unsigned'(X"000000400000000000000000") ELSE
      '0';

  temp_23 <= to_signed(16#0000001A#, 32);

  
  tmp_22 <= tmp_21 WHEN s_22 = '0' ELSE
      temp_23;

  p76_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_24 <= '1' WHEN p76_cast > unsigned'(X"000000800000000000000000") ELSE
      '0';

  temp_24 <= to_signed(16#00000019#, 32);

  
  tmp_23 <= tmp_22 WHEN s_23 = '0' ELSE
      temp_24;

  p73_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_25 <= '1' WHEN p73_cast > unsigned'(X"000001000000000000000000") ELSE
      '0';

  temp_25 <= to_signed(16#00000018#, 32);

  
  tmp_24 <= tmp_23 WHEN s_24 = '0' ELSE
      temp_25;

  p70_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_26 <= '1' WHEN p70_cast > unsigned'(X"000002000000000000000000") ELSE
      '0';

  temp_26 <= to_signed(16#00000017#, 32);

  
  tmp_25 <= tmp_24 WHEN s_25 = '0' ELSE
      temp_26;

  p67_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_27 <= '1' WHEN p67_cast > unsigned'(X"000004000000000000000000") ELSE
      '0';

  temp_27 <= to_signed(16#00000016#, 32);

  
  tmp_26 <= tmp_25 WHEN s_26 = '0' ELSE
      temp_27;

  p64_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_28 <= '1' WHEN p64_cast > unsigned'(X"000008000000000000000000") ELSE
      '0';

  temp_28 <= to_signed(16#00000015#, 32);

  
  tmp_27 <= tmp_26 WHEN s_27 = '0' ELSE
      temp_28;

  p61_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_29 <= '1' WHEN p61_cast > unsigned'(X"000010000000000000000000") ELSE
      '0';

  temp_29 <= to_signed(16#00000014#, 32);

  
  tmp_28 <= tmp_27 WHEN s_28 = '0' ELSE
      temp_29;

  p58_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_30 <= '1' WHEN p58_cast > unsigned'(X"000020000000000000000000") ELSE
      '0';

  temp_30 <= to_signed(16#00000013#, 32);

  
  tmp_29 <= tmp_28 WHEN s_29 = '0' ELSE
      temp_30;

  p55_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_31 <= '1' WHEN p55_cast > unsigned'(X"000040000000000000000000") ELSE
      '0';

  temp_31 <= to_signed(16#00000012#, 32);

  
  tmp_30 <= tmp_29 WHEN s_30 = '0' ELSE
      temp_31;

  p52_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_32 <= '1' WHEN p52_cast > unsigned'(X"000080000000000000000000") ELSE
      '0';

  temp_32 <= to_signed(16#00000011#, 32);

  
  tmp_31 <= tmp_30 WHEN s_31 = '0' ELSE
      temp_32;

  p49_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_33 <= '1' WHEN p49_cast > unsigned'(X"000100000000000000000000") ELSE
      '0';

  temp_33 <= to_signed(16#00000010#, 32);

  
  tmp_32 <= tmp_31 WHEN s_32 = '0' ELSE
      temp_33;

  p46_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_34 <= '1' WHEN p46_cast > unsigned'(X"000200000000000000000000") ELSE
      '0';

  temp_34 <= to_signed(16#0000000F#, 32);

  
  tmp_33 <= tmp_32 WHEN s_33 = '0' ELSE
      temp_34;

  p43_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_35 <= '1' WHEN p43_cast > unsigned'(X"000400000000000000000000") ELSE
      '0';

  temp_35 <= to_signed(16#0000000E#, 32);

  
  tmp_34 <= tmp_33 WHEN s_34 = '0' ELSE
      temp_35;

  p40_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_36 <= '1' WHEN p40_cast > unsigned'(X"000800000000000000000000") ELSE
      '0';

  temp_36 <= to_signed(16#0000000D#, 32);

  
  tmp_35 <= tmp_34 WHEN s_35 = '0' ELSE
      temp_36;

  p37_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_37 <= '1' WHEN p37_cast > unsigned'(X"001000000000000000000000") ELSE
      '0';

  temp_37 <= to_signed(16#0000000C#, 32);

  
  tmp_36 <= tmp_35 WHEN s_36 = '0' ELSE
      temp_37;

  p34_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_38 <= '1' WHEN p34_cast > unsigned'(X"002000000000000000000000") ELSE
      '0';

  temp_38 <= to_signed(16#0000000B#, 32);

  
  tmp_37 <= tmp_36 WHEN s_37 = '0' ELSE
      temp_38;

  p31_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_39 <= '1' WHEN p31_cast > unsigned'(X"004000000000000000000000") ELSE
      '0';

  temp_39 <= to_signed(16#0000000A#, 32);

  
  tmp_38 <= tmp_37 WHEN s_38 = '0' ELSE
      temp_39;

  p28_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_40 <= '1' WHEN p28_cast > unsigned'(X"008000000000000000000000") ELSE
      '0';

  temp_40 <= to_signed(16#00000009#, 32);

  
  tmp_39 <= tmp_38 WHEN s_39 = '0' ELSE
      temp_40;

  p25_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_41 <= '1' WHEN p25_cast > unsigned'(X"010000000000000000000000") ELSE
      '0';

  temp_41 <= to_signed(16#00000008#, 32);

  
  tmp_40 <= tmp_39 WHEN s_40 = '0' ELSE
      temp_41;

  p22_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_42 <= '1' WHEN p22_cast > unsigned'(X"020000000000000000000000") ELSE
      '0';

  temp_42 <= to_signed(16#00000007#, 32);

  
  tmp_41 <= tmp_40 WHEN s_41 = '0' ELSE
      temp_42;

  p19_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_43 <= '1' WHEN p19_cast > unsigned'(X"040000000000000000000000") ELSE
      '0';

  temp_43 <= to_signed(16#00000006#, 32);

  
  tmp_42 <= tmp_41 WHEN s_42 = '0' ELSE
      temp_43;

  p16_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_44 <= '1' WHEN p16_cast > unsigned'(X"080000000000000000000000") ELSE
      '0';

  temp_44 <= to_signed(16#00000005#, 32);

  
  tmp_43 <= tmp_42 WHEN s_43 = '0' ELSE
      temp_44;

  p13_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_45 <= '1' WHEN p13_cast > unsigned'(X"100000000000000000000000") ELSE
      '0';

  temp_45 <= to_signed(16#00000004#, 32);

  
  tmp_44 <= tmp_43 WHEN s_44 = '0' ELSE
      temp_45;

  p10_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_46 <= '1' WHEN p10_cast > unsigned'(X"200000000000000000000000") ELSE
      '0';

  temp_46 <= to_signed(16#00000003#, 32);

  
  tmp_45 <= tmp_44 WHEN s_45 = '0' ELSE
      temp_46;

  p7_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  s_47 <= '1' WHEN p7_cast > unsigned'(X"400000000000000000000000") ELSE
      '0';

  temp_47 <= to_signed(16#00000002#, 32);

  
  tmp_46 <= tmp_45 WHEN s_46 = '0' ELSE
      temp_47;

  -- else
  --     while( )
  --         temp = temp+1;
  --         flag()=flag()*2;
  --     end
  -- end
  -- 
  -- end
  
  s_48 <= '1' WHEN x_unsigned = to_unsigned(0, 48) ELSE
      '0';

  temp_48 <= to_signed(16#00000001#, 32);

  
  tmp_47 <= tmp_46 WHEN s_47 = '0' ELSE
      temp_48;

  temp_49 <= to_signed(16#00000031#, 32);

  
  tmp_48 <= tmp_47 WHEN s_48 = '0' ELSE
      temp_49;

  exp_e_tmp <= unsigned(tmp_48(7 DOWNTO 0));

  exp_e <= std_logic_vector(exp_e_tmp);

END rtl;

