-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\dspmultichannelhdl\Multichannel_FIR_Filter_pkg.vhd
-- Created: 2026-01-14 10:53:58
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Multichannel_FIR_Filter_pkg IS
  TYPE vector_of_std_logic_vector16 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(15 DOWNTO 0);
  TYPE vector_of_std_logic_vector38 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(37 DOWNTO 0);
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
  TYPE vector_of_signed33 IS ARRAY (NATURAL RANGE <>) OF signed(32 DOWNTO 0);
  TYPE vector_of_signed38 IS ARRAY (NATURAL RANGE <>) OF signed(37 DOWNTO 0);
END Multichannel_FIR_Filter_pkg;

