open_system('gm_multi_module_phase_shift_generator_base');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_base/pwm_generator/Unit Delay1', 'user1');
annotate_port('gm_multi_module_phase_shift_generator_base/pwm_generator/Unit Delay1', 0, 1, 'cp : 0.812 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_base/pwm_generator/Add7_stage2', 'user2');
annotate_port('gm_multi_module_phase_shift_generator_base/pwm_generator/Add7_stage2', 0, 1, 'cp : 2.628 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_base/pwm_generator/Add7_stage3', 'user2');
annotate_port('gm_multi_module_phase_shift_generator_base/pwm_generator/Add7_stage3', 0, 1, 'cp : 4.678 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_base/pwm_generator/Relational Operator3', 'user1');
annotate_port('gm_multi_module_phase_shift_generator_base/pwm_generator/Relational Operator3', 0, 1, 'cp : 7.915 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_base/pwm_generator/Switch4', 'user2');
annotate_port('gm_multi_module_phase_shift_generator_base/pwm_generator/Switch4', 0, 1, 'cp : 5.894 ns');
