open_system('input_output_distributed_pipelining_multi_module_phase_shift_generator_base');
open_system('gm_input_output_distributed_pipelining_multi_module_phase_shift_generator_base');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_input_output_distributed_pipelining_multi_module_phase_shift_generator_base/pwm_generator/Relational Operator6', 'user1');
annotate_port('gm_input_output_distributed_pipelining_multi_module_phase_shift_generator_base/pwm_generator/Relational Operator6', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('input_output_distributed_pipelining_multi_module_phase_shift_generator_base/pwm_generator/Relational Operator6', 'user1');
annotate_port('input_output_distributed_pipelining_multi_module_phase_shift_generator_base/pwm_generator/Relational Operator6', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_input_output_distributed_pipelining_multi_module_phase_shift_generator_base/pwm_generator/Relational Operator7', 'user1');
annotate_port('gm_input_output_distributed_pipelining_multi_module_phase_shift_generator_base/pwm_generator/Relational Operator7', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('input_output_distributed_pipelining_multi_module_phase_shift_generator_base/pwm_generator/Relational Operator7', 'user1');
annotate_port('input_output_distributed_pipelining_multi_module_phase_shift_generator_base/pwm_generator/Relational Operator7', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_input_output_distributed_pipelining_multi_module_phase_shift_generator_base/pwm_generator/Relational Operator8', 'user1');
annotate_port('gm_input_output_distributed_pipelining_multi_module_phase_shift_generator_base/pwm_generator/Relational Operator8', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('input_output_distributed_pipelining_multi_module_phase_shift_generator_base/pwm_generator/Relational Operator8', 'user1');
annotate_port('input_output_distributed_pipelining_multi_module_phase_shift_generator_base/pwm_generator/Relational Operator8', 0, 1, 'Delays not moved across due to potential numerical mismatch');
