-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\hdl_coder_led_blinking\FFT_Comparison\MathWorks\hdlsrc\fft8\fft8_dut_tb.vhd
-- Created: 2026-07-15 18:12:15
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fft8_dut_tb
-- Source Path: 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_textio.ALL;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
LIBRARY STD;
USE STD.textio.ALL;
LIBRARY work;
USE work.fft8_dut_pkg.ALL;
USE work.fft8_dut_tb_pkg.ALL;

ENTITY fft8_dut_tb IS
END fft8_dut_tb;


ARCHITECTURE rtl OF fft8_dut_tb IS

  -- Component Declarations
  COMPONENT fft8_dut
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          validIn                         :   IN    std_logic;
          ce_out                          :   OUT   std_logic;
          dataOut_re                      :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
          dataOut_im                      :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : fft8_dut
    USE ENTITY work.fft8_dut(rtl);

  -- Signals
  SIGNAL clk                              : std_logic;
  SIGNAL reset                            : std_logic;
  SIGNAL clk_enable                       : std_logic;
  SIGNAL rawData_validIn                  : std_logic;
  SIGNAL validOut_done                    : std_logic;  -- ufix1
  SIGNAL rdEnb                            : std_logic;
  SIGNAL validOut_done_enb                : std_logic;  -- ufix1
  SIGNAL dataOut_re_addr                  : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL validOut_lastAddr                : std_logic;  -- ufix1
  SIGNAL resetn                           : std_logic;
  SIGNAL check2_done                      : std_logic;  -- ufix1
  SIGNAL dataOut_re_done                  : std_logic;  -- ufix1
  SIGNAL dataOut_re_done_enb              : std_logic;  -- ufix1
  SIGNAL dataOut_re_active                : std_logic;  -- ufix1
  SIGNAL holdData_validIn                 : std_logic;
  SIGNAL validIn_offset                   : std_logic;
  SIGNAL validIn_1                        : std_logic;
  SIGNAL dataIn_addr                      : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL dataIn_active                    : std_logic;  -- ufix1
  SIGNAL tb_enb_delay                     : std_logic;
  SIGNAL dataIn_enb                       : std_logic;  -- ufix1
  SIGNAL dataIn_addr_delay_1              : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL tb_enb                           : std_logic;
  SIGNAL snkDone                          : std_logic;
  SIGNAL rawData_dataIn                   : signed(15 DOWNTO 0);  -- int16
  SIGNAL holdData_dataIn                  : signed(15 DOWNTO 0);  -- int16
  SIGNAL dataIn_offset                    : signed(15 DOWNTO 0);  -- int16
  SIGNAL dataIn                           : signed(15 DOWNTO 0);  -- int16
  SIGNAL dataIn_1                         : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL snkDonen                         : std_logic;
  SIGNAL ce_out                           : std_logic;
  SIGNAL dataOut_re                       : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL dataOut_im                       : std_logic_vector(18 DOWNTO 0);  -- ufix19
  SIGNAL validOut                         : std_logic;
  SIGNAL dataOut_re_enb                   : std_logic;  -- ufix1
  SIGNAL dataOut_re_lastAddr              : std_logic;  -- ufix1
  SIGNAL check1_done                      : std_logic;  -- ufix1
  SIGNAL dataOut_re_signed                : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL dataOut_re_addr_delay_1          : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL dataOut_re_expected              : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL dataOut_re_ref                   : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL dataOut_re_testFailure           : std_logic;  -- ufix1
  SIGNAL dataOut_im_signed                : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL dataOut_im_expected_1            : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL dataOut_im_ref                   : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL dataOut_im_testFailure           : std_logic;  -- ufix1
  SIGNAL validOut_addr_delay_1            : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL validOut_expected                : std_logic;
  SIGNAL validOut_ref                     : std_logic;
  SIGNAL validOut_testFailure             : std_logic;  -- ufix1
  SIGNAL testFailure                      : std_logic;  -- ufix1

BEGIN
  u_fft8_dut : fft8_dut
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              dataIn => dataIn_1,  -- int16
              validIn => validIn_1,
              ce_out => ce_out,
              dataOut_re => dataOut_re,  -- sfix19
              dataOut_im => dataOut_im,  -- sfix19
              validOut => validOut
              );

  -- Data source for validIn
  rawData_validIn <= '1';

  validOut_done_enb <= validOut_done AND rdEnb;

  
  validOut_lastAddr <= '1' WHEN dataOut_re_addr >= to_unsigned(16#96#, 8) ELSE
      '0';

  validOut_done <= validOut_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_2_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check2_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF validOut_done_enb = '1' THEN
        check2_done <= validOut_done;
      END IF;
    END IF;
  END PROCESS checkDone_2_process;

  dataOut_re_done_enb <= dataOut_re_done AND rdEnb;

  
  dataOut_re_active <= '1' WHEN dataOut_re_addr /= to_unsigned(16#96#, 8) ELSE
      '0';

  -- holdData reg for validIn
  stimuli_validIn_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_validIn <= 'X';
    ELSIF clk'event AND clk = '1' THEN
      holdData_validIn <= rawData_validIn;
    END IF;
  END PROCESS stimuli_validIn_process;

  stimuli_validIn_1: PROCESS (rawData_validIn, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      validIn_offset <= holdData_validIn;
    ELSE
      validIn_offset <= rawData_validIn;
    END IF;
  END PROCESS stimuli_validIn_1;

  validIn_1 <= validIn_offset AFTER 2 ns;

  
  dataIn_active <= '1' WHEN dataIn_addr /= to_unsigned(16#96#, 8) ELSE
      '0';

  dataIn_enb <= dataIn_active AND (rdEnb AND tb_enb_delay);

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 150
  toFix_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dataIn_addr <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF dataIn_enb = '1' THEN
        IF dataIn_addr >= to_unsigned(16#96#, 8) THEN 
          dataIn_addr <= to_unsigned(16#00#, 8);
        ELSE 
          dataIn_addr <= dataIn_addr + to_unsigned(16#01#, 8);
        END IF;
      END IF;
    END IF;
  END PROCESS toFix_process;


  dataIn_addr_delay_1 <= dataIn_addr AFTER 1 ns;

  -- Data source for dataIn
  dataIn_fileread: PROCESS (dataIn_addr_delay_1, tb_enb_delay, rdEnb)
    FILE fp: TEXT open READ_MODE is "dataIn.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(15 DOWNTO 0);

  BEGIN
    IF tb_enb_delay /= '1' THEN
      IF snkDone = '1' THEN
        file_close(fp);
      END IF;
    ELSIF rdEnb = '1' AND NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    rawData_dataIn <= signed(read_data(15 DOWNTO 0));
  END PROCESS dataIn_fileread;

  -- holdData reg for dataIn
  stimuli_dataIn_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_dataIn <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_dataIn <= rawData_dataIn;
    END IF;
  END PROCESS stimuli_dataIn_process;

  stimuli_dataIn_1: PROCESS (rawData_dataIn, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      dataIn_offset <= holdData_dataIn;
    ELSE
      dataIn_offset <= rawData_dataIn;
    END IF;
  END PROCESS stimuli_dataIn_1;

  dataIn <= dataIn_offset AFTER 2 ns;

  dataIn_1 <= std_logic_vector(dataIn);

  snkDonen <=  NOT snkDone;

  resetn <=  NOT reset;

  tb_enb <= resetn AND snkDonen;

  -- Delay inside enable generation: register depth 1
  u_enable_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tb_enb_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      tb_enb_delay <= tb_enb;
    END IF;
  END PROCESS u_enable_delay_process;


  
  rdEnb <= tb_enb_delay WHEN snkDone = '0' ELSE
      '0';

  clk_enable <= rdEnb AFTER 2 ns;

  reset_gen: PROCESS 
  BEGIN
    reset <= '1';
    WAIT FOR 20 ns;
    WAIT UNTIL clk'event AND clk = '1';
    WAIT FOR 2 ns;
    reset <= '0';
    WAIT;
  END PROCESS reset_gen;

  clk_gen: PROCESS 
  BEGIN
    clk <= '1';
    WAIT FOR 5 ns;
    clk <= '0';
    WAIT FOR 5 ns;
    IF snkDone = '1' THEN
      clk <= '1';
      WAIT FOR 5 ns;
      clk <= '0';
      WAIT FOR 5 ns;
      WAIT;
    END IF;
  END PROCESS clk_gen;

  dataOut_re_enb <= ce_out AND dataOut_re_active;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 150
  c_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dataOut_re_addr <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF dataOut_re_enb = '1' THEN
        IF dataOut_re_addr >= to_unsigned(16#96#, 8) THEN 
          dataOut_re_addr <= to_unsigned(16#00#, 8);
        ELSE 
          dataOut_re_addr <= dataOut_re_addr + to_unsigned(16#01#, 8);
        END IF;
      END IF;
    END IF;
  END PROCESS c_3_process;


  
  dataOut_re_lastAddr <= '1' WHEN dataOut_re_addr >= to_unsigned(16#96#, 8) ELSE
      '0';

  dataOut_re_done <= dataOut_re_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check1_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF dataOut_re_done_enb = '1' THEN
        check1_done <= dataOut_re_done;
      END IF;
    END IF;
  END PROCESS checkDone_1_process;

  snkDone <= check1_done AND check2_done;

  dataOut_re_signed <= signed(dataOut_re);

  dataOut_re_addr_delay_1 <= dataOut_re_addr AFTER 1 ns;

  -- Data source for dataOut_re_expected
  dataOut_re_expected_fileread: PROCESS (dataOut_re_addr_delay_1, tb_enb_delay, ce_out)
    FILE fp: TEXT open READ_MODE is "dataOut_re_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(19 DOWNTO 0);

  BEGIN
    IF tb_enb_delay /= '1' THEN
      IF snkDone = '1' THEN
        file_close(fp);
      END IF;
    ELSIF ce_out = '1' AND NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    dataOut_re_expected <= signed(read_data(18 DOWNTO 0));
  END PROCESS dataOut_re_expected_fileread;

  dataOut_re_ref <= dataOut_re_expected;

  dataOut_re_signed_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dataOut_re_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND dataOut_re_signed /= dataOut_re_ref THEN
        dataOut_re_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in dataOut_re_signed: Expected " & to_hex(dataOut_re_ref) & (" Actual " & to_hex(dataOut_re_signed))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS dataOut_re_signed_checker;

  dataOut_im_signed <= signed(dataOut_im);

  -- Data source for dataOut_im_expected
  dataOut_im_expected_1 <= to_signed(16#00000#, 19);

  dataOut_im_ref <= dataOut_im_expected_1;

  dataOut_im_signed_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dataOut_im_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND dataOut_im_signed /= dataOut_im_ref THEN
        dataOut_im_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in dataOut_im_signed: Expected " & to_hex(dataOut_im_ref) & (" Actual " & to_hex(dataOut_im_signed))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS dataOut_im_signed_checker;

  validOut_addr_delay_1 <= dataOut_re_addr AFTER 1 ns;

  -- Data source for validOut_expected
  validOut_expected_fileread: PROCESS (validOut_addr_delay_1, tb_enb_delay, ce_out)
    FILE fp: TEXT open READ_MODE is "validOut_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic;

  BEGIN
    IF tb_enb_delay /= '1' THEN
      IF snkDone = '1' THEN
        file_close(fp);
      END IF;
    ELSIF ce_out = '1' AND NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      READ(l, read_data);
    END IF;
    validOut_expected <= read_data;
  END PROCESS validOut_expected_fileread;

  validOut_ref <= validOut_expected;

  validOut_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validOut_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND validOut /= validOut_ref THEN
        validOut_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in validOut: Expected " & to_hex(validOut_ref) & (" Actual " & to_hex(validOut))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS validOut_checker;

  testFailure <= validOut_testFailure OR (dataOut_re_testFailure OR dataOut_im_testFailure);

  completed_msg: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF snkDone = '1' THEN
        IF testFailure = '0' THEN
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (PASSED)**************"
            SEVERITY NOTE;
        ELSE
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (FAILED)**************"
            SEVERITY NOTE;
        END IF;
      END IF;
    END IF;
  END PROCESS completed_msg;

END rtl;

