-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\flash_led\flash_led_ctl.vhd
-- Created: 2026-07-13 10:19:36
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: flash_led_ctl
-- Source Path: flash_led/flash_led_top/flash_led_ctl
-- Hierarchy Level: 1
-- Model version: 1.10
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY flash_led_ctl IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        tick                              :   IN    std_logic;
        led                               :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END flash_led_ctl;


ARCHITECTURE rtl OF flash_led_ctl IS

  -- Signals
  SIGNAL pattern_reg_out1                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL rotate_left_out1                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL update_out1                      : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  rotate_left_out1 <= pattern_reg_out1 rol 1;

  
  update_out1 <= pattern_reg_out1 WHEN tick = '0' ELSE
      rotate_left_out1;

  pattern_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      pattern_reg_out1 <= to_unsigned(16#01#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      pattern_reg_out1 <= update_out1;
    END IF;
  END PROCESS pattern_reg_process;


  led <= std_logic_vector(pattern_reg_out1);

END rtl;

