open_system('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter/pwm/Counter Free-Running', 'user2');
annotate_port('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter/pwm/Counter Free-Running', 0, 1, 'cp : 0.812 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter/pwm/Add1_stage2', 'user2');
annotate_port('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter/pwm/Add1_stage2', 0, 1, 'cp : 2.628 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter/pwm/Add1_stage3', 'user2');
annotate_port('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter/pwm/Add1_stage3', 0, 1, 'cp : 4.561 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter/pwm/Data Type Conversion6', 'user2');
annotate_port('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter/pwm/Data Type Conversion6', 0, 1, 'cp : 0.812 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter/pwm/Switch4', 'user2');
annotate_port('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter/pwm/Switch4', 0, 1, 'cp : 5.777 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter/pwm/delayMatch', 'user1');
annotate_port('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter/pwm/delayMatch', 1, 1, 'cp : 6.111 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter/pwm/Counter Free-Running/Output', 'user1');
annotate_port('gm_optimized_timing_multi_module_phase_shift_generator_built_in_counter/pwm/Counter Free-Running/Output', 0, 1, 'cp : 0.812 ns');
