function gs_soc_dvbs2_top_setup(hFPGA)
%--------------------------------------------------------------------------
% Host Interface Script Setup
% 
% Generated with MATLAB 25.2 (R2025b) at 17:44:08 on 27/10/2025.
% This function was created for the IP Core generated from design 'soc_dvbs2_top'.
% 
% Run this function on an "fpga" object to configure it with the same interfaces as the generated IP core.
%--------------------------------------------------------------------------

%% DVBS2 Register Interface
addAXI4SlaveInterface(hFPGA, ...
	"InterfaceID", "DVBS2Register", ...
	"BaseAddress", 0xA0000000, ...
	"AddressRange", 0x10000, ...
	"WriteDeviceName", "mwdvbs2_ip0:mmwr0", ...
	"ReadDeviceName", "mwdvbs2_ip0:mmrd0");

h_adc_dac_loopback = hdlcoder.DUTPort("adc_dac_loopback", ...
	"Direction", "IN", ...
	"IsComplex", false, ...
	"DataType", "logical", ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x0128");

h_enbNoise = hdlcoder.DUTPort("enbNoise", ...
	"Direction", "IN", ...
	"IsComplex", false, ...
	"DataType", "logical", ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x012C");

h_snrdB = hdlcoder.DUTPort("snrdB", ...
	"Direction", "IN", ...
	"IsComplex", false, ...
	"DataType", numerictype(1,16,9), ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x0130");

h_CFO = hdlcoder.DUTPort("CFO", ...
	"Direction", "IN", ...
	"IsComplex", false, ...
	"DataType", numerictype(1,21,21), ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x0134");

h_CPO = hdlcoder.DUTPort("CPO", ...
	"Direction", "IN", ...
	"IsComplex", false, ...
	"DataType", numerictype(1,21,21), ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x0138");

h_modcodIdx = hdlcoder.DUTPort("modcodIdx", ...
	"Direction", "IN", ...
	"IsComplex", false, ...
	"DataType", numerictype(0,5,0), ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x013C");

h_resetFCPO = hdlcoder.DUTPort("resetFCPO", ...
	"Direction", "IN", ...
	"IsComplex", false, ...
	"DataType", "logical", ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x0140");

h_resetDisplay = hdlcoder.DUTPort("resetDisplay", ...
	"Direction", "IN", ...
	"IsComplex", false, ...
	"DataType", "logical", ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x0144");

h_nframesSynced = hdlcoder.DUTPort("nframesSynced", ...
	"Direction", "OUT", ...
	"IsComplex", false, ...
	"DataType", "uint32", ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x0100");

h_decodedModcod = hdlcoder.DUTPort("decodedModcod", ...
	"Direction", "OUT", ...
	"IsComplex", false, ...
	"DataType", numerictype(0,5,0), ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x0104");

h_decodedFecFrame = hdlcoder.DUTPort("decodedFecFrame", ...
	"Direction", "OUT", ...
	"IsComplex", false, ...
	"DataType", numerictype(0,1,0), ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x0108");

h_FreqEst = hdlcoder.DUTPort("FreqEst", ...
	"Direction", "OUT", ...
	"IsComplex", false, ...
	"DataType", numerictype(1,21,21), ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x010C");

h_TSorGS = hdlcoder.DUTPort("TSorGS", ...
	"Direction", "OUT", ...
	"IsComplex", false, ...
	"DataType", numerictype(0,2,0), ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x0110");

h_UPL = hdlcoder.DUTPort("UPL", ...
	"Direction", "OUT", ...
	"IsComplex", false, ...
	"DataType", "uint16", ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x0114");

h_DFL = hdlcoder.DUTPort("DFL", ...
	"Direction", "OUT", ...
	"IsComplex", false, ...
	"DataType", "uint16", ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x0118");

h_SYNC = hdlcoder.DUTPort("SYNC", ...
	"Direction", "OUT", ...
	"IsComplex", false, ...
	"DataType", "uint8", ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x011C");

h_nbitsReceived = hdlcoder.DUTPort("nbitsReceived", ...
	"Direction", "OUT", ...
	"IsComplex", false, ...
	"DataType", "uint32", ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x0124");

h_nbitsErrored = hdlcoder.DUTPort("nbitsErrored", ...
	"Direction", "OUT", ...
	"IsComplex", false, ...
	"DataType", "uint32", ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2Register", ...
	"IOInterfaceMapping", "0x0120");

mapPort(hFPGA, [h_adc_dac_loopback, h_enbNoise, h_snrdB, h_CFO, h_CPO, h_modcodIdx, h_resetFCPO, h_resetDisplay, h_nframesSynced, h_decodedModcod, h_decodedFecFrame, h_FreqEst, h_TSorGS, h_UPL, h_DFL, h_SYNC, h_nbitsReceived, h_nbitsErrored]);

%% DVBS2 Stream Interface
addAXI4StreamInterface(hFPGA, ...
	"InterfaceID", "DVBS2StreamRead0", ...
	"WriteEnable", false, ...
	"ReadEnable", true, ...
	"ReadDeviceName", "mwdvbs2_ip0:s2mm0", ...
	"ReadFrameLength", 2048, ...
	"ReadDataWidth", 32);

h_data_DVBS2StreamRead0 = hdlcoder.DUTPort("data_DVBS2StreamRead0", ...
	"Direction", "OUT", ...
	"IsComplex", false, ...
	"DataType", "uint32", ...
	"Dimension", [1 1], ...
	"IOInterface", "DVBS2StreamRead0");

mapPort(hFPGA, h_data_DVBS2StreamRead0);

end
