#ifndef PORTABLE_WORDSIZES
#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__

#define MW_MULTI_TASKING_MODE 0

#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE Xilinx Zynq UltraScale+ RFSoC ZCU111 Evaluation Kit
#define MW_CONNECTIONINFO_TCPIP_IPADDRESS soc.sdk.internal.getIPAddress(hCS)
#define MW_CONNECTIONINFO_TCPIP_PORT 17725
#define MW_CONNECTIONINFO_TCPIP_VERBOSE 0
#define MW_CONNECTIONINFO_TCPIP_RUNINBACKGROUND 1
#define MW_CONNECTIONINFO_XCPONTCPIP_IPADDRESS 192.168.1.101
#define MW_CONNECTIONINFO_XCPONTCPIP_PORT 17725
#define MW_CONNECTIONINFO_XCPONTCPIP_VERBOSE 0
#define MW_EXTMODE_CONFIGURATION TCP/IP
#define MW_EXTMODE_RUNNING on
#define MW_TARGETSERVICES_RUNNING 1
#define MW_ESB_SIMDIAGSHOWINSDI 1
#define MW_ESB_SIMDIAGSAVETOFILE 0
#define MW_ESB_SIMDIAGOVERWRITEFILE 0
#define MW_ESB_HWDIAGSHOWINSDI 1
#define MW_ESB_HWDIAGSAVETOFILE 0
#define MW_ESB_HWDIAGOVERWRITEFILE 0
#define MW_ESB_HWDIAGINSTRUMENTATION Code
#define MW_ESB_HWDIAGRECORDING Continuous
#define MW_ESB_HWDIAGSTREAMINGMODETYPE Unlimited
#define MW_ESB_HWDIAGBUFFERSIZE 1024.000000
#define MW_ESB_HWDIAGNUMBUFFERS 1.000000
#define MW_ESB_HWDIAGVIEWLEVEL Task manager tasks
#define MW_ESB_SETRNG 0
#define MW_ESB_RNGSEED default
#define MW_ESB_CACHEDATA 0
#define MW_ESB_PROCESSINGUNIT APU
#define MW_ESB_SCHEDULEEDITORSCHEDULERESET 0
#define MW_RTOS Linux
#define MW_RTOSBASERATETASKPRIORITY 40
#define MW_OS_KERNELLATENCY 0.000000
#define MW_OS_TASKCONTEXTSAVETIME 0.000000
#define MW_OS_TASKCONTEXTRESTORETIME 0.000000
#define MW_SCHEDULER_INTERRUPT_SOURCE 0
#define MW_BOARDPARAMETERS_DEVICEADDRESS 192.168.1.101
#define MW_BOARDPARAMETERS_USERNAME root
#define MW_BOARDPARAMETERS_PASSWORD root
#define MW_RUNTIME_BUILDACTION 2
#define MW_CLOCKING_CPUCLOCKRATEMHZ 1000
#define MW_FPGADESIGNMEMMAPBUTTON 
#define MW_FPGADESIGN_INCLUDEJTAGMASTER 1
#define MW_FPGADESIGN_INCLUDEPROCESSINGSYSTEM 1
#define MW_FPGADESIGN_INTERRUPTLATENCY 0.000000
#define MW_FPGADESIGN_AXILITECLOCK 50.000000
#define MW_FPGADESIGN_AXIHDLUSERLOGICCLOCK 100.000000
#define MW_FPGADESIGN_MEMCHDIAGLEVEL 0
#define MW_FPGADESIGN_INCLUDEAXIINTERCONNECTMONITOR 0
#define MW_FPGADESIGN_NUMBEROFTRACEEVENTS 1024.000000
#define MW_FPGADESIGN_AXIMEMORYSUBSYSTEMCLOCKPS 300.000000
#define MW_FPGADESIGN_AXIMEMORYSUBSYSTEMDATAWIDTHPS 4
#define MW_FPGADESIGN_REFRESHOVERHEADPS 2.300000
#define MW_FPGADESIGN_WRITEFIRSTTRANSFERLATENCYPS 30.000000
#define MW_FPGADESIGN_WRITELASTTRANSFERLATENCYPS 30.000000
#define MW_FPGADESIGN_READFIRSTTRANSFERLATENCYPS 30.000000
#define MW_FPGADESIGN_READLASTTRANSFERLATENCYPS 30.000000
#define MW_FPGADESIGN_HASPSMEMORY 1
#define MW_FPGADESIGN_HASPLMEMORY 1
#define MW_FPGADESIGN_PROJECTFOLDER soc_prj
#define MW_FPGADESIGN_AXIMEMORYSUBSYSTEMCLOCKPL 300.000000
#define MW_FPGADESIGN_AXIMEMORYSUBSYSTEMDATAWIDTHPL 6
#define MW_FPGADESIGN_REFRESHOVERHEADPL 2.300000
#define MW_FPGADESIGN_WRITEFIRSTTRANSFERLATENCYPL 5.000000
#define MW_FPGADESIGN_WRITELASTTRANSFERLATENCYPL 5.000000
#define MW_FPGADESIGN_READFIRSTTRANSFERLATENCYPL 5.000000
#define MW_FPGADESIGN_READLASTTRANSFERLATENCYPL 5.000000
#define MW_DATAVERSION 2016.02
#define MW_FPGADESIGNPROJECTFOLDERBROWSE 

#endif /* __MW_TARGET_HARDWARE_RESOURCES_H__ */

#endif

#endif
