ASFLAGS_ADDITIONAL = 
TARGET_SYSROOT = C:/PROGRA~3/MATLAB/SUPPOR~1/R2025b/3P778C~1.INS/XILINX~2.INS/SYSROO~1
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/R2025b/toolbox/soc/SUPPOR~1/rfsoc
STACK_SIZE = 64
