open_system('gm_multi_module_phase_shift_generator_built_in_counter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_built_in_counter/Subsystem/Counter Free-Running', 'user2');
annotate_port('gm_multi_module_phase_shift_generator_built_in_counter/Subsystem/Counter Free-Running', 0, 1, 'cp : 0.812 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_built_in_counter/Subsystem/Add2_stage2', 'user2');
annotate_port('gm_multi_module_phase_shift_generator_built_in_counter/Subsystem/Add2_stage2', 0, 1, 'cp : 2.628 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_built_in_counter/Subsystem/Add2_stage3', 'user2');
annotate_port('gm_multi_module_phase_shift_generator_built_in_counter/Subsystem/Add2_stage3', 0, 1, 'cp : 4.561 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_built_in_counter/Subsystem/Data Type Conversion7', 'user2');
annotate_port('gm_multi_module_phase_shift_generator_built_in_counter/Subsystem/Data Type Conversion7', 0, 1, 'cp : 0.812 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_built_in_counter/Subsystem/Relational Operator1', 'user1');
annotate_port('gm_multi_module_phase_shift_generator_built_in_counter/Subsystem/Relational Operator1', 0, 1, 'cp : 7.798 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_built_in_counter/Subsystem/Switch1', 'user2');
annotate_port('gm_multi_module_phase_shift_generator_built_in_counter/Subsystem/Switch1', 0, 1, 'cp : 5.777 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_built_in_counter/Subsystem/Counter Free-Running/Output', 'user1');
annotate_port('gm_multi_module_phase_shift_generator_built_in_counter/Subsystem/Counter Free-Running/Output', 0, 1, 'cp : 0.812 ns');
