function findings = vpcEvaluateCriteria(ts, m, cfg)
%VPCEVALUATECRITERIA Score voyage results against the certification rule set.
%
%   findings = VPCEVALUATECRITERIA(ts, m, cfg) returns a struct array with one
%   element per rule. Each element has:
%       id, title, status ('PASS'|'WARN'|'FAIL'), measured, limit, detail
%
%   The rules are a plausible surveyor's check list for a hybrid electric vessel,
%   not a transcription of any particular class society's notation. They are kept
%   in one place so the demo can be re-pointed at a real rule set without touching
%   the model or the app.
%
%   See also vpcRunCertification.

L = cfg.limits;
f = {};

% ---- 1. installed capacity must cover peak demand -----------------------
f{end+1} = rule('CAP-01', 'Installed generating capacity covers peak demand', ...
    m.peakGenDemand_kW <= m.installedCap_kW, [], ...
    sprintf('%.0f kW', m.peakGenDemand_kW), ...
    sprintf('<= %.0f kW installed', m.installedCap_kW), ...
    sprintf('Capacity margin %.1f%%.', 100*m.capacityMargin));

% ---- 2. N-1 redundancy --------------------------------------------------
f{end+1} = rule('RED-01', 'N-1 redundancy: largest set can trip without shortfall', ...
    m.nMinus1MaxDeficit_kW <= 0, [], ...
    sprintf('%.0f kW shortfall', m.nMinus1MaxDeficit_kW), ...
    '0 kW shortfall', ...
    'Worst-case loss of the largest running generator, at every point in the profile.');

% ---- 3. spinning reserve ------------------------------------------------
if m.essReserveCredit_kW > 0
    reserveDetail = sprintf(['Generators alone provide %.1f%%; the store adds up to ' ...
        '%.0f kW of instantly available reserve.'], ...
        100*m.spinReserveGenOnly, m.essReserveCredit_kW);
else
    reserveDetail = sprintf(['Generators alone provide %.1f%%, with no energy store ' ...
        'to catch a load step. Reserve must come from idling machinery.'], ...
        100*m.spinReserveGenOnly);
end
f{end+1} = rule('RED-02', 'Spinning reserve available to catch a load step', ...
    m.spinReserveMin >= L.spinReserveMin, ...
    m.spinReserveMin >= 0.8*L.spinReserveMin, ...
    sprintf('%.1f%%', 100*m.spinReserveMin), ...
    sprintf('>= %.0f%%', 100*L.spinReserveMin), ...
    reserveDetail);

% ---- 4. generator load band --------------------------------------------
f{end+1} = rule('GEN-01', 'Generator loading kept inside its permitted band', ...
    m.loadOutOfBandFrac <= L.lowLoadDwellMax_frac, ...
    m.loadOutOfBandFrac <= 2*L.lowLoadDwellMax_frac, ...
    sprintf('%.1f%% of voyage', 100*m.loadOutOfBandFrac), ...
    sprintf('<= %.0f%% outside %.0f-%.0f%%', 100*L.lowLoadDwellMax_frac, ...
            100*L.genLoadMin, 100*L.genLoadMax), ...
    sprintf('Mean loading %.0f%%, peak %.0f%%. Sustained low load causes fouling.', ...
            100*m.genLoadMean, 100*m.genLoadMax));

% ---- 5. energy storage state of charge ---------------------------------
if cfg.variants.energyStorage == 1
    f{end+1} = rule('ESS-01', 'Energy storage state of charge within limits', ...
        true, [], 'not fitted', 'n/a', ...
        'No energy storage in this configuration, so the rule does not apply.');
else
    okSoc = m.socMin >= L.socMin && m.socMax <= L.socMax;
    f{end+1} = rule('ESS-01', 'Energy storage state of charge within limits', ...
        okSoc, m.socMin >= 0.9*L.socMin && m.socMax <= 1.02*L.socMax, ...
        sprintf('%.0f%% - %.0f%%', 100*m.socMin, 100*m.socMax), ...
        sprintf('%.0f%% - %.0f%%', 100*L.socMin, 100*L.socMax), ...
        sprintf('Throughput %.0f kWh over the voyage.', m.essThroughput_kWh));
end

% ---- 6. harbour emissions ----------------------------------------------
if L.harbourEmissionsZero
    okHarbour = m.harbourFuel_t <= 1e-3;
    f{end+1} = rule('EMI-01', 'Zero emissions alongside (cold ironing)', ...
        okHarbour, m.harbourFuel_t <= 0.25, ...
        sprintf('%.2f t fuel in port', m.harbourFuel_t), ...
        '0.00 t', ...
        'Fuel burned onboard while in harbour mode.');
end

% ---- 7. fuel budget ----------------------------------------------------
f{end+1} = rule('FUE-01', 'Voyage fuel within budget', ...
    m.fuelTotal_t <= L.fuelBudget_t, ...
    m.fuelTotal_t <= 1.05*L.fuelBudget_t, ...
    sprintf('%.2f t', m.fuelTotal_t), ...
    sprintf('<= %.2f t', L.fuelBudget_t), ...
    sprintf('Main engine %.2f t, generators %.2f t. Cost approx USD %s.', ...
            m.fuelME_t, m.fuelGen_t, ...
            vpcThousands(m.fuelCost_USD)));

% ---- 8. carbon intensity ----------------------------------------------
okCii = m.co2Intensity_gptnm <= L.co2Intensity_max;
f{end+1} = rule('EMI-02', 'Carbon intensity within required band', ...
    okCii, m.co2Intensity_gptnm <= 1.10*L.co2Intensity_max, ...
    sprintf('%.2f g/t-nm', m.co2Intensity_gptnm), ...
    sprintf('<= %.2f g/t-nm', L.co2Intensity_max), ...
    sprintf('Total %.1f t CO2 over %.0f nm. Indicative rating %s.', ...
            m.co2_t, m.distance_nm, vpcCiiBand(m.co2Intensity_gptnm, L.co2Intensity_max)));

findings = [f{:}];
end

% =========================================================================
function s = rule(id, title, passCond, warnCond, measured, limit, detail)
%RULE Build one finding. warnCond may be [] when there is no intermediate state.
s.id       = id;
s.title    = title;
s.measured = measured;
s.limit    = limit;
s.detail   = detail;

if passCond
    s.status = 'PASS';
elseif ~isempty(warnCond) && warnCond
    s.status = 'WARN';
else
    s.status = 'FAIL';
end
end

% =========================================================================
function b = vpcCiiBand(value, limit)
%VPCCIIBAND Map a carbon intensity onto an A-E band around the required limit.
r = value / max(limit, eps);
if     r <= 0.80; b = 'A';
elseif r <= 0.94; b = 'B';
elseif r <= 1.00; b = 'C';
elseif r <= 1.15; b = 'D';
else              b = 'E';
end
end

% =========================================================================
function s = vpcThousands(v)
%VPCTHOUSANDS Format a number with thousands separators.
s = regexprep(sprintf('%.0f',v), '(\d)(?=(\d{3})+$)', '$1,');
end
