-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_AposterioriUnit.vhd
-- Created: 2025-10-27 18:12:27
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_AposterioriUnit
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/FEC Decoding/DVB-S2 
-- LDPC Decoder/DecoderCore/MetricCalculator/FunctionalUnit/AposterioriUni
-- Hierarchy Level: 9
-- Model version: 9.0
-- 
-- Aposteriori Node Unit
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_AposterioriUnit IS
  PORT( alpha                             :   IN    vector_of_std_logic_vector11(0 TO 44);  -- sfix11_En4 [45]
        beta                              :   IN    vector_of_std_logic_vector9(0 TO 44);  -- sfix9_En4 [45]
        valid                             :   IN    std_logic;  -- ufix1
        gamma                             :   OUT   vector_of_std_logic_vector11(0 TO 44);  -- sfix11_En4 [45]
        valid_1                           :   OUT   std_logic  -- ufix1
        );
END dvbs2_ip_src_AposterioriUnit;


ARCHITECTURE rtl OF dvbs2_ip_src_AposterioriUnit IS

  -- Signals
  SIGNAL alpha_signed                     : vector_of_signed11(0 TO 44);  -- sfix11_En4 [45]
  SIGNAL beta_signed                      : vector_of_signed9(0 TO 44);  -- sfix9_En4 [45]
  SIGNAL add_Comp_add_cast                : vector_of_signed12(0 TO 44);  -- sfix12_En4 [45]
  SIGNAL add_Comp_add_cast_1              : vector_of_signed11(0 TO 44);  -- sfix11_En4 [45]
  SIGNAL add_Comp_add_cast_2              : vector_of_signed12(0 TO 44);  -- sfix12_En4 [45]
  SIGNAL add_Comp_add_temp                : vector_of_signed12(0 TO 44);  -- sfix12_En4 [45]
  SIGNAL add                              : vector_of_signed11(0 TO 44);  -- sfix11_En4 [45]

BEGIN
  outputgen2: FOR k IN 0 TO 44 GENERATE
    alpha_signed(k) <= signed(alpha(k));
  END GENERATE;

  outputgen1: FOR k IN 0 TO 44 GENERATE
    beta_signed(k) <= signed(beta(k));
  END GENERATE;


  add_gen: FOR t_0 IN 0 TO 44 GENERATE
    add_Comp_add_cast(t_0) <= resize(alpha_signed(t_0), 12);
    add_Comp_add_cast_1(t_0) <= resize(beta_signed(t_0), 11);
    add_Comp_add_cast_2(t_0) <= resize(add_Comp_add_cast_1(t_0), 12);
    add_Comp_add_temp(t_0) <= add_Comp_add_cast(t_0) + add_Comp_add_cast_2(t_0);
    
    add(t_0) <= "01111111111" WHEN (add_Comp_add_temp(t_0)(11) = '0') AND (add_Comp_add_temp(t_0)(10) /= '0') ELSE
        "10000000000" WHEN (add_Comp_add_temp(t_0)(11) = '1') AND (add_Comp_add_temp(t_0)(10) /= '1') ELSE
        add_Comp_add_temp(t_0)(10 DOWNTO 0);
  END GENERATE add_gen;


  outputgen: FOR k IN 0 TO 44 GENERATE
    gamma(k) <= std_logic_vector(add(k));
  END GENERATE;

  valid_1 <= valid;

END rtl;

