-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_SinCos.vhd
-- Created: 2025-10-27 18:12:26
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_SinCos
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SinCos
-- Hierarchy Level: 5
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dvbs2_ip_src_SinCos IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_8_0                         :   IN    std_logic;
        u1                                :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        g0                                :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        g1_16_15                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END dvbs2_ip_src_SinCos;


ARCHITECTURE rtl OF dvbs2_ip_src_SinCos IS

  -- Component Declarations
  COMPONENT dvbs2_ip_src_Sine_HDL_Optimized2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_8_0                       :   IN    std_logic;
          u                               :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          x                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_Sine_HDL_Optimized1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_8_0                       :   IN    std_logic;
          u                               :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          x                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dvbs2_ip_src_Sine_HDL_Optimized2
    USE ENTITY work.dvbs2_ip_src_Sine_HDL_Optimized2(rtl);

  FOR ALL : dvbs2_ip_src_Sine_HDL_Optimized1
    USE ENTITY work.dvbs2_ip_src_Sine_HDL_Optimized1(rtl);

  -- Signals
  SIGNAL u1_unsigned                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL u1_1                             : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL g0_1                             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL g0_signed                        : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Delay_out1                       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL g1_16_15_1                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL g1_16_15_signed                  : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Delay1_out1                      : signed(15 DOWNTO 0);  -- sfix16_En15

BEGIN
  u_Sine_HDL_Optimized2 : dvbs2_ip_src_Sine_HDL_Optimized2
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_8_0 => enb_1_8_0,
              u => std_logic_vector(u1_1),  -- ufix16_En16
              x => g0_1  -- sfix16_En15
              );

  u_Sine_HDL_Optimized1 : dvbs2_ip_src_Sine_HDL_Optimized1
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_8_0 => enb_1_8_0,
              u => std_logic_vector(u1_1),  -- ufix16_En16
              x => g1_16_15_1  -- sfix16_En15
              );

  u1_unsigned <= unsigned(u1);

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        u1_1 <= to_unsigned(16#0000#, 16);
      ELSIF enb_1_8_0 = '1' THEN
        u1_1 <= u1_unsigned;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  g0_signed <= signed(g0_1);

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_out1 <= to_signed(16#0000#, 16);
      ELSIF enb_1_8_0 = '1' THEN
        Delay_out1 <= g0_signed;
      END IF;
    END IF;
  END PROCESS Delay_process;


  g0 <= std_logic_vector(Delay_out1);

  g1_16_15_signed <= signed(g1_16_15_1);

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out1 <= to_signed(16#0000#, 16);
      ELSIF enb_1_8_0 = '1' THEN
        Delay1_out1 <= g1_16_15_signed;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  g1_16_15 <= std_logic_vector(Delay1_out1);

END rtl;

