-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_FunctionEvaluation.vhd
-- Created: 2025-10-27 18:12:26
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_FunctionEvaluation
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation
-- Hierarchy Level: 7
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_FunctionEvaluation IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_8_0                         :   IN    std_logic;
        x_f                               :   IN    std_logic_vector(30 DOWNTO 0);  -- ufix31_En24
        passIn                            :   IN    std_logic_vector(8 DOWNTO 0);  -- sfix9
        exp_fIn                           :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        y_f                               :   OUT   std_logic_vector(16 DOWNTO 0);  -- ufix17_En13
        passOut                           :   OUT   std_logic_vector(8 DOWNTO 0);  -- sfix9
        exp_fOut                          :   OUT   std_logic_vector(7 DOWNTO 0)  -- int8
        );
END dvbs2_ip_src_FunctionEvaluation;


ARCHITECTURE rtl OF dvbs2_ip_src_FunctionEvaluation IS

  -- Constants
  CONSTANT alpha1_D_Lookup_Table2_data    : vector_of_signed13(0 TO 64) := 
    (to_signed(16#05A3#, 13), to_signed(16#0597#, 13), to_signed(16#058D#, 13), to_signed(16#0582#, 13),
     to_signed(16#0578#, 13), to_signed(16#056E#, 13), to_signed(16#0564#, 13), to_signed(16#055A#, 13),
     to_signed(16#0551#, 13), to_signed(16#0547#, 13), to_signed(16#053E#, 13), to_signed(16#0535#, 13),
     to_signed(16#052D#, 13), to_signed(16#0524#, 13), to_signed(16#051C#, 13), to_signed(16#0513#, 13),
     to_signed(16#050B#, 13), to_signed(16#0503#, 13), to_signed(16#04FB#, 13), to_signed(16#04F4#, 13),
     to_signed(16#04EC#, 13), to_signed(16#04E5#, 13), to_signed(16#04DE#, 13), to_signed(16#04D7#, 13),
     to_signed(16#04CF#, 13), to_signed(16#04C9#, 13), to_signed(16#04C2#, 13), to_signed(16#04BB#, 13),
     to_signed(16#04B5#, 13), to_signed(16#04AE#, 13), to_signed(16#04A8#, 13), to_signed(16#04A2#, 13),
     to_signed(16#049B#, 13), to_signed(16#0495#, 13), to_signed(16#048F#, 13), to_signed(16#0489#, 13),
     to_signed(16#0484#, 13), to_signed(16#047E#, 13), to_signed(16#0478#, 13), to_signed(16#0473#, 13),
     to_signed(16#046D#, 13), to_signed(16#0468#, 13), to_signed(16#0463#, 13), to_signed(16#045D#, 13),
     to_signed(16#0458#, 13), to_signed(16#0453#, 13), to_signed(16#044E#, 13), to_signed(16#0449#, 13),
     to_signed(16#0444#, 13), to_signed(16#043F#, 13), to_signed(16#043B#, 13), to_signed(16#0436#, 13),
     to_signed(16#0431#, 13), to_signed(16#042D#, 13), to_signed(16#0428#, 13), to_signed(16#0424#, 13),
     to_signed(16#041F#, 13), to_signed(16#041B#, 13), to_signed(16#0417#, 13), to_signed(16#0412#, 13),
     to_signed(16#040E#, 13), to_signed(16#040A#, 13), to_signed(16#0406#, 13), to_signed(16#0402#, 13),
     to_signed(16#0000#, 13));  -- sfix13 [65]
  CONSTANT alpha1_D_Lookup_Table3_data    : vector_of_signed21(0 TO 64) := 
    (to_signed(16#0B5B93#, 21), to_signed(16#0B7207#, 21), to_signed(16#0B884F#, 21), to_signed(16#0B9E6D#, 21),
     to_signed(16#0BB461#, 21), to_signed(16#0BCA2C#, 21), to_signed(16#0BDFCF#, 21), to_signed(16#0BF54B#, 21),
     to_signed(16#0C0AA0#, 21), to_signed(16#0C1FD0#, 21), to_signed(16#0C34DB#, 21), to_signed(16#0C49C2#, 21),
     to_signed(16#0C5E86#, 21), to_signed(16#0C7327#, 21), to_signed(16#0C87A6#, 21), to_signed(16#0C9C04#, 21),
     to_signed(16#0CB042#, 21), to_signed(16#0CC45F#, 21), to_signed(16#0CD85C#, 21), to_signed(16#0CEC3B#, 21),
     to_signed(16#0CFFFB#, 21), to_signed(16#0D139E#, 21), to_signed(16#0D2723#, 21), to_signed(16#0D3A8B#, 21),
     to_signed(16#0D4DD7#, 21), to_signed(16#0D6108#, 21), to_signed(16#0D741C#, 21), to_signed(16#0D8716#, 21),
     to_signed(16#0D99F6#, 21), to_signed(16#0DACBB#, 21), to_signed(16#0DBF67#, 21), to_signed(16#0DD1FA#, 21),
     to_signed(16#0DE473#, 21), to_signed(16#0DF6D5#, 21), to_signed(16#0E091E#, 21), to_signed(16#0E1B4F#, 21),
     to_signed(16#0E2D6A#, 21), to_signed(16#0E3F6D#, 21), to_signed(16#0E5159#, 21), to_signed(16#0E632F#, 21),
     to_signed(16#0E74F0#, 21), to_signed(16#0E869A#, 21), to_signed(16#0E982F#, 21), to_signed(16#0EA9AF#, 21),
     to_signed(16#0EBB1A#, 21), to_signed(16#0ECC71#, 21), to_signed(16#0EDDB4#, 21), to_signed(16#0EEEE2#, 21),
     to_signed(16#0EFFFD#, 21), to_signed(16#0F1104#, 21), to_signed(16#0F21F9#, 21), to_signed(16#0F32DA#, 21),
     to_signed(16#0F43A9#, 21), to_signed(16#0F5465#, 21), to_signed(16#0F650F#, 21), to_signed(16#0F75A7#, 21),
     to_signed(16#0F862E#, 21), to_signed(16#0F96A2#, 21), to_signed(16#0FA706#, 21), to_signed(16#0FB758#, 21),
     to_signed(16#0FC79A#, 21), to_signed(16#0FD7CB#, 21), to_signed(16#0FE7EB#, 21), to_signed(16#0FF7FB#, 21),
     to_signed(16#000000#, 21));  -- sfix21 [65]
  CONSTANT alpha1_D_Lookup_Table_data     : vector_of_signed13(0 TO 64) := 
    (to_signed(16#07F8#, 13), to_signed(16#07E8#, 13), to_signed(16#07D9#, 13), to_signed(16#07CA#, 13),
     to_signed(16#07BC#, 13), to_signed(16#07AD#, 13), to_signed(16#079F#, 13), to_signed(16#0792#, 13),
     to_signed(16#0784#, 13), to_signed(16#0777#, 13), to_signed(16#076A#, 13), to_signed(16#075E#, 13),
     to_signed(16#0751#, 13), to_signed(16#0745#, 13), to_signed(16#0739#, 13), to_signed(16#072E#, 13),
     to_signed(16#0722#, 13), to_signed(16#0717#, 13), to_signed(16#070C#, 13), to_signed(16#0701#, 13),
     to_signed(16#06F6#, 13), to_signed(16#06EC#, 13), to_signed(16#06E2#, 13), to_signed(16#06D8#, 13),
     to_signed(16#06CE#, 13), to_signed(16#06C4#, 13), to_signed(16#06BA#, 13), to_signed(16#06B1#, 13),
     to_signed(16#06A8#, 13), to_signed(16#069E#, 13), to_signed(16#0695#, 13), to_signed(16#068D#, 13),
     to_signed(16#0684#, 13), to_signed(16#067B#, 13), to_signed(16#0673#, 13), to_signed(16#066B#, 13),
     to_signed(16#0662#, 13), to_signed(16#065A#, 13), to_signed(16#0652#, 13), to_signed(16#064A#, 13),
     to_signed(16#0643#, 13), to_signed(16#063B#, 13), to_signed(16#0634#, 13), to_signed(16#062C#, 13),
     to_signed(16#0625#, 13), to_signed(16#061E#, 13), to_signed(16#0617#, 13), to_signed(16#0610#, 13),
     to_signed(16#0609#, 13), to_signed(16#0602#, 13), to_signed(16#05FB#, 13), to_signed(16#05F5#, 13),
     to_signed(16#05EE#, 13), to_signed(16#05E7#, 13), to_signed(16#05E1#, 13), to_signed(16#05DB#, 13),
     to_signed(16#05D5#, 13), to_signed(16#05CE#, 13), to_signed(16#05C8#, 13), to_signed(16#05C2#, 13),
     to_signed(16#05BC#, 13), to_signed(16#05B7#, 13), to_signed(16#05B1#, 13), to_signed(16#05AB#, 13),
     to_signed(16#0000#, 13));  -- sfix13 [65]
  CONSTANT alpha1_D_Lookup_Table1_data    : vector_of_signed21(0 TO 64) := 
    (to_signed(16#0807F7#, 21), to_signed(16#0817D8#, 21), to_signed(16#082799#, 21), to_signed(16#08373D#, 21),
     to_signed(16#0846C2#, 21), to_signed(16#08562B#, 21), to_signed(16#086578#, 21), to_signed(16#0874A9#, 21),
     to_signed(16#0883BF#, 21), to_signed(16#0892BA#, 21), to_signed(16#08A19B#, 21), to_signed(16#08B063#, 21),
     to_signed(16#08BF12#, 21), to_signed(16#08CDA8#, 21), to_signed(16#08DC27#, 21), to_signed(16#08EA8D#, 21),
     to_signed(16#08F8DD#, 21), to_signed(16#090716#, 21), to_signed(16#091539#, 21), to_signed(16#092346#, 21),
     to_signed(16#09313D#, 21), to_signed(16#093F1F#, 21), to_signed(16#094CED#, 21), to_signed(16#095AA6#, 21),
     to_signed(16#09684B#, 21), to_signed(16#0975DD#, 21), to_signed(16#09835B#, 21), to_signed(16#0990C6#, 21),
     to_signed(16#099E1E#, 21), to_signed(16#09AB64#, 21), to_signed(16#09B898#, 21), to_signed(16#09C5BA#, 21),
     to_signed(16#09D2CA#, 21), to_signed(16#09DFC9#, 21), to_signed(16#09ECB8#, 21), to_signed(16#09F995#, 21),
     to_signed(16#0A0662#, 21), to_signed(16#0A131E#, 21), to_signed(16#0A1FCB#, 21), to_signed(16#0A2C68#, 21),
     to_signed(16#0A38F5#, 21), to_signed(16#0A4573#, 21), to_signed(16#0A51E2#, 21), to_signed(16#0A5E41#, 21),
     to_signed(16#0A6A93#, 21), to_signed(16#0A76D5#, 21), to_signed(16#0A830A#, 21), to_signed(16#0A8F30#, 21),
     to_signed(16#0A9B48#, 21), to_signed(16#0AA753#, 21), to_signed(16#0AB350#, 21), to_signed(16#0ABF3F#, 21),
     to_signed(16#0ACB22#, 21), to_signed(16#0AD6F7#, 21), to_signed(16#0AE2C0#, 21), to_signed(16#0AEE7C#, 21),
     to_signed(16#0AFA2B#, 21), to_signed(16#0B05CE#, 21), to_signed(16#0B1165#, 21), to_signed(16#0B1CEF#, 21),
     to_signed(16#0B286E#, 21), to_signed(16#0B33E1#, 21), to_signed(16#0B3F48#, 21), to_signed(16#0B4AA4#, 21),
     to_signed(16#000000#, 21));  -- sfix21 [65]

  -- Signals
  SIGNAL passIn_signed                    : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Delay23_reg                      : vector_of_signed9(0 TO 6);  -- sfix9 [7]
  SIGNAL Delay23_out1                     : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL x_f_unsigned                     : unsigned(30 DOWNTO 0);  -- ufix31_En24
  SIGNAL reduced_reg                      : vector_of_unsigned31(0 TO 2);  -- ufix31 [3]
  SIGNAL x_f_1                            : unsigned(30 DOWNTO 0);  -- ufix31_En24
  SIGNAL init_guard_true_1                : std_logic;
  SIGNAL init_guard_true_2                : std_logic;
  SIGNAL outinit_guard_default            : signed(12 DOWNTO 0);  -- sfix13_En12
  SIGNAL Constant1_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Subtract1_sub_cast               : unsigned(30 DOWNTO 0);  -- ufix31_En24
  SIGNAL Subtract1_out1                   : unsigned(30 DOWNTO 0);  -- ufix31_En24
  SIGNAL x_e                              : unsigned(30 DOWNTO 0);  -- ufix31_En19
  SIGNAL u016                             : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL u016_dtc                         : signed(7 DOWNTO 0);  -- int8
  SIGNAL Constant2_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant2_out1_dtc               : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch2_out1                     : signed(7 DOWNTO 0);  -- int8
  SIGNAL Switch2_out1_1                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL prelookup_idx                    : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL out_rsvd                         : signed(12 DOWNTO 0);  -- sfix13_En12
  SIGNAL out_rsvd_1                       : signed(12 DOWNTO 0) := to_signed(16#0000#, 13);  -- sfix13_En12
  SIGNAL c1                               : signed(12 DOWNTO 0);  -- sfix13_En12
  SIGNAL Delay13_out1                     : signed(12 DOWNTO 0);  -- sfix13_En12
  SIGNAL Product1_cast                    : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL Product1_mul_temp                : signed(44 DOWNTO 0);  -- sfix45_En36
  SIGNAL Product1_out1                    : signed(43 DOWNTO 0);  -- sfix44_En36
  SIGNAL Delay19_reg                      : vector_of_signed44(0 TO 1);  -- sfix44 [2]
  SIGNAL Delay19_out1                     : signed(43 DOWNTO 0);  -- sfix44_En36
  SIGNAL init_guard_true_4                : std_logic;
  SIGNAL init_guard_true_5                : std_logic;
  SIGNAL outinit_guard_default_1          : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL prelookup_idx_1                  : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL out_rsvd_2                       : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL out_rsvd_3                       : signed(20 DOWNTO 0) := to_signed(16#000000#, 21);  -- sfix21_En20
  SIGNAL c0                               : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL Delay20_reg                      : vector_of_signed21(0 TO 2);  -- sfix21 [3]
  SIGNAL Delay20_out1                     : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL Add1_add_cast                    : unsigned(16 DOWNTO 0);  -- ufix17_En13
  SIGNAL Add1_add_cast_1                  : unsigned(16 DOWNTO 0);  -- ufix17_En13
  SIGNAL Add1_out1                        : unsigned(16 DOWNTO 0);  -- ufix17_En13
  SIGNAL Delay24_reg                      : vector_of_unsigned17(0 TO 1);  -- ufix17 [2]
  SIGNAL Delay24_out1                     : unsigned(16 DOWNTO 0);  -- ufix17_En13
  SIGNAL init_guard_true_7                : std_logic;
  SIGNAL init_guard_true_8                : std_logic;
  SIGNAL outinit_guard_default_2          : signed(12 DOWNTO 0);  -- sfix13_En12
  SIGNAL Constant_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Subtract_sub_cast                : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL Subtract_sub_cast_1              : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL Subtract_out1                    : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL x_e_1                            : signed(32 DOWNTO 0);  -- sfix33_En18
  SIGNAL u016_1                           : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL Switch1_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Switch1_out1_1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL prelookup_idx_2                  : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL out_rsvd_4                       : signed(12 DOWNTO 0);  -- sfix13_En12
  SIGNAL out_rsvd_5                       : signed(12 DOWNTO 0) := to_signed(16#0000#, 13);  -- sfix13_En12
  SIGNAL c1_1                             : signed(12 DOWNTO 0);  -- sfix13_En12
  SIGNAL Delay9_out1                      : signed(12 DOWNTO 0);  -- sfix13_En12
  SIGNAL Product_cast                     : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL Product_mul_temp                 : signed(44 DOWNTO 0);  -- sfix45_En36
  SIGNAL Product_out1                     : signed(43 DOWNTO 0);  -- sfix44_En36
  SIGNAL Delay16_reg                      : vector_of_signed44(0 TO 1);  -- sfix44 [2]
  SIGNAL Delay16_out1                     : signed(43 DOWNTO 0);  -- sfix44_En36
  SIGNAL init_guard_true_10               : std_logic;
  SIGNAL init_guard_true_11               : std_logic;
  SIGNAL outinit_guard_default_3          : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL prelookup_idx_3                  : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL out_rsvd_6                       : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL out_rsvd_7                       : signed(20 DOWNTO 0) := to_signed(16#000000#, 21);  -- sfix21_En20
  SIGNAL c0_1                             : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL Delay17_reg                      : vector_of_signed21(0 TO 2);  -- sfix21 [3]
  SIGNAL Delay17_out1                     : signed(20 DOWNTO 0);  -- sfix21_En20
  SIGNAL Add_add_cast                     : signed(43 DOWNTO 0);  -- sfix44_En36
  SIGNAL Add_add_temp                     : signed(43 DOWNTO 0);  -- sfix44_En36
  SIGNAL Add_out1                         : unsigned(16 DOWNTO 0);  -- ufix17_En13
  SIGNAL Delay22_reg                      : vector_of_unsigned17(0 TO 1);  -- ufix17 [2]
  SIGNAL Delay22_out1                     : unsigned(16 DOWNTO 0);  -- ufix17_En13
  SIGNAL Switch_out1                      : unsigned(16 DOWNTO 0);  -- ufix17_En13
  SIGNAL exp_fIn_signed                   : signed(7 DOWNTO 0);  -- int8
  SIGNAL Delay25_reg                      : vector_of_signed8(0 TO 6);  -- sfix8 [7]
  SIGNAL Delay25_out1                     : signed(7 DOWNTO 0);  -- int8

  ATTRIBUTE use_dsp : string;

  ATTRIBUTE use_dsp OF Product1_out1 : SIGNAL IS "no";
  ATTRIBUTE use_dsp OF Product_out1 : SIGNAL IS "no";

BEGIN
  passIn_signed <= signed(passIn);

  Delay23_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay23_reg <= (OTHERS => to_signed(16#000#, 9));
      ELSIF enb_1_8_0 = '1' THEN
        Delay23_reg(0) <= passIn_signed;
        Delay23_reg(1 TO 6) <= Delay23_reg(0 TO 5);
      END IF;
    END IF;
  END PROCESS Delay23_process;

  Delay23_out1 <= Delay23_reg(6);

  x_f_unsigned <= unsigned(x_f);

  reduced_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        reduced_reg <= (OTHERS => to_unsigned(16#00000000#, 31));
      ELSIF enb_1_8_0 = '1' THEN
        reduced_reg(0) <= x_f_unsigned;
        reduced_reg(1 TO 2) <= reduced_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS reduced_process;

  x_f_1 <= reduced_reg(2);

  init_guard_true_1 <= '1';

  matching_delays_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        init_guard_true_2 <= '0';
      ELSIF enb_1_8_0 = '1' THEN
        init_guard_true_2 <= init_guard_true_1;
      END IF;
    END IF;
  END PROCESS matching_delays_process;


  outinit_guard_default <= to_signed(16#0000#, 13);

  Constant1_out1 <= to_unsigned(16#02#, 8);

  Subtract1_sub_cast <= Constant1_out1(6 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  Subtract1_out1 <= x_f_unsigned - Subtract1_sub_cast;

  x_e <= Subtract1_out1;

  u016 <= x_e(26 DOWNTO 19);

  
  switch_compare_1 <= '1' WHEN u016 > to_unsigned(16#3F#, 8) ELSE
      '0';

  u016_dtc <= signed(u016);

  Constant2_out1 <= to_unsigned(16#40#, 8);

  Constant2_out1_dtc <= signed(Constant2_out1);

  
  Switch2_out1 <= u016_dtc WHEN switch_compare_1 = '0' ELSE
      Constant2_out1_dtc;

  reduced_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Switch2_out1_1 <= to_signed(16#00#, 8);
      ELSIF enb_1_8_0 = '1' THEN
        Switch2_out1_1 <= Switch2_out1;
      END IF;
    END IF;
  END PROCESS reduced_1_process;


  
  prelookup_idx <= to_unsigned(16#00#, 7) WHEN Switch2_out1_1 <= to_signed(16#00#, 8) ELSE
      to_unsigned(16#40#, 7) WHEN Switch2_out1_1 >= to_signed(16#40#, 8) ELSE
      unsigned(Switch2_out1_1(6 DOWNTO 0));

  out_rsvd <= alpha1_D_Lookup_Table2_data(to_integer(prelookup_idx));

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb_1_8_0 = '1' THEN
        out_rsvd_1 <= out_rsvd;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  
  c1 <= outinit_guard_default WHEN init_guard_true_2 = '0' ELSE
      out_rsvd_1;

  Delay13_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay13_out1 <= to_signed(16#0000#, 13);
      ELSIF enb_1_8_0 = '1' THEN
        Delay13_out1 <= c1;
      END IF;
    END IF;
  END PROCESS Delay13_process;


  Product1_cast <= signed(resize(x_f_1, 32));
  Product1_mul_temp <= Product1_cast * Delay13_out1;
  Product1_out1 <= Product1_mul_temp(43 DOWNTO 0);

  Delay19_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay19_reg <= (OTHERS => to_signed(0, 44));
      ELSIF enb_1_8_0 = '1' THEN
        Delay19_reg(0) <= Product1_out1;
        Delay19_reg(1) <= Delay19_reg(0);
      END IF;
    END IF;
  END PROCESS Delay19_process;

  Delay19_out1 <= Delay19_reg(1);

  init_guard_true_4 <= '1';

  matching_delays_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        init_guard_true_5 <= '0';
      ELSIF enb_1_8_0 = '1' THEN
        init_guard_true_5 <= init_guard_true_4;
      END IF;
    END IF;
  END PROCESS matching_delays_1_process;


  outinit_guard_default_1 <= to_signed(16#000000#, 21);

  
  prelookup_idx_1 <= to_unsigned(16#00#, 7) WHEN Switch2_out1_1 <= to_signed(16#00#, 8) ELSE
      to_unsigned(16#40#, 7) WHEN Switch2_out1_1 >= to_signed(16#40#, 8) ELSE
      unsigned(Switch2_out1_1(6 DOWNTO 0));

  out_rsvd_2 <= alpha1_D_Lookup_Table3_data(to_integer(prelookup_idx_1));

  PipelineRegister_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb_1_8_0 = '1' THEN
        out_rsvd_3 <= out_rsvd_2;
      END IF;
    END IF;
  END PROCESS PipelineRegister_1_process;


  
  c0 <= outinit_guard_default_1 WHEN init_guard_true_5 = '0' ELSE
      out_rsvd_3;

  Delay20_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay20_reg <= (OTHERS => to_signed(16#000000#, 21));
      ELSIF enb_1_8_0 = '1' THEN
        Delay20_reg(0) <= c0;
        Delay20_reg(1 TO 2) <= Delay20_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS Delay20_process;

  Delay20_out1 <= Delay20_reg(2);

  Add1_add_cast <= unsigned(Delay19_out1(39 DOWNTO 23));
  Add1_add_cast_1 <= unsigned(resize(Delay20_out1(20 DOWNTO 7), 17));
  Add1_out1 <= Add1_add_cast + Add1_add_cast_1;

  Delay24_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay24_reg <= (OTHERS => to_unsigned(16#00000#, 17));
      ELSIF enb_1_8_0 = '1' THEN
        Delay24_reg(0) <= Add1_out1;
        Delay24_reg(1) <= Delay24_reg(0);
      END IF;
    END IF;
  END PROCESS Delay24_process;

  Delay24_out1 <= Delay24_reg(1);

  init_guard_true_7 <= '1';

  matching_delays_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        init_guard_true_8 <= '0';
      ELSIF enb_1_8_0 = '1' THEN
        init_guard_true_8 <= init_guard_true_7;
      END IF;
    END IF;
  END PROCESS matching_delays_2_process;


  outinit_guard_default_2 <= to_signed(16#0000#, 13);

  Constant_out1 <= to_unsigned(16#01#, 8);

  Subtract_sub_cast <= signed(resize(x_f_unsigned, 33));
  Subtract_sub_cast_1 <= signed(resize(Constant_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 33));
  Subtract_out1 <= Subtract_sub_cast - Subtract_sub_cast_1;

  x_e_1 <= Subtract_out1;

  u016_1 <= unsigned(x_e_1(25 DOWNTO 18));

  
  switch_compare_1_1 <= '1' WHEN u016_1 > to_unsigned(16#3F#, 8) ELSE
      '0';

  
  Switch1_out1 <= u016_1 WHEN switch_compare_1_1 = '0' ELSE
      Constant2_out1;

  reduced_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Switch1_out1_1 <= to_unsigned(16#00#, 8);
      ELSIF enb_1_8_0 = '1' THEN
        Switch1_out1_1 <= Switch1_out1;
      END IF;
    END IF;
  END PROCESS reduced_2_process;


  
  prelookup_idx_2 <= to_unsigned(16#00#, 7) WHEN Switch1_out1_1 = to_unsigned(16#00#, 8) ELSE
      to_unsigned(16#40#, 7) WHEN Switch1_out1_1 >= to_unsigned(16#40#, 8) ELSE
      Switch1_out1_1(6 DOWNTO 0);

  out_rsvd_4 <= alpha1_D_Lookup_Table_data(to_integer(prelookup_idx_2));

  PipelineRegister_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb_1_8_0 = '1' THEN
        out_rsvd_5 <= out_rsvd_4;
      END IF;
    END IF;
  END PROCESS PipelineRegister_2_process;


  
  c1_1 <= outinit_guard_default_2 WHEN init_guard_true_8 = '0' ELSE
      out_rsvd_5;

  Delay9_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay9_out1 <= to_signed(16#0000#, 13);
      ELSIF enb_1_8_0 = '1' THEN
        Delay9_out1 <= c1_1;
      END IF;
    END IF;
  END PROCESS Delay9_process;


  Product_cast <= signed(resize(x_f_1, 32));
  Product_mul_temp <= Product_cast * Delay9_out1;
  Product_out1 <= Product_mul_temp(43 DOWNTO 0);

  Delay16_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay16_reg <= (OTHERS => to_signed(0, 44));
      ELSIF enb_1_8_0 = '1' THEN
        Delay16_reg(0) <= Product_out1;
        Delay16_reg(1) <= Delay16_reg(0);
      END IF;
    END IF;
  END PROCESS Delay16_process;

  Delay16_out1 <= Delay16_reg(1);

  init_guard_true_10 <= '1';

  matching_delays_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        init_guard_true_11 <= '0';
      ELSIF enb_1_8_0 = '1' THEN
        init_guard_true_11 <= init_guard_true_10;
      END IF;
    END IF;
  END PROCESS matching_delays_3_process;


  outinit_guard_default_3 <= to_signed(16#000000#, 21);

  
  prelookup_idx_3 <= to_unsigned(16#00#, 7) WHEN Switch1_out1_1 = to_unsigned(16#00#, 8) ELSE
      to_unsigned(16#40#, 7) WHEN Switch1_out1_1 >= to_unsigned(16#40#, 8) ELSE
      Switch1_out1_1(6 DOWNTO 0);

  out_rsvd_6 <= alpha1_D_Lookup_Table1_data(to_integer(prelookup_idx_3));

  PipelineRegister_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb_1_8_0 = '1' THEN
        out_rsvd_7 <= out_rsvd_6;
      END IF;
    END IF;
  END PROCESS PipelineRegister_3_process;


  
  c0_1 <= outinit_guard_default_3 WHEN init_guard_true_11 = '0' ELSE
      out_rsvd_7;

  Delay17_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay17_reg <= (OTHERS => to_signed(16#000000#, 21));
      ELSIF enb_1_8_0 = '1' THEN
        Delay17_reg(0) <= c0_1;
        Delay17_reg(1 TO 2) <= Delay17_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS Delay17_process;

  Delay17_out1 <= Delay17_reg(2);

  Add_add_cast <= resize(Delay17_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 44);
  Add_add_temp <= Delay16_out1 + Add_add_cast;
  Add_out1 <= unsigned(Add_add_temp(39 DOWNTO 23));

  Delay22_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay22_reg <= (OTHERS => to_unsigned(16#00000#, 17));
      ELSIF enb_1_8_0 = '1' THEN
        Delay22_reg(0) <= Add_out1;
        Delay22_reg(1) <= Delay22_reg(0);
      END IF;
    END IF;
  END PROCESS Delay22_process;

  Delay22_out1 <= Delay22_reg(1);

  
  Switch_out1 <= Delay24_out1 WHEN Delay23_out1 = to_signed(16#000#, 9) ELSE
      Delay22_out1;

  y_f <= std_logic_vector(Switch_out1);

  passOut <= std_logic_vector(Delay23_out1);

  exp_fIn_signed <= signed(exp_fIn);

  Delay25_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay25_reg <= (OTHERS => to_signed(16#00#, 8));
      ELSIF enb_1_8_0 = '1' THEN
        Delay25_reg(0) <= exp_fIn_signed;
        Delay25_reg(1 TO 6) <= Delay25_reg(0 TO 5);
      END IF;
    END IF;
  END PROCESS Delay25_process;

  Delay25_out1 <= Delay25_reg(6);

  exp_fOut <= std_logic_vector(Delay25_out1);

END rtl;

