-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_DecoderCore.vhd
-- Created: 2025-10-27 18:12:27
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_DecoderCore
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/FEC Decoding/DVB-S2 
-- LDPC Decoder/DecoderCor
-- Hierarchy Level: 6
-- Model version: 9.0
-- 
-- Decoder Core
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_DecoderCore IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        data                              :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8_En4
        valid                             :   IN    std_logic;  -- ufix1
        framevalid                        :   IN    std_logic;  -- ufix1
        reset_1                           :   IN    std_logic;  -- ufix1
        softReset                         :   IN    std_logic;  -- ufix1
        numiter                           :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        parind                            :   IN    std_logic;  -- ufix1
        nlayers                           :   IN    std_logic_vector(10 DOWNTO 0);  -- ufix11
        outlen                            :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        rateidx                           :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        lenidx                            :   IN    std_logic;  -- ufix1
        data_1                            :   OUT   std_logic;  -- ufix1
        start                             :   OUT   std_logic;  -- ufix1
        end_rsvd                          :   OUT   std_logic;  -- ufix1
        valid_1                           :   OUT   std_logic  -- ufix1
        );
END dvbs2_ip_src_DecoderCore;


ARCHITECTURE rtl OF dvbs2_ip_src_DecoderCore IS

  -- Component Declarations
  COMPONENT dvbs2_ip_src_MetricCalculator
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          data                            :   IN    vector_of_std_logic_vector11(0 TO 44);  -- sfix11_En4 [45]
          valid                           :   IN    std_logic;  -- ufix1
          shift                           :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
          reset_1                         :   IN    std_logic;  -- ufix1
          ddsm                            :   IN    std_logic;  -- ufix1
          parvalid                        :   IN    std_logic;  -- ufix1
          layeridx                        :   IN    std_logic_vector(10 DOWNTO 0);  -- ufix11
          betaenb                         :   IN    std_logic;  -- ufix1
          degree                          :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
          gamma                           :   OUT   vector_of_std_logic_vector11(0 TO 44);  -- sfix11_En4 [45]
          gammavalid                      :   OUT   std_logic;  -- ufix1
          gParValid                       :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_IterationController
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          data                            :   IN    std_logic_vector(10 DOWNTO 0);  -- sfix11_En4
          valid                           :   IN    std_logic;  -- ufix1
          framevalid                      :   IN    std_logic;  -- ufix1
          reset_1                         :   IN    std_logic;  -- ufix1
          softreset                       :   IN    std_logic;  -- ufix1
          numiter                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          parind                          :   IN    std_logic;  -- ufix1
          nlayers                         :   IN    std_logic_vector(10 DOWNTO 0);  -- ufix11
          outlen                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          rateidx                         :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          lenidx                          :   IN    std_logic;  -- ufix1
          gpvalid                         :   IN    std_logic;  -- ufix1
          valid1                          :   IN    std_logic;  -- ufix1
          gamma                           :   IN    vector_of_std_logic_vector11(0 TO 44);  -- sfix11_En4 [45]
          gvalid                          :   IN    std_logic;  -- ufix1
          gwrenb                          :   IN    std_logic_vector(44 DOWNTO 0);  -- ufix1 [45]
          coldata                         :   OUT   vector_of_std_logic_vector11(0 TO 44);  -- sfix11_En4 [45]
          rdvalid                         :   OUT   std_logic;  -- ufix1
          svalue                          :   OUT   std_logic_vector(5 DOWNTO 0);  -- ufix6
          ddsmind                         :   OUT   std_logic;  -- ufix1
          parvalid                        :   OUT   std_logic;  -- ufix1
          layeridx                        :   OUT   std_logic_vector(10 DOWNTO 0);  -- ufix11
          betaread                        :   OUT   std_logic;  -- ufix1
          degree                          :   OUT   std_logic_vector(4 DOWNTO 0);  -- ufix5
          iterdone                        :   OUT   std_logic;  -- ufix1
          rdcount                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          irddata                         :   OUT   vector_of_std_logic_vector11(0 TO 44)  -- sfix11_En4 [45]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dvbs2_ip_src_MetricCalculator
    USE ENTITY work.dvbs2_ip_src_MetricCalculator(rtl);

  FOR ALL : dvbs2_ip_src_IterationController
    USE ENTITY work.dvbs2_ip_src_IterationController(rtl);

  -- Constants
  CONSTANT parityVNWriting_data           : std_logic_vector(44 DOWNTO 0) := 
    ('0', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
     '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
     '1');  -- boolean [45]

  -- Signals
  SIGNAL data_signed                      : signed(7 DOWNTO 0);  -- sfix8_En4
  SIGNAL dataDTC                          : signed(10 DOWNTO 0);  -- sfix11_En4
  SIGNAL intReset                         : std_logic;  -- ufix1
  SIGNAL gamma                            : vector_of_std_logic_vector11(0 TO 44);  -- ufix11 [45]
  SIGNAL gamma_signed                     : vector_of_signed11(0 TO 44);  -- sfix11_En4 [45]
  SIGNAL gValid                           : std_logic;  -- ufix1
  SIGNAL gParValid                        : std_logic;  -- ufix1
  SIGNAL layerIdx                         : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL parityVNWriting_rdData           : vector_of_signed11(0 TO 44);  -- sfix11 [45]
  SIGNAL parityVNWriting_rValid           : std_logic;
  SIGNAL parityVNWriting_pValid           : std_logic;
  SIGNAL parityVNWriting_count            : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL parityVNWriting_rdDataE          : vector_of_signed11(0 TO 44);  -- sfix11 [45]
  SIGNAL parityVNWriting_rdData_next      : vector_of_signed11(0 TO 44);  -- sfix11_En4 [45]
  SIGNAL parityVNWriting_rValid_next      : std_logic;
  SIGNAL parityVNWriting_pValid_next      : std_logic;
  SIGNAL parityVNWriting_count_next       : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL parityVNWriting_rdDataE_next     : vector_of_signed11(0 TO 44);  -- sfix11_En4 [45]
  SIGNAL gammaOut                         : vector_of_signed11(0 TO 44);  -- sfix11_En4 [45]
  SIGNAL gValidOut                        : std_logic;  -- ufix1
  SIGNAL gWrEnb                           : std_logic_vector(44 DOWNTO 0);  -- ufix1 [45]
  SIGNAL gammaOut_1                       : vector_of_std_logic_vector11(0 TO 44);  -- ufix11 [45]
  SIGNAL countLayer                       : std_logic_vector(10 DOWNTO 0);  -- ufix11
  SIGNAL countLayer_unsigned              : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL ddsmInd                          : std_logic;  -- ufix1
  SIGNAL ddsmReg                          : std_logic;  -- ufix1
  SIGNAL colData                          : vector_of_std_logic_vector11(0 TO 44);  -- ufix11 [45]
  SIGNAL rdValid                          : std_logic;  -- ufix1
  SIGNAL sValue                           : std_logic_vector(5 DOWNTO 0);  -- ufix6
  SIGNAL parValid                         : std_logic;  -- ufix1
  SIGNAL betaRead                         : std_logic;  -- ufix1
  SIGNAL degree                           : std_logic_vector(4 DOWNTO 0);  -- ufix5
  SIGNAL iterDone                         : std_logic;  -- ufix1
  SIGNAL rdCount                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL irdData                          : vector_of_std_logic_vector11(0 TO 44);  -- ufix11 [45]
  SIGNAL iterDoneReg                      : std_logic;  -- ufix1
  SIGNAL rdCount_unsigned                 : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL rdCountReg                       : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL irdData_signed                   : vector_of_signed11(0 TO 44);  -- sfix11_En4 [45]
  SIGNAL irdDataTmp                       : std_logic_vector(44 DOWNTO 0);  -- ufix1 [45]
  SIGNAL irdDataReg                       : std_logic_vector(44 DOWNTO 0);  -- ufix1 [45]
  SIGNAL outlen_unsigned                  : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL finalEnbReg                      : std_logic;  -- ufix1
  SIGNAL finalDecision_iterDone           : std_logic;
  SIGNAL finalDecision_startEnb           : std_logic;
  SIGNAL finalDecision_dataOut            : std_logic;
  SIGNAL finalDecision_startOut           : std_logic;
  SIGNAL finalDecision_endOut             : std_logic;
  SIGNAL finalDecision_validOut           : std_logic;
  SIGNAL finalDecision_countSF            : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL finalDecision_countZ             : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL finalDecision_rdCount            : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL finalDecision_read_rsvd          : std_logic;
  SIGNAL finalDecision_iterDone_next      : std_logic;
  SIGNAL finalDecision_startEnb_next      : std_logic;
  SIGNAL finalDecision_dataOut_next       : std_logic;
  SIGNAL finalDecision_startOut_next      : std_logic;
  SIGNAL finalDecision_endOut_next        : std_logic;
  SIGNAL finalDecision_validOut_next      : std_logic;
  SIGNAL finalDecision_countSF_next       : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL finalDecision_countZ_next        : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL finalDecision_rdCount_next       : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL finalDecision_read_next          : std_logic;
  SIGNAL dataO                            : std_logic;  -- ufix1
  SIGNAL startO                           : std_logic;  -- ufix1
  SIGNAL endO                             : std_logic;  -- ufix1
  SIGNAL validO                           : std_logic;  -- ufix1
  SIGNAL zeroData                         : std_logic;  -- ufix1
  SIGNAL dataTmp                          : std_logic;  -- ufix1
  SIGNAL dataOut_reg                      : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL data_2                           : std_logic;  -- ufix1
  SIGNAL const1                           : std_logic;  -- ufix1
  SIGNAL startTmp                         : std_logic;  -- ufix1
  SIGNAL startOut_reg                     : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL endTmp                           : std_logic;  -- ufix1
  SIGNAL endOut_reg                       : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL validTmp                         : std_logic;  -- ufix1
  SIGNAL validOut_reg                     : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL valid_2                          : std_logic;  -- ufix1

BEGIN
  u_Metric_Calculator : dvbs2_ip_src_MetricCalculator
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              data => colData,  -- sfix11_En4 [45]
              valid => rdValid,  -- ufix1
              shift => sValue,  -- ufix6
              reset_1 => intReset,  -- ufix1
              ddsm => ddsmReg,  -- ufix1
              parvalid => parValid,  -- ufix1
              layeridx => std_logic_vector(layerIdx),  -- ufix11
              betaenb => betaRead,  -- ufix1
              degree => degree,  -- ufix5
              gamma => gamma,  -- sfix11_En4 [45]
              gammavalid => gValid,  -- ufix1
              gParValid => gParValid  -- ufix1
              );

  u_IteraionContoller : dvbs2_ip_src_IterationController
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              data => std_logic_vector(dataDTC),  -- sfix11_En4
              valid => valid,  -- ufix1
              framevalid => framevalid,  -- ufix1
              reset_1 => reset_1,  -- ufix1
              softreset => softReset,  -- ufix1
              numiter => numiter,  -- ufix8
              parind => parind,  -- ufix1
              nlayers => nlayers,  -- ufix11
              outlen => outlen,  -- ufix16
              rateidx => rateidx,  -- ufix4
              lenidx => lenidx,  -- ufix1
              gpvalid => gParValid,  -- ufix1
              valid1 => gValid,  -- ufix1
              gamma => gammaOut_1,  -- sfix11_En4 [45]
              gvalid => gValidOut,  -- ufix1
              gwrenb => gWrEnb,  -- ufix1 [45]
              coldata => colData,  -- sfix11_En4 [45]
              rdvalid => rdValid,  -- ufix1
              svalue => sValue,  -- ufix6
              ddsmind => ddsmInd,  -- ufix1
              parvalid => parValid,  -- ufix1
              layeridx => countLayer,  -- ufix11
              betaread => betaRead,  -- ufix1
              degree => degree,  -- ufix5
              iterdone => iterDone,  -- ufix1
              rdcount => rdCount,  -- ufix16
              irddata => irdData  -- sfix11_En4 [45]
              );

  data_signed <= signed(data);

  dataDTC <= resize(data_signed, 11);

  intReset <= reset_1 OR softReset;

  outputgen2: FOR k IN 0 TO 44 GENERATE
    gamma_signed(k) <= signed(gamma(k));
  END GENERATE;

  parityVNWriting_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        parityVNWriting_rdData <= (OTHERS => to_signed(16#000#, 11));
        parityVNWriting_rdDataE <= (OTHERS => to_signed(16#000#, 11));
        parityVNWriting_rValid <= '0';
        parityVNWriting_pValid <= '0';
        parityVNWriting_count <= to_unsigned(16#0#, 3);
      ELSIF enb = '1' THEN
        parityVNWriting_rValid <= parityVNWriting_rValid_next;
        parityVNWriting_pValid <= parityVNWriting_pValid_next;
        parityVNWriting_count <= parityVNWriting_count_next;
        parityVNWriting_rdData <= parityVNWriting_rdData_next;
        parityVNWriting_rdDataE <= parityVNWriting_rdDataE_next;
      END IF;
    END IF;
  END PROCESS parityVNWriting_process;

  parityVNWriting_output : PROCESS (gParValid, gValid, gamma_signed, intReset, layerIdx, parityVNWriting_count,
       parityVNWriting_pValid, parityVNWriting_rValid, parityVNWriting_rdData,
       parityVNWriting_rdDataE)
    VARIABLE out0 : vector_of_signed11(0 TO 44);
    VARIABLE wrEnb : std_logic_vector(44 DOWNTO 0);
  BEGIN
    parityVNWriting_rdDataE_next <= parityVNWriting_rdDataE;
    IF intReset /= '0' THEN 
      out0 := (OTHERS => to_signed(16#000#, 11));
      wrEnb := (OTHERS => '0');
      parityVNWriting_rdDataE_next <= (OTHERS => to_signed(16#000#, 11));
    ELSIF parityVNWriting_rValid = '1' THEN 
      IF parityVNWriting_pValid = '1' THEN 
        IF (layerIdx = to_unsigned(16#001#, 11)) AND (parityVNWriting_count = to_unsigned(16#1#, 3)) THEN 
          out0(0 TO 43) := parityVNWriting_rdData(1 TO 44);
          out0(44) := to_signed(16#000#, 11);
          wrEnb := parityVNWriting_data;
          parityVNWriting_rdDataE_next(0) <= parityVNWriting_rdData(0);
          parityVNWriting_rdDataE_next(1 TO 44) <= gamma_signed(1 TO 44);
        ELSIF (layerIdx = to_unsigned(16#001#, 11)) AND (parityVNWriting_count = to_unsigned(16#2#, 3)) THEN 
          out0 := parityVNWriting_rdDataE;
          wrEnb := (OTHERS => '1');
        ELSE 
          out0 := parityVNWriting_rdData;
          wrEnb := (OTHERS => '1');
        END IF;
      ELSE 
        out0 := parityVNWriting_rdData;
        wrEnb := (OTHERS => '0');
      END IF;
    ELSE 
      out0 := (OTHERS => to_signed(16#000#, 11));
      wrEnb := (OTHERS => '0');
    END IF;
    IF intReset /= '0' THEN 
      parityVNWriting_count_next <= to_unsigned(16#0#, 3);
    ELSIF (gParValid /= '0') AND (gValid /= '0') THEN 
      IF parityVNWriting_count = to_unsigned(16#2#, 3) THEN 
        parityVNWriting_count_next <= to_unsigned(16#0#, 3);
      ELSE 
        parityVNWriting_count_next <= parityVNWriting_count + to_unsigned(16#1#, 3);
      END IF;
    ELSE 
      parityVNWriting_count_next <= to_unsigned(16#0#, 3);
    END IF;
    parityVNWriting_pValid_next <= gParValid;
    parityVNWriting_rValid_next <= gValid;
    gValidOut <= parityVNWriting_rValid;
    parityVNWriting_rdData_next <= gamma_signed;
    gammaOut <= out0;
    gWrEnb <= wrEnb;
  END PROCESS parityVNWriting_output;


  outputgen1: FOR k IN 0 TO 44 GENERATE
    gammaOut_1(k) <= std_logic_vector(gammaOut(k));
  END GENERATE;

  countLayer_unsigned <= unsigned(countLayer);

  c_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        layerIdx <= to_unsigned(16#000#, 11);
      ELSIF enb = '1' THEN
        layerIdx <= countLayer_unsigned;
      END IF;
    END IF;
  END PROCESS c_process;


  c_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        ddsmReg <= '0';
      ELSIF enb = '1' THEN
        ddsmReg <= ddsmInd;
      END IF;
    END IF;
  END PROCESS c_1_process;


  iterDone_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        iterDoneReg <= '0';
      ELSIF enb = '1' THEN
        iterDoneReg <= iterDone;
      END IF;
    END IF;
  END PROCESS iterDone_1_process;


  rdCount_unsigned <= unsigned(rdCount);

  rdCount_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rdCountReg <= to_unsigned(16#0000#, 16);
      ELSIF enb = '1' THEN
        rdCountReg <= rdCount_unsigned;
      END IF;
    END IF;
  END PROCESS rdCount_1_process;


  outputgen: FOR k IN 0 TO 44 GENERATE
    irdData_signed(k) <= signed(irdData(k));
  END GENERATE;


  irdDataTmp_gen: FOR t_0 IN 0 TO 44 GENERATE
    
    irdDataTmp(t_0) <= '1' WHEN irdData_signed(t_0) <= to_signed(16#000#, 11) ELSE
        '0';
  END GENERATE irdDataTmp_gen;


  irdData_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        irdDataReg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        irdDataReg <= irdDataTmp;
      END IF;
    END IF;
  END PROCESS irdData_1_process;


  outlen_unsigned <= unsigned(outlen);

  finalEnbReg <= '0';

  finalDecision_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        finalDecision_iterDone <= '0';
        finalDecision_dataOut <= '0';
        finalDecision_startOut <= '0';
        finalDecision_endOut <= '0';
        finalDecision_validOut <= '0';
        finalDecision_countSF <= to_unsigned(16#0#, 4);
        finalDecision_countZ <= to_unsigned(16#00#, 8);
        finalDecision_rdCount <= to_unsigned(16#0000#, 16);
        finalDecision_read_rsvd <= '0';
        finalDecision_startEnb <= '0';
      ELSIF enb = '1' THEN
        finalDecision_iterDone <= finalDecision_iterDone_next;
        finalDecision_startEnb <= finalDecision_startEnb_next;
        finalDecision_dataOut <= finalDecision_dataOut_next;
        finalDecision_startOut <= finalDecision_startOut_next;
        finalDecision_endOut <= finalDecision_endOut_next;
        finalDecision_validOut <= finalDecision_validOut_next;
        finalDecision_countSF <= finalDecision_countSF_next;
        finalDecision_countZ <= finalDecision_countZ_next;
        finalDecision_rdCount <= finalDecision_rdCount_next;
        finalDecision_read_rsvd <= finalDecision_read_next;
      END IF;
    END IF;
  END PROCESS finalDecision_process;

  finalDecision_output : PROCESS (finalDecision_countSF, finalDecision_countZ, finalDecision_dataOut,
       finalDecision_endOut, finalDecision_iterDone, finalDecision_rdCount,
       finalDecision_read_rsvd, finalDecision_startEnb, finalDecision_startOut,
       finalDecision_validOut, intReset, irdDataReg, iterDoneReg,
       outlen_unsigned, rdCountReg)
    VARIABLE startOut_temp : std_logic;
    VARIABLE validOut_temp : std_logic;
    VARIABLE countZ_temp : unsigned(7 DOWNTO 0);
    VARIABLE read_temp : std_logic;
    VARIABLE sub_cast : signed(31 DOWNTO 0);
  BEGIN
    countZ_temp := finalDecision_countZ;
    read_temp := finalDecision_read_rsvd;
    IF intReset /= '0' THEN 
      read_temp := '0';
      startOut_temp := '0';
      finalDecision_endOut_next <= '0';
      validOut_temp := '0';
    ELSE 
      IF finalDecision_startEnb = '1' THEN 
        read_temp := '1';
      END IF;
      IF read_temp = '1' THEN 
        IF finalDecision_rdCount = to_unsigned(16#0001#, 16) THEN 
          startOut_temp := '1';
          finalDecision_endOut_next <= '0';
          validOut_temp := '1';
        ELSIF finalDecision_rdCount = outlen_unsigned THEN 
          startOut_temp := '0';
          finalDecision_endOut_next <= '1';
          validOut_temp := '1';
          read_temp := '0';
        ELSE 
          startOut_temp := '0';
          finalDecision_endOut_next <= '0';
          validOut_temp := '1';
        END IF;
      ELSE 
        startOut_temp := '0';
        finalDecision_endOut_next <= '0';
        validOut_temp := '0';
      END IF;
    END IF;
    IF startOut_temp = '1' THEN 
      finalDecision_countSF_next <= to_unsigned(16#1#, 4);
      countZ_temp := to_unsigned(16#01#, 8);
    ELSIF validOut_temp = '1' THEN 
      IF finalDecision_countSF = to_unsigned(16#8#, 4) THEN 
        finalDecision_countSF_next <= to_unsigned(16#1#, 4);
        IF finalDecision_countZ = to_unsigned(16#2D#, 8) THEN 
          countZ_temp := to_unsigned(16#01#, 8);
        ELSE 
          countZ_temp := finalDecision_countZ + to_unsigned(16#01#, 8);
        END IF;
      ELSE 
        finalDecision_countSF_next <= finalDecision_countSF + to_unsigned(16#1#, 4);
      END IF;
    ELSE 
      finalDecision_countSF_next <= to_unsigned(16#1#, 4);
      countZ_temp := to_unsigned(16#01#, 8);
    END IF;
    sub_cast := signed(resize(countZ_temp, 32));
    finalDecision_dataOut_next <= irdDataReg(to_integer(sub_cast - 1));
    finalDecision_startEnb_next <= ( NOT finalDecision_iterDone) AND iterDoneReg;
    finalDecision_iterDone_next <= iterDoneReg;
    finalDecision_rdCount_next <= rdCountReg;
    dataO <= finalDecision_dataOut;
    startO <= finalDecision_startOut;
    endO <= finalDecision_endOut;
    validO <= finalDecision_validOut;
    finalDecision_startOut_next <= startOut_temp;
    finalDecision_validOut_next <= validOut_temp;
    finalDecision_countZ_next <= countZ_temp;
    finalDecision_read_next <= read_temp;
  END PROCESS finalDecision_output;


  zeroData <= '0';

  
  dataTmp <= zeroData WHEN validO = '0' ELSE
      dataO;

  dataOut_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dataOut_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        dataOut_reg(0) <= dataTmp;
        dataOut_reg(1) <= dataOut_reg(0);
      END IF;
    END IF;
  END PROCESS dataOut_process;

  data_2 <= dataOut_reg(1);

  const1 <= '0';

  
  startTmp <= const1 WHEN validO = '0' ELSE
      startO;

  startOut_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        startOut_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        startOut_reg(0) <= startTmp;
        startOut_reg(1) <= startOut_reg(0);
      END IF;
    END IF;
  END PROCESS startOut_process;

  start <= startOut_reg(1);

  
  endTmp <= const1 WHEN validO = '0' ELSE
      endO;

  endOut_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        endOut_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        endOut_reg(0) <= endTmp;
        endOut_reg(1) <= endOut_reg(0);
      END IF;
    END IF;
  END PROCESS endOut_process;

  end_rsvd <= endOut_reg(1);

  
  validTmp <= const1 WHEN validO = '0' ELSE
      validO;

  validOut_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        validOut_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        validOut_reg(0) <= validTmp;
        validOut_reg(1) <= validOut_reg(0);
      END IF;
    END IF;
  END PROCESS validOut_process;

  valid_2 <= validOut_reg(1);

  data_1 <= data_2;

  valid_1 <= valid_2;

END rtl;

