-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_Frame_Synchronizer.vhd
-- Created: 2025-10-27 18:12:30
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_Frame_Synchronizer
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency 
-- and Coarse Phase Synchronizer/Time and Coarse Frequency Synchronizer/Frame Synchronize
-- Hierarchy Level: 6
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_Frame_Synchronizer IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_8_1                         :   IN    std_logic;
        enb_1_32_0                        :   IN    std_logic;
        enb_1_32_1                        :   IN    std_logic;
        enb_1_8_0                         :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
        dataIn_im                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
        validIn                           :   IN    std_logic;
        dataOut_re                        :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
        dataOut_im                        :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
        validOut                          :   OUT   std_logic;
        endOfSOF                          :   OUT   std_logic;
        hasPilots                         :   OUT   std_logic
        );
END dvbs2_ip_src_Frame_Synchronizer;


ARCHITECTURE rtl OF dvbs2_ip_src_Frame_Synchronizer IS

  -- Component Declarations
  COMPONENT dvbs2_ip_src_Correlator
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_8_1                       :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          enb_1_32_1                      :   IN    std_logic;
          enb_1_8_0                       :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
          dataIn_im                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En13
          validIn                         :   IN    std_logic;
          SOFCorrOut_re                   :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          SOFCorrOut_im                   :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          PLSCCorrOut_re                  :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          PLSCCorrOut_im                  :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          threshold                       :   OUT   std_logic_vector(16 DOWNTO 0)  -- sfix17_En14
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_Pilot_and_Sync_Pulse_Indicator
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_32_0                      :   IN    std_logic;
          SOFCorrDelayed_re               :   IN    std_logic_vector(14 DOWNTO 0);  -- sfix15_En12
          SOFCorrDelayed_im               :   IN    std_logic_vector(14 DOWNTO 0);  -- sfix15_En12
          PLSCCorr_re                     :   IN    std_logic_vector(14 DOWNTO 0);  -- sfix15_En11
          PLSCCorr_im                     :   IN    std_logic_vector(14 DOWNTO 0);  -- sfix15_En11
          threshold                       :   IN    std_logic_vector(14 DOWNTO 0);  -- sfix15_En12
          hasPilots                       :   OUT   std_logic;
          thresholdExceeded               :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dvbs2_ip_src_Correlator
    USE ENTITY work.dvbs2_ip_src_Correlator(rtl);

  FOR ALL : dvbs2_ip_src_Pilot_and_Sync_Pulse_Indicator
    USE ENTITY work.dvbs2_ip_src_Pilot_and_Sync_Pulse_Indicator(rtl);

  -- Signals
  SIGNAL dataIn_re_signed                 : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL dataIn_im_signed                 : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay12_reg_re                   : vector_of_signed18(0 TO 1);  -- sfix18_En13 [2]
  SIGNAL Delay12_reg_im                   : vector_of_signed18(0 TO 1);  -- sfix18_En13 [2]
  SIGNAL Delay12_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay12_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay6_reg_re                    : vector_of_signed18(0 TO 8);  -- sfix18_En13 [9]
  SIGNAL Delay6_reg_im                    : vector_of_signed18(0 TO 8);  -- sfix18_En13 [9]
  SIGNAL Delay6_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay6_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay1_reg_re                    : vector_of_signed18(0 TO 69);  -- sfix18_En13 [70]
  SIGNAL Delay1_reg_im                    : vector_of_signed18(0 TO 69);  -- sfix18_En13 [70]
  SIGNAL Delay1_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay1_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay3_reg_re                    : vector_of_signed18(0 TO 63);  -- sfix18_En13 [64]
  SIGNAL Delay3_reg_im                    : vector_of_signed18(0 TO 63);  -- sfix18_En13 [64]
  SIGNAL Delay3_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay3_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay10_reg_re                   : vector_of_signed18(0 TO 8);  -- sfix18_En13 [9]
  SIGNAL Delay10_reg_im                   : vector_of_signed18(0 TO 8);  -- sfix18_En13 [9]
  SIGNAL Delay10_out1_re                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay10_out1_im                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL Delay13_reg                      : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay13_out1                     : std_logic;
  SIGNAL Delay11_reg                      : std_logic_vector(8 DOWNTO 0);  -- ufix1 [9]
  SIGNAL Delay11_out1                     : std_logic;
  SIGNAL Delay2_reg                       : std_logic_vector(69 DOWNTO 0);  -- ufix1 [70]
  SIGNAL Delay2_out1                      : std_logic;
  SIGNAL Delay4_reg                       : std_logic_vector(63 DOWNTO 0);  -- ufix1 [64]
  SIGNAL Delay4_out1                      : std_logic;
  SIGNAL Delay9_reg                       : std_logic_vector(8 DOWNTO 0);  -- ufix1 [9]
  SIGNAL Delay9_out1                      : std_logic;
  SIGNAL Correlator_SOFCorrOut_re         : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL Correlator_SOFCorrOut_im         : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL Correlator_PLSCCorrOut_re        : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL Correlator_PLSCCorrOut_im        : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL Correlator_threshold             : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL Correlator_SOFCorrOut_re_signed  : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Correlator_SOFCorrOut_im_signed  : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay5_reg_re                    : vector_of_signed18(0 TO 63);  -- sfix18_En15 [64]
  SIGNAL Delay5_reg_im                    : vector_of_signed18(0 TO 63);  -- sfix18_En15 [64]
  SIGNAL Delay5_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay5_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Data_Type_Conversion_out1_re     : signed(14 DOWNTO 0);  -- sfix15_En12
  SIGNAL Data_Type_Conversion_out1_im     : signed(14 DOWNTO 0);  -- sfix15_En12
  SIGNAL Correlator_PLSCCorrOut_re_signed : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Correlator_PLSCCorrOut_im_signed : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Data_Type_Conversion1_out1_re    : signed(14 DOWNTO 0);  -- sfix15_En11
  SIGNAL Data_Type_Conversion1_out1_im    : signed(14 DOWNTO 0);  -- sfix15_En11
  SIGNAL Correlator_threshold_signed      : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL Data_Type_Conversion2_out1       : signed(14 DOWNTO 0);  -- sfix15_En12
  SIGNAL Pilot_and_Sync_Pulse_Indicator_hasPilots : std_logic;
  SIGNAL Pilot_and_Sync_Pulse_Indicator_thresholdExceeded : std_logic;

BEGIN
  u_Correlator : dvbs2_ip_src_Correlator
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_8_1 => enb_1_8_1,
              enb_1_32_0 => enb_1_32_0,
              enb_1_32_1 => enb_1_32_1,
              enb_1_8_0 => enb_1_8_0,
              dataIn_re => std_logic_vector(Delay12_out1_re),  -- sfix18_En13
              dataIn_im => std_logic_vector(Delay12_out1_im),  -- sfix18_En13
              validIn => Delay13_out1,
              SOFCorrOut_re => Correlator_SOFCorrOut_re,  -- sfix18_En15
              SOFCorrOut_im => Correlator_SOFCorrOut_im,  -- sfix18_En15
              PLSCCorrOut_re => Correlator_PLSCCorrOut_re,  -- sfix18_En15
              PLSCCorrOut_im => Correlator_PLSCCorrOut_im,  -- sfix18_En15
              threshold => Correlator_threshold  -- sfix17_En14
              );

  u_Pilot_and_Sync_Pulse_Indicator : dvbs2_ip_src_Pilot_and_Sync_Pulse_Indicator
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_32_0 => enb_1_32_0,
              SOFCorrDelayed_re => std_logic_vector(Data_Type_Conversion_out1_re),  -- sfix15_En12
              SOFCorrDelayed_im => std_logic_vector(Data_Type_Conversion_out1_im),  -- sfix15_En12
              PLSCCorr_re => std_logic_vector(Data_Type_Conversion1_out1_re),  -- sfix15_En11
              PLSCCorr_im => std_logic_vector(Data_Type_Conversion1_out1_im),  -- sfix15_En11
              threshold => std_logic_vector(Data_Type_Conversion2_out1),  -- sfix15_En12
              hasPilots => Pilot_and_Sync_Pulse_Indicator_hasPilots,
              thresholdExceeded => Pilot_and_Sync_Pulse_Indicator_thresholdExceeded
              );

  dataIn_re_signed <= signed(dataIn_re);

  dataIn_im_signed <= signed(dataIn_im);

  Delay12_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay12_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay12_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_32_0 = '1' THEN
        Delay12_reg_im(0) <= dataIn_im_signed;
        Delay12_reg_im(1) <= Delay12_reg_im(0);
        Delay12_reg_re(0) <= dataIn_re_signed;
        Delay12_reg_re(1) <= Delay12_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay12_process;

  Delay12_out1_re <= Delay12_reg_re(1);
  Delay12_out1_im <= Delay12_reg_im(1);

  Delay6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay6_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay6_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_32_0 = '1' THEN
        Delay6_reg_im(0) <= Delay12_out1_im;
        Delay6_reg_im(1 TO 8) <= Delay6_reg_im(0 TO 7);
        Delay6_reg_re(0) <= Delay12_out1_re;
        Delay6_reg_re(1 TO 8) <= Delay6_reg_re(0 TO 7);
      END IF;
    END IF;
  END PROCESS Delay6_process;

  Delay6_out1_re <= Delay6_reg_re(8);
  Delay6_out1_im <= Delay6_reg_im(8);

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay1_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_32_0 = '1' THEN
        Delay1_reg_im(0) <= Delay6_out1_im;
        Delay1_reg_im(1 TO 69) <= Delay1_reg_im(0 TO 68);
        Delay1_reg_re(0) <= Delay6_out1_re;
        Delay1_reg_re(1 TO 69) <= Delay1_reg_re(0 TO 68);
      END IF;
    END IF;
  END PROCESS Delay1_process;

  Delay1_out1_re <= Delay1_reg_re(69);
  Delay1_out1_im <= Delay1_reg_im(69);

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay3_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_32_0 = '1' THEN
        Delay3_reg_im(0) <= Delay1_out1_im;
        Delay3_reg_im(1 TO 63) <= Delay3_reg_im(0 TO 62);
        Delay3_reg_re(0) <= Delay1_out1_re;
        Delay3_reg_re(1 TO 63) <= Delay3_reg_re(0 TO 62);
      END IF;
    END IF;
  END PROCESS Delay3_process;

  Delay3_out1_re <= Delay3_reg_re(63);
  Delay3_out1_im <= Delay3_reg_im(63);

  Delay10_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay10_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay10_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_32_0 = '1' THEN
        Delay10_reg_im(0) <= Delay3_out1_im;
        Delay10_reg_im(1 TO 8) <= Delay10_reg_im(0 TO 7);
        Delay10_reg_re(0) <= Delay3_out1_re;
        Delay10_reg_re(1 TO 8) <= Delay10_reg_re(0 TO 7);
      END IF;
    END IF;
  END PROCESS Delay10_process;

  Delay10_out1_re <= Delay10_reg_re(8);
  Delay10_out1_im <= Delay10_reg_im(8);

  dataOut_re <= std_logic_vector(Delay10_out1_re);

  dataOut_im <= std_logic_vector(Delay10_out1_im);

  Delay13_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay13_reg <= (OTHERS => '0');
      ELSIF enb_1_32_0 = '1' THEN
        Delay13_reg(0) <= validIn;
        Delay13_reg(1) <= Delay13_reg(0);
      END IF;
    END IF;
  END PROCESS Delay13_process;

  Delay13_out1 <= Delay13_reg(1);

  Delay11_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay11_reg <= (OTHERS => '0');
      ELSIF enb_1_32_0 = '1' THEN
        Delay11_reg(0) <= Delay13_out1;
        Delay11_reg(8 DOWNTO 1) <= Delay11_reg(7 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay11_process;

  Delay11_out1 <= Delay11_reg(8);

  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_reg <= (OTHERS => '0');
      ELSIF enb_1_32_0 = '1' THEN
        Delay2_reg(0) <= Delay11_out1;
        Delay2_reg(69 DOWNTO 1) <= Delay2_reg(68 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay2_process;

  Delay2_out1 <= Delay2_reg(69);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_reg <= (OTHERS => '0');
      ELSIF enb_1_32_0 = '1' THEN
        Delay4_reg(0) <= Delay2_out1;
        Delay4_reg(63 DOWNTO 1) <= Delay4_reg(62 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay4_process;

  Delay4_out1 <= Delay4_reg(63);

  Delay9_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay9_reg <= (OTHERS => '0');
      ELSIF enb_1_32_0 = '1' THEN
        Delay9_reg(0) <= Delay4_out1;
        Delay9_reg(8 DOWNTO 1) <= Delay9_reg(7 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay9_process;

  Delay9_out1 <= Delay9_reg(8);

  Correlator_SOFCorrOut_re_signed <= signed(Correlator_SOFCorrOut_re);

  Correlator_SOFCorrOut_im_signed <= signed(Correlator_SOFCorrOut_im);

  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay5_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_32_0 = '1' THEN
        Delay5_reg_im(0) <= Correlator_SOFCorrOut_im_signed;
        Delay5_reg_im(1 TO 63) <= Delay5_reg_im(0 TO 62);
        Delay5_reg_re(0) <= Correlator_SOFCorrOut_re_signed;
        Delay5_reg_re(1 TO 63) <= Delay5_reg_re(0 TO 62);
      END IF;
    END IF;
  END PROCESS Delay5_process;

  Delay5_out1_re <= Delay5_reg_re(63);
  Delay5_out1_im <= Delay5_reg_im(63);

  Data_Type_Conversion_out1_re <= Delay5_out1_re(17 DOWNTO 3);
  Data_Type_Conversion_out1_im <= Delay5_out1_im(17 DOWNTO 3);

  Correlator_PLSCCorrOut_re_signed <= signed(Correlator_PLSCCorrOut_re);

  Correlator_PLSCCorrOut_im_signed <= signed(Correlator_PLSCCorrOut_im);

  Data_Type_Conversion1_out1_re <= resize(Correlator_PLSCCorrOut_re_signed(17 DOWNTO 4), 15);
  Data_Type_Conversion1_out1_im <= resize(Correlator_PLSCCorrOut_im_signed(17 DOWNTO 4), 15);

  Correlator_threshold_signed <= signed(Correlator_threshold);

  Data_Type_Conversion2_out1 <= Correlator_threshold_signed(16 DOWNTO 2);

  validOut <= Delay9_out1;

  endOfSOF <= Pilot_and_Sync_Pulse_Indicator_thresholdExceeded;

  hasPilots <= Pilot_and_Sync_Pulse_Indicator_hasPilots;

END rtl;

