-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_FEC_Decoding.vhd
-- Created: 2025-10-27 18:12:27
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_FEC_Decoding
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/FEC Decoding
-- Hierarchy Level: 4
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dvbs2_ip_src_FEC_Decoding IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8_En4
        startIn                           :   IN    std_logic;
        endIn                             :   IN    std_logic;
        validIn                           :   IN    std_logic;
        FECFrame                          :   IN    std_logic;
        codIdx                            :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        bitsOut                           :   OUT   std_logic;
        ctrl_start                        :   OUT   std_logic;
        ctrl_valid                        :   OUT   std_logic
        );
END dvbs2_ip_src_FEC_Decoding;


ARCHITECTURE rtl OF dvbs2_ip_src_FEC_Decoding IS

  -- Component Declarations
  COMPONENT dvbs2_ip_src_Sample_Control_Bus_Creator
    PORT( In1                             :   IN    std_logic;
          In2                             :   IN    std_logic;
          In3                             :   IN    std_logic;
          Out1_start                      :   OUT   std_logic;
          Out1_end                        :   OUT   std_logic;
          Out1_valid                      :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_DVB_S2_LDPC_Decoder
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          in0                             :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8_En4
          in1_start                       :   IN    std_logic;
          in1_end                         :   IN    std_logic;
          in1_valid                       :   IN    std_logic;
          in2                             :   IN    std_logic;
          in3                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          out0                            :   OUT   std_logic;
          out1_start                      :   OUT   std_logic;
          out1_end                        :   OUT   std_logic;
          out1_valid                      :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_DVB_S2_BCH_Decoder
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          in0                             :   IN    std_logic;
          in1_start                       :   IN    std_logic;
          in1_end                         :   IN    std_logic;
          in1_valid                       :   IN    std_logic;
          in2                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          out0                            :   OUT   std_logic;
          out1_start                      :   OUT   std_logic;
          out1_valid                      :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dvbs2_ip_src_Sample_Control_Bus_Creator
    USE ENTITY work.dvbs2_ip_src_Sample_Control_Bus_Creator(rtl);

  FOR ALL : dvbs2_ip_src_DVB_S2_LDPC_Decoder
    USE ENTITY work.dvbs2_ip_src_DVB_S2_LDPC_Decoder(rtl);

  FOR ALL : dvbs2_ip_src_DVB_S2_BCH_Decoder
    USE ENTITY work.dvbs2_ip_src_DVB_S2_BCH_Decoder(rtl);

  -- Signals
  SIGNAL Sample_Control_Bus_Creator_Out1_start : std_logic;
  SIGNAL Sample_Control_Bus_Creator_Out1_end : std_logic;
  SIGNAL Sample_Control_Bus_Creator_Out1_valid : std_logic;
  SIGNAL DVB_S2_LDPC_Decoder_out1         : std_logic;
  SIGNAL DVB_S2_LDPC_Decoder_out2_start   : std_logic;
  SIGNAL DVB_S2_LDPC_Decoder_out2_end     : std_logic;
  SIGNAL DVB_S2_LDPC_Decoder_out2_valid   : std_logic;
  SIGNAL DVB_S2_BCH_Decoder_out1          : std_logic;
  SIGNAL DVB_S2_BCH_Decoder_out2_start    : std_logic;
  SIGNAL DVB_S2_BCH_Decoder_out2_valid    : std_logic;

BEGIN
  u_Sample_Control_Bus_Creator : dvbs2_ip_src_Sample_Control_Bus_Creator
    PORT MAP( In1 => startIn,
              In2 => endIn,
              In3 => validIn,
              Out1_start => Sample_Control_Bus_Creator_Out1_start,
              Out1_end => Sample_Control_Bus_Creator_Out1_end,
              Out1_valid => Sample_Control_Bus_Creator_Out1_valid
              );

  u_DVB_S2_LDPC_Decoder : dvbs2_ip_src_DVB_S2_LDPC_Decoder
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              in0 => dataIn,  -- sfix8_En4
              in1_start => Sample_Control_Bus_Creator_Out1_start,
              in1_end => Sample_Control_Bus_Creator_Out1_end,
              in1_valid => Sample_Control_Bus_Creator_Out1_valid,
              in2 => FECFrame,
              in3 => codIdx,  -- ufix4
              out0 => DVB_S2_LDPC_Decoder_out1,
              out1_start => DVB_S2_LDPC_Decoder_out2_start,
              out1_end => DVB_S2_LDPC_Decoder_out2_end,
              out1_valid => DVB_S2_LDPC_Decoder_out2_valid
              );

  u_DVB_S2_BCH_Decoder : dvbs2_ip_src_DVB_S2_BCH_Decoder
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              in0 => DVB_S2_LDPC_Decoder_out1,
              in1_start => DVB_S2_LDPC_Decoder_out2_start,
              in1_end => DVB_S2_LDPC_Decoder_out2_end,
              in1_valid => DVB_S2_LDPC_Decoder_out2_valid,
              in2 => codIdx,  -- ufix4
              out0 => DVB_S2_BCH_Decoder_out1,
              out1_start => DVB_S2_BCH_Decoder_out2_start,
              out1_valid => DVB_S2_BCH_Decoder_out2_valid
              );

  bitsOut <= DVB_S2_BCH_Decoder_out1;

  ctrl_start <= DVB_S2_BCH_Decoder_out2_start;

  ctrl_valid <= DVB_S2_BCH_Decoder_out2_valid;

END rtl;

