-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_FilterCoef_block2.vhd
-- Created: 2025-10-27 18:12:30
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_FilterCoef_block2
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Prepare Outputs/Discrete FIR Filter HDL Optimized/Filter/FilterCoef
-- Hierarchy Level: 5
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_FilterCoef_block2 IS
  PORT( CoefOut                           :   OUT   vector_of_std_logic_vector18(0 TO 69)  -- sfix18_En20 [70]
        );
END dvbs2_ip_src_FilterCoef_block2;


ARCHITECTURE rtl OF dvbs2_ip_src_FilterCoef_block2 IS

  -- Signals
  SIGNAL CoefData                         : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_1                       : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_2                       : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_3                       : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_4                       : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_5                       : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_6                       : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_7                       : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_8                       : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_9                       : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_10                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_11                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_12                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_13                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_14                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_15                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_16                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_17                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_18                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_19                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_20                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_21                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_22                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_23                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_24                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_25                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_26                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_27                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_28                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_29                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_30                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_31                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_32                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_33                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_34                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_35                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_36                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_37                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_38                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_39                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_40                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_41                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_42                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_43                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_44                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_45                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_46                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_47                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_48                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_49                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_50                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_51                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_52                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_53                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_54                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_55                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_56                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_57                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_58                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_59                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_60                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_61                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_62                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_63                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_64                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_65                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_66                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_67                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_68                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefData_69                      : signed(17 DOWNTO 0);  -- sfix18_En20
  SIGNAL CoefOut_tmp                      : vector_of_signed18(0 TO 69);  -- sfix18_En20 [70]

BEGIN
  -- CoefReg_1
  CoefData <= to_signed(16#00000#, 18);

  -- CoefReg_2
  CoefData_1 <= to_signed(16#00000#, 18);

  -- CoefReg_3
  CoefData_2 <= to_signed(-16#00002#, 18);

  -- CoefReg_4
  CoefData_3 <= to_signed(-16#00006#, 18);

  -- CoefReg_5
  CoefData_4 <= to_signed(-16#00010#, 18);

  -- CoefReg_6
  CoefData_5 <= to_signed(-16#00027#, 18);

  -- CoefReg_7
  CoefData_6 <= to_signed(-16#00053#, 18);

  -- CoefReg_8
  CoefData_7 <= to_signed(-16#000A5#, 18);

  -- CoefReg_9
  CoefData_8 <= to_signed(-16#00130#, 18);

  -- CoefReg_10
  CoefData_9 <= to_signed(-16#0020E#, 18);

  -- CoefReg_11
  CoefData_10 <= to_signed(-16#0035C#, 18);

  -- CoefReg_12
  CoefData_11 <= to_signed(-16#00537#, 18);

  -- CoefReg_13
  CoefData_12 <= to_signed(-16#007B8#, 18);

  -- CoefReg_14
  CoefData_13 <= to_signed(-16#00AE8#, 18);

  -- CoefReg_15
  CoefData_14 <= to_signed(-16#00EBD#, 18);

  -- CoefReg_16
  CoefData_15 <= to_signed(-16#0130B#, 18);

  -- CoefReg_17
  CoefData_16 <= to_signed(-16#0177D#, 18);

  -- CoefReg_18
  CoefData_17 <= to_signed(-16#01B8F#, 18);

  -- CoefReg_19
  CoefData_18 <= to_signed(-16#01E8B#, 18);

  -- CoefReg_20
  CoefData_19 <= to_signed(-16#01F8F#, 18);

  -- CoefReg_21
  CoefData_20 <= to_signed(-16#01D9B#, 18);

  -- CoefReg_22
  CoefData_21 <= to_signed(-16#017A5#, 18);

  -- CoefReg_23
  CoefData_22 <= to_signed(-16#00CB3#, 18);

  -- CoefReg_24
  CoefData_23 <= to_signed(16#00400#, 18);

  -- CoefReg_25
  CoefData_24 <= to_signed(16#01AE5#, 18);

  -- CoefReg_26
  CoefData_25 <= to_signed(16#037FA#, 18);

  -- CoefReg_27
  CoefData_26 <= to_signed(16#05AB5#, 18);

  -- CoefReg_28
  CoefData_27 <= to_signed(16#081F5#, 18);

  -- CoefReg_29
  CoefData_28 <= to_signed(16#0AC11#, 18);

  -- CoefReg_30
  CoefData_29 <= to_signed(16#0D6E7#, 18);

  -- CoefReg_31
  CoefData_30 <= to_signed(16#10004#, 18);

  -- CoefReg_32
  CoefData_31 <= to_signed(16#124DC#, 18);

  -- CoefReg_33
  CoefData_32 <= to_signed(16#14301#, 18);

  -- CoefReg_34
  CoefData_33 <= to_signed(16#15861#, 18);

  -- CoefReg_35
  CoefData_34 <= to_signed(16#16377#, 18);

  -- CoefReg_36
  CoefData_35 <= to_signed(16#16377#, 18);

  -- CoefReg_37
  CoefData_36 <= to_signed(16#15861#, 18);

  -- CoefReg_38
  CoefData_37 <= to_signed(16#14301#, 18);

  -- CoefReg_39
  CoefData_38 <= to_signed(16#124DC#, 18);

  -- CoefReg_40
  CoefData_39 <= to_signed(16#10004#, 18);

  -- CoefReg_41
  CoefData_40 <= to_signed(16#0D6E7#, 18);

  -- CoefReg_42
  CoefData_41 <= to_signed(16#0AC11#, 18);

  -- CoefReg_43
  CoefData_42 <= to_signed(16#081F5#, 18);

  -- CoefReg_44
  CoefData_43 <= to_signed(16#05AB5#, 18);

  -- CoefReg_45
  CoefData_44 <= to_signed(16#037FA#, 18);

  -- CoefReg_46
  CoefData_45 <= to_signed(16#01AE5#, 18);

  -- CoefReg_47
  CoefData_46 <= to_signed(16#00400#, 18);

  -- CoefReg_48
  CoefData_47 <= to_signed(-16#00CB3#, 18);

  -- CoefReg_49
  CoefData_48 <= to_signed(-16#017A5#, 18);

  -- CoefReg_50
  CoefData_49 <= to_signed(-16#01D9B#, 18);

  -- CoefReg_51
  CoefData_50 <= to_signed(-16#01F8F#, 18);

  -- CoefReg_52
  CoefData_51 <= to_signed(-16#01E8B#, 18);

  -- CoefReg_53
  CoefData_52 <= to_signed(-16#01B8F#, 18);

  -- CoefReg_54
  CoefData_53 <= to_signed(-16#0177D#, 18);

  -- CoefReg_55
  CoefData_54 <= to_signed(-16#0130B#, 18);

  -- CoefReg_56
  CoefData_55 <= to_signed(-16#00EBD#, 18);

  -- CoefReg_57
  CoefData_56 <= to_signed(-16#00AE8#, 18);

  -- CoefReg_58
  CoefData_57 <= to_signed(-16#007B8#, 18);

  -- CoefReg_59
  CoefData_58 <= to_signed(-16#00537#, 18);

  -- CoefReg_60
  CoefData_59 <= to_signed(-16#0035C#, 18);

  -- CoefReg_61
  CoefData_60 <= to_signed(-16#0020E#, 18);

  -- CoefReg_62
  CoefData_61 <= to_signed(-16#00130#, 18);

  -- CoefReg_63
  CoefData_62 <= to_signed(-16#000A5#, 18);

  -- CoefReg_64
  CoefData_63 <= to_signed(-16#00053#, 18);

  -- CoefReg_65
  CoefData_64 <= to_signed(-16#00027#, 18);

  -- CoefReg_66
  CoefData_65 <= to_signed(-16#00010#, 18);

  -- CoefReg_67
  CoefData_66 <= to_signed(-16#00006#, 18);

  -- CoefReg_68
  CoefData_67 <= to_signed(-16#00002#, 18);

  -- CoefReg_69
  CoefData_68 <= to_signed(16#00000#, 18);

  -- CoefReg_70
  CoefData_69 <= to_signed(16#00000#, 18);

  CoefOut_tmp(0) <= CoefData;
  CoefOut_tmp(1) <= CoefData_1;
  CoefOut_tmp(2) <= CoefData_2;
  CoefOut_tmp(3) <= CoefData_3;
  CoefOut_tmp(4) <= CoefData_4;
  CoefOut_tmp(5) <= CoefData_5;
  CoefOut_tmp(6) <= CoefData_6;
  CoefOut_tmp(7) <= CoefData_7;
  CoefOut_tmp(8) <= CoefData_8;
  CoefOut_tmp(9) <= CoefData_9;
  CoefOut_tmp(10) <= CoefData_10;
  CoefOut_tmp(11) <= CoefData_11;
  CoefOut_tmp(12) <= CoefData_12;
  CoefOut_tmp(13) <= CoefData_13;
  CoefOut_tmp(14) <= CoefData_14;
  CoefOut_tmp(15) <= CoefData_15;
  CoefOut_tmp(16) <= CoefData_16;
  CoefOut_tmp(17) <= CoefData_17;
  CoefOut_tmp(18) <= CoefData_18;
  CoefOut_tmp(19) <= CoefData_19;
  CoefOut_tmp(20) <= CoefData_20;
  CoefOut_tmp(21) <= CoefData_21;
  CoefOut_tmp(22) <= CoefData_22;
  CoefOut_tmp(23) <= CoefData_23;
  CoefOut_tmp(24) <= CoefData_24;
  CoefOut_tmp(25) <= CoefData_25;
  CoefOut_tmp(26) <= CoefData_26;
  CoefOut_tmp(27) <= CoefData_27;
  CoefOut_tmp(28) <= CoefData_28;
  CoefOut_tmp(29) <= CoefData_29;
  CoefOut_tmp(30) <= CoefData_30;
  CoefOut_tmp(31) <= CoefData_31;
  CoefOut_tmp(32) <= CoefData_32;
  CoefOut_tmp(33) <= CoefData_33;
  CoefOut_tmp(34) <= CoefData_34;
  CoefOut_tmp(35) <= CoefData_35;
  CoefOut_tmp(36) <= CoefData_36;
  CoefOut_tmp(37) <= CoefData_37;
  CoefOut_tmp(38) <= CoefData_38;
  CoefOut_tmp(39) <= CoefData_39;
  CoefOut_tmp(40) <= CoefData_40;
  CoefOut_tmp(41) <= CoefData_41;
  CoefOut_tmp(42) <= CoefData_42;
  CoefOut_tmp(43) <= CoefData_43;
  CoefOut_tmp(44) <= CoefData_44;
  CoefOut_tmp(45) <= CoefData_45;
  CoefOut_tmp(46) <= CoefData_46;
  CoefOut_tmp(47) <= CoefData_47;
  CoefOut_tmp(48) <= CoefData_48;
  CoefOut_tmp(49) <= CoefData_49;
  CoefOut_tmp(50) <= CoefData_50;
  CoefOut_tmp(51) <= CoefData_51;
  CoefOut_tmp(52) <= CoefData_52;
  CoefOut_tmp(53) <= CoefData_53;
  CoefOut_tmp(54) <= CoefData_54;
  CoefOut_tmp(55) <= CoefData_55;
  CoefOut_tmp(56) <= CoefData_56;
  CoefOut_tmp(57) <= CoefData_57;
  CoefOut_tmp(58) <= CoefData_58;
  CoefOut_tmp(59) <= CoefData_59;
  CoefOut_tmp(60) <= CoefData_60;
  CoefOut_tmp(61) <= CoefData_61;
  CoefOut_tmp(62) <= CoefData_62;
  CoefOut_tmp(63) <= CoefData_63;
  CoefOut_tmp(64) <= CoefData_64;
  CoefOut_tmp(65) <= CoefData_65;
  CoefOut_tmp(66) <= CoefData_66;
  CoefOut_tmp(67) <= CoefData_67;
  CoefOut_tmp(68) <= CoefData_68;
  CoefOut_tmp(69) <= CoefData_69;

  outputgen: FOR k IN 0 TO 69 GENERATE
    CoefOut(k) <= std_logic_vector(CoefOut_tmp(k));
  END GENERATE;

END rtl;

