-- -------------------------------------------------------------
-- 
-- File Name: C:\demo\DVBS2ReceiverSoCExample\soc_prj\hdlcoder\DVBS2\hdlsrc\soc_dvbs2_fpga\dvbs2_ip_src_Digital_Automatic_Gain_Control.vhd
-- Created: 2025-10-27 18:12:30
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvbs2_ip_src_Digital_Automatic_Gain_Control
-- Source Path: soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Digital Automatic Gain Control
-- Hierarchy Level: 2
-- Model version: 9.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.dvbs2_ip_src_DVBS2_pkg.ALL;

ENTITY dvbs2_ip_src_Digital_Automatic_Gain_Control IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_8_0                         :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        dataIn_im                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        validIn                           :   IN    std_logic;
        dataOut_re                        :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        dataOut_im                        :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        validOut                          :   OUT   std_logic
        );
END dvbs2_ip_src_Digital_Automatic_Gain_Control;


ARCHITECTURE rtl OF dvbs2_ip_src_Digital_Automatic_Gain_Control IS

  -- Component Declarations
  COMPONENT dvbs2_ip_src_Error_Detector
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_8_0                       :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          dataIn_im                       :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          err                             :   OUT   std_logic_vector(36 DOWNTO 0)  -- sfix37_En30
          );
  END COMPONENT;

  COMPONENT dvbs2_ip_src_Loop_Filter_block2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_8_0                       :   IN    std_logic;
          err                             :   IN    std_logic_vector(36 DOWNTO 0);  -- sfix37_En30
          gain                            :   OUT   std_logic_vector(36 DOWNTO 0)  -- sfix37_En30
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dvbs2_ip_src_Error_Detector
    USE ENTITY work.dvbs2_ip_src_Error_Detector(rtl);

  FOR ALL : dvbs2_ip_src_Loop_Filter_block2
    USE ENTITY work.dvbs2_ip_src_Loop_Filter_block2(rtl);

  -- Signals
  SIGNAL dataIn_re_signed                 : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL dataIn_im_signed                 : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay7_reg_re                    : vector_of_signed18(0 TO 1);  -- sfix18_En15 [2]
  SIGNAL Delay7_reg_im                    : vector_of_signed18(0 TO 1);  -- sfix18_En15 [2]
  SIGNAL Delay7_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay7_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay4_reg_re                    : vector_of_signed18(0 TO 1);  -- sfix18_En15 [2]
  SIGNAL Delay4_reg_im                    : vector_of_signed18(0 TO 1);  -- sfix18_En15 [2]
  SIGNAL Delay4_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay4_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay2_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay2_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Error_Detector_err               : std_logic_vector(36 DOWNTO 0);  -- ufix37
  SIGNAL Loop_Filter_gain                 : std_logic_vector(36 DOWNTO 0);  -- ufix37
  SIGNAL Loop_Filter_gain_signed          : signed(36 DOWNTO 0);  -- sfix37_En30
  SIGNAL Delay1_reg                       : vector_of_signed37(0 TO 1);  -- sfix37 [2]
  SIGNAL Delay1_out1                      : signed(36 DOWNTO 0);  -- sfix37_En30
  SIGNAL Product_out1_re                  : signed(54 DOWNTO 0);  -- sfix55_En45
  SIGNAL Product_out1_im                  : signed(54 DOWNTO 0);  -- sfix55_En45
  SIGNAL Data_Type_Conversion_out1_re     : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Data_Type_Conversion_out1_im     : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay2_reg_re                    : vector_of_signed18(0 TO 1);  -- sfix18_En15 [2]
  SIGNAL Delay2_reg_im                    : vector_of_signed18(0 TO 1);  -- sfix18_En15 [2]
  SIGNAL Delay8_reg_re                    : vector_of_signed18(0 TO 1);  -- sfix18_En15 [2]
  SIGNAL Delay8_reg_im                    : vector_of_signed18(0 TO 1);  -- sfix18_En15 [2]
  SIGNAL Delay8_out1_re                   : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay8_out1_im                   : signed(17 DOWNTO 0);  -- sfix18_En15
  SIGNAL Delay6_reg                       : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay6_out1                      : std_logic;
  SIGNAL Delay5_reg                       : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay5_out1                      : std_logic;
  SIGNAL Delay3_reg                       : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay3_out1                      : std_logic;
  SIGNAL Delay9_reg                       : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay9_out1                      : std_logic;

BEGIN
  u_Error_Detector : dvbs2_ip_src_Error_Detector
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_8_0 => enb_1_8_0,
              dataIn_re => std_logic_vector(Delay2_out1_re),  -- sfix18_En15
              dataIn_im => std_logic_vector(Delay2_out1_im),  -- sfix18_En15
              err => Error_Detector_err  -- sfix37_En30
              );

  u_Loop_Filter : dvbs2_ip_src_Loop_Filter_block2
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_8_0 => enb_1_8_0,
              err => Error_Detector_err,  -- sfix37_En30
              gain => Loop_Filter_gain  -- sfix37_En30
              );

  dataIn_re_signed <= signed(dataIn_re);

  dataIn_im_signed <= signed(dataIn_im);

  Delay7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay7_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay7_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_8_0 = '1' THEN
        Delay7_reg_im(0) <= dataIn_im_signed;
        Delay7_reg_im(1) <= Delay7_reg_im(0);
        Delay7_reg_re(0) <= dataIn_re_signed;
        Delay7_reg_re(1) <= Delay7_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay7_process;

  Delay7_out1_re <= Delay7_reg_re(1);
  Delay7_out1_im <= Delay7_reg_im(1);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay4_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_8_0 = '1' THEN
        Delay4_reg_im(0) <= Delay7_out1_im;
        Delay4_reg_im(1) <= Delay4_reg_im(0);
        Delay4_reg_re(0) <= Delay7_out1_re;
        Delay4_reg_re(1) <= Delay4_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay4_process;

  Delay4_out1_re <= Delay4_reg_re(1);
  Delay4_out1_im <= Delay4_reg_im(1);

  Loop_Filter_gain_signed <= signed(Loop_Filter_gain);

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_reg <= (OTHERS => to_signed(0, 37));
      ELSIF enb_1_8_0 = '1' THEN
        Delay1_reg(0) <= Loop_Filter_gain_signed;
        Delay1_reg(1) <= Delay1_reg(0);
      END IF;
    END IF;
  END PROCESS Delay1_process;

  Delay1_out1 <= Delay1_reg(1);

  Product_out1_re <= Delay4_out1_re * Delay1_out1;
  Product_out1_im <= Delay4_out1_im * Delay1_out1;

  Data_Type_Conversion_out1_re <= Product_out1_re(47 DOWNTO 30);
  Data_Type_Conversion_out1_im <= Product_out1_im(47 DOWNTO 30);

  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay2_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_8_0 = '1' THEN
        Delay2_reg_im(0) <= Data_Type_Conversion_out1_im;
        Delay2_reg_im(1) <= Delay2_reg_im(0);
        Delay2_reg_re(0) <= Data_Type_Conversion_out1_re;
        Delay2_reg_re(1) <= Delay2_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay2_process;

  Delay2_out1_re <= Delay2_reg_re(1);
  Delay2_out1_im <= Delay2_reg_im(1);

  Delay8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay8_reg_re <= (OTHERS => to_signed(16#00000#, 18));
        Delay8_reg_im <= (OTHERS => to_signed(16#00000#, 18));
      ELSIF enb_1_8_0 = '1' THEN
        Delay8_reg_im(0) <= Delay2_out1_im;
        Delay8_reg_im(1) <= Delay8_reg_im(0);
        Delay8_reg_re(0) <= Delay2_out1_re;
        Delay8_reg_re(1) <= Delay8_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay8_process;

  Delay8_out1_re <= Delay8_reg_re(1);
  Delay8_out1_im <= Delay8_reg_im(1);

  dataOut_re <= std_logic_vector(Delay8_out1_re);

  dataOut_im <= std_logic_vector(Delay8_out1_im);

  Delay6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay6_reg <= (OTHERS => '0');
      ELSIF enb_1_8_0 = '1' THEN
        Delay6_reg(0) <= validIn;
        Delay6_reg(1) <= Delay6_reg(0);
      END IF;
    END IF;
  END PROCESS Delay6_process;

  Delay6_out1 <= Delay6_reg(1);

  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_reg <= (OTHERS => '0');
      ELSIF enb_1_8_0 = '1' THEN
        Delay5_reg(0) <= Delay6_out1;
        Delay5_reg(1) <= Delay5_reg(0);
      END IF;
    END IF;
  END PROCESS Delay5_process;

  Delay5_out1 <= Delay5_reg(1);

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_reg <= (OTHERS => '0');
      ELSIF enb_1_8_0 = '1' THEN
        Delay3_reg(0) <= Delay5_out1;
        Delay3_reg(1) <= Delay3_reg(0);
      END IF;
    END IF;
  END PROCESS Delay3_process;

  Delay3_out1 <= Delay3_reg(1);

  Delay9_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay9_reg <= (OTHERS => '0');
      ELSIF enb_1_8_0 = '1' THEN
        Delay9_reg(0) <= Delay3_out1;
        Delay9_reg(1) <= Delay9_reg(0);
      END IF;
    END IF;
  END PROCESS Delay9_process;

  Delay9_out1 <= Delay9_reg(1);

  validOut <= Delay9_out1;

END rtl;

