cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Data Type Conversion','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/Bit Concat','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/Delay18','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/Delay19','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Delay28','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Delay40','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Delay57','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Delay60','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Generate and Add Read Base Address/No HDL Read Address Debug Scope','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Parameter Store FIFO/Delay21','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Parameter Store FIFO/Delay22','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Parameter Store FIFO/Delay23','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Parameter Store FIFO/Delay24','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Parameter Store FIFO/Delay25','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Parameter Store FIFO/Delay26','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Parameter Store FIFO/Delay27','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Parameter Store FIFO/Delay28','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Parameter Store FIFO/Delay29','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Parameter Store FIFO/Simple Dual Port RAM2','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/Write Offset Address/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM Address Generator/nRows and nColumns/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM/Wrap Address/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/RAM/Wrap Address/Data Type Duplicate1','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/DVBS2 HDL Deinterleaver/modIdxReg','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/Discard Unsupported Frames/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/Discard Unsupported Frames/Delay','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/Discard Unsupported Frames/Delay1','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/FEC Decoding/Bus Selector','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/FEC Decoding/Logical Operator2','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/FEC Decoding/Logical Operator3','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/FEC Decoding/Logical Operator4','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/FEC Decoding/Logical Operator5','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/Symbol Demodulaor/Delay','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/Symbol Demodulaor/Logical Operator','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Demod Deinterleave and FECDecode/Symbol Demodulaor/Logical Operator1','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/No HDL','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/No HDL2','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Repeat','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Repeat2','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Bit Concat','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Delay51','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Delay52','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Delay53','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Delay54','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Delay55','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Delay67','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Extract BBHeader/Extract MATYPE2','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Extract Stream/Constant','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Extract Stream/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Extract Stream/Insert SYNC/Delay10','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Extract Stream/Insert SYNC/Delay16','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Extract Stream/Insert SYNC/Delay5','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Extract Stream/Switch4','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Stream Recovery/BB Decoder/Logical Operator2','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Delay','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Delay1','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Delay2','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Delay22','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Delay23','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Fine Phase Synchronizer/Power Q and Beta Offset Rotation/Complex Multiplier/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Fine Phase Synchronizer/Power Q and Beta Offset Rotation/Complex Multiplier1/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Fine Phase Synchronizer/Power Q and Beta Offset Rotation/Complex Multiplier2/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Fine Phase Synchronizer/Power Q and Beta Offset Rotation/Gain/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Fine Phase Synchronizer/Power Q and Beta Offset Rotation/Gain1/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/No HDL1','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Compute Euclidean Distance/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Delay','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Delay8','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Euclidean Distance Sum Up/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Get Min Index/Delay1','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Get Min Index/Delay2','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Get Min Index/Delay3','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Get Min Index/Delay4','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Get Min Index/Delay5','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Get Min Index/Delay6','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Coarse Phase Synchronizer/Coarse Phase Estimator/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Delay19','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 1 to 6/Compute R(m)_1/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 1 to 6/Compute R(m)_2/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 1 to 6/Compute R(m)_3/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 1 to 6/Compute R(m)_4/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 1 to 6/Compute R(m)_5/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 1 to 6/Compute R(m)_6/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 13 to 18/Compute R(m)_1/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 13 to 18/Compute R(m)_2/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 13 to 18/Compute R(m)_3/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 13 to 18/Compute R(m)_4/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 13 to 18/Compute R(m)_5/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 13 to 18/Compute R(m)_6/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 7 to 12/Compute R(m)_1/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 7 to 12/Compute R(m)_2/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 7 to 12/Compute R(m)_3/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 7 to 12/Compute R(m)_4/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 7 to 12/Compute R(m)_5/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/L and R Algorithm 18 point/Compute R(m) for 7 to 12/Compute R(m)_6/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Frequency Synchronizer/Modified L and R Algorithm/Moving Average/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Gain Control/Delay27','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Gain Control/Delay35','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Gain Control/Reciprocal/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Time and Coarse Frequency Synchronizer/Frame Synchronizer/Pilot and Sync Pulse Indicator/No HDL Correlation Value','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Time and Coarse Frequency Synchronizer/Symbol Synchronizer/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Add','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Complex to Real-Imag','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Constant','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Constant1','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Data Type Conversion','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Delay1','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Delay10','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Delay17','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Delay21','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Delay22','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Delay23','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Delay5','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Delay6','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Delay7','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Delay8','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Delay9','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Math Function','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Moving Average ','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Moving Average /Add1','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Moving Average /Add2','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Moving Average /Data Type Conversion','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Moving Average /Delay','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Moving Average /Delay1','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Moving Average /Delay2','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Moving Average /Delay22','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Moving Average /Delay3','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Moving Average /Delay4','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Moving Average /Delay5','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Moving Average /Gain','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Product','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Variance Estimator/Switch','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Digital Automatic Gain Control/Data Type Propagation','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Digital Automatic Gain Control/Error Detector/Data Type Duplicate','user1');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/HDL Counter','user1');
