open_system('soc_dvbs2_fpga');
open_system('gm_soc_dvbs2_fpga');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Code Word LUT 1 to 32', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Code Word LUT 1 to 32', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Code Word LUT 1 to 32', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Code Word LUT 1 to 32', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Code Word LUT 33 to 64', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Code Word LUT 33 to 64', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Code Word LUT 33 to 64', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/PL Header Recovery/PL Header Decoder/ML Decoder/Code Word LUT 33 to 64', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Coarse Phase Synchronizer/Coarse Phase Corrector/Reciprocal/Function Impl/LUT1', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Coarse Phase Synchronizer/Coarse Phase Corrector/Reciprocal/Function Impl/LUT1', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Coarse Phase Synchronizer/Coarse Phase Corrector/Reciprocal/Function Impl/LUT1', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Coarse Phase Synchronizer/Coarse Phase Corrector/Reciprocal/Function Impl/LUT1', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Coarse Phase Synchronizer/Coarse Phase Corrector/Reciprocal/Function Impl/LUT2', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Coarse Phase Synchronizer/Coarse Phase Corrector/Reciprocal/Function Impl/LUT2', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Coarse Phase Synchronizer/Coarse Phase Corrector/Reciprocal/Function Impl/LUT2', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Coarse Phase Synchronizer/Coarse Phase Corrector/Reciprocal/Function Impl/LUT2', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Gain Control/Reciprocal/Function Impl/LUT1', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Gain Control/Reciprocal/Function Impl/LUT1', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Gain Control/Reciprocal/Function Impl/LUT1', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Gain Control/Reciprocal/Function Impl/LUT1', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Gain Control/Reciprocal/Function Impl/LUT2', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Gain Control/Reciprocal/Function Impl/LUT2', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Gain Control/Reciprocal/Function Impl/LUT2', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Fine Gain Control/Reciprocal/Function Impl/LUT2', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/BER/Send Payload Data/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/BER/Send Payload Data/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/BER/Send Payload Data/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/BER/Send Payload Data/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SinCos/Sine HDL Optimized1/cosine hdl/Look-Up Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SinCos/Sine HDL Optimized1/cosine hdl/Look-Up Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SinCos/Sine HDL Optimized2/sine hdl/Look-Up Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SinCos/Sine HDL Optimized2/sine hdl/Look-Up Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table1/1-D Lookup Table1', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table1/1-D Lookup Table1', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table1', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table1', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table2/1-D Lookup Table2', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table2/1-D Lookup Table2', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table2', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table2', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table3/1-D Lookup Table3', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table3/1-D Lookup Table3', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table3', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/Channel/AWGN Generator/Unit Variance Gaussian Noise/SqrtImplementation/SqrtEval/FunctionEvaluation/1-D Lookup Table3', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Time and Coarse Frequency Synchronizer/PL Data Descrambler and Pilot Valid Indicator/PL Data Descrambler/PL Scramble Sequence Mapper LUT/PL Scramble Sequence Mapper LUT', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Time and Coarse Frequency Synchronizer/PL Data Descrambler and Pilot Valid Indicator/PL Data Descrambler/PL Scramble Sequence Mapper LUT/PL Scramble Sequence Mapper LUT', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Time and Coarse Frequency Synchronizer/PL Data Descrambler and Pilot Valid Indicator/PL Data Descrambler/PL Scramble Sequence Mapper LUT', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Time and Coarse Frequency Synchronizer/PL Data Descrambler and Pilot Valid Indicator/PL Data Descrambler/PL Scramble Sequence Mapper LUT', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Time and Coarse Frequency Synchronizer/PL Data Descrambler and Pilot Valid Indicator/PL Data Descrambler/PL Scramble Sequence Mapper LUT/PL Scramble Sequence Mapper LUT', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Time and Coarse Frequency Synchronizer/PL Data Descrambler and Pilot Valid Indicator/PL Data Descrambler/PL Scramble Sequence Mapper LUT/PL Scramble Sequence Mapper LUT', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Time and Coarse Frequency Synchronizer/PL Data Descrambler and Pilot Valid Indicator/PL Data Descrambler/PL Scramble Sequence Mapper LUT', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/DVB-S2 HDL Receiver/Synchronizer and PL Header Decoder/Time Frequency and Coarse Phase Synchronizer/Time and Coarse Frequency Synchronizer/PL Data Descrambler and Pilot Valid Indicator/PL Data Descrambler/PL Scramble Sequence Mapper LUT', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT1/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT1/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT1/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT1/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT1/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT1/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT1/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT1/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT2/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT2/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT2/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT2/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT2/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT2/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT2/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT2/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT3/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT3/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT3/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT3/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT3/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT3/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT3/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT3/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT4/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT4/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT4/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT4/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT4/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT4/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT4/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT4/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT5/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT5/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT5/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT5/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT5/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT5/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT5/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT5/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT6/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT6/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT6/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT6/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT6/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT6/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT6/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem/txLUT6/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT1/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT1/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT1/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT1/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT1/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT1/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT1/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT1/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT2/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT2/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT2/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT2/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT2/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT2/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT2/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT2/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT3/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT3/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT3/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT3/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT3/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT3/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT3/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT3/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT4/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT4/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT4/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT4/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT4/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT4/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT4/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT4/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT5/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT5/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT5/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT5/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT5/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT5/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT5/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT5/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT6/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT6/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT6/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT6/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT6/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT6/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT6/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem1/txLUT6/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT1/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT1/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT1/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT1/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT1/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT1/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT1/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT1/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT2/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT2/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT2/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT2/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT2/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT2/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT2/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT2/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT3/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT3/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT3/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT3/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT3/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT3/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT3/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT3/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT4/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT4/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT4/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT4/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT4/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT4/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT4/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT4/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT5/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT5/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT5/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT5/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT5/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT5/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT5/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT5/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT6/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT6/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT6/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT6/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT6/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT6/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT6/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem2/txLUT6/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT1/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT1/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT1/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT1/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT1/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT1/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT1/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT1/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT2/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT2/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT2/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT2/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT2/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT2/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT2/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT2/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT3/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT3/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT3/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT3/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT3/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT3/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT3/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT3/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT4/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT4/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT4/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT4/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT4/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT4/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT4/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT4/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT5/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT5/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT5/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT5/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT5/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT5/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT5/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT5/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT6/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT6/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT6/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT6/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT6/1-D Lookup Table/1-D Lookup Table', 'user1');
annotate_port('gm_soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT6/1-D Lookup Table/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
hilite_system('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT6/1-D Lookup Table', 'user1');
annotate_port('soc_dvbs2_fpga/DVBS2/DVBS2 TxRx/LUT Based Tx/Subsystem1/Subsystem4/txLUT6/1-D Lookup Table', 0, 1, 'Lookup Table mapped to RAM');
