create_clock -period 10.000 -name sysclk -waveform {0.000 5.000} [get_ports sysclk]
set_property PACKAGE_PIN E3 [get_ports sysclk]
set_property IOSTANDARD LVCMOS33 [get_ports sysclk]
set_property PACKAGE_PIN G18 [get_ports ETH_CLK25]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_CLK25]
set_property PACKAGE_PIN D17 [get_ports ETH_COL]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_COL]
set_property PACKAGE_PIN G14 [get_ports ETH_CRS]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_CRS]
set_property PACKAGE_PIN F16 [get_ports ETH_MDC]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_MDC]
set_property PACKAGE_PIN K13 [get_ports ETH_MDIO]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_MDIO]
set_property PACKAGE_PIN C16 [get_ports ETH_RESET_n]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RESET_n]
set_property PACKAGE_PIN F15 [get_ports ETH_RXCLK]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RXCLK]
set_property PACKAGE_PIN D18 [get_ports ETH_RXD[0]]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RXD[0]]
set_property PACKAGE_PIN E17 [get_ports ETH_RXD[1]]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RXD[1]]
set_property PACKAGE_PIN E18 [get_ports ETH_RXD[2]]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RXD[2]]
set_property PACKAGE_PIN G17 [get_ports ETH_RXD[3]]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RXD[3]]
set_property PACKAGE_PIN G16 [get_ports ETH_RXDV]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RXDV]
set_property PACKAGE_PIN C17 [get_ports ETH_RXER]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RXER]
set_property PACKAGE_PIN H16 [get_ports ETH_TXCLK]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_TXCLK]
set_property PACKAGE_PIN H14 [get_ports ETH_TXD[0]]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_TXD[0]]
set_property PACKAGE_PIN J14 [get_ports ETH_TXD[1]]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_TXD[1]]
set_property PACKAGE_PIN J13 [get_ports ETH_TXD[2]]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_TXD[2]]
set_property PACKAGE_PIN H17 [get_ports ETH_TXD[3]]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_TXD[3]]
set_property PACKAGE_PIN H15 [get_ports ETH_TXEN]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_TXEN]
set_property PACKAGE_PIN H5 [get_ports ETH_TXER]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_TXER]
create_clock -period 40.000 -name ETH_RXCLK -waveform {0.000 20.000} [get_ports ETH_RXCLK]
create_clock -period 40.000 -name ETH_TXCLK -waveform {0.000 20.000} [get_ports ETH_TXCLK]
set_clock_groups -asynchronous -group ETH_RXCLK -group ETH_TXCLK -group [get_clocks -include_generated_clocks sysclk]
