open_system('gm_multi_module_phase_shift_generator_built_in_pwm');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_built_in_pwm/pwm_generator/PWM', 'user2');
annotate_port('gm_multi_module_phase_shift_generator_built_in_pwm/pwm_generator/PWM', 0, 1, 'cp : 6.607 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_built_in_pwm/pwm_generator/PWM/ReplicaOfSource/ReplicaOfSource', 'user2');
annotate_port('gm_multi_module_phase_shift_generator_built_in_pwm/pwm_generator/PWM/ReplicaOfSource/ReplicaOfSource', 0, 1, 'cp : 4.228 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_built_in_pwm/pwm_generator/PWM/ReplicaOfSource_out1_wire', 'user2');
annotate_port('gm_multi_module_phase_shift_generator_built_in_pwm/pwm_generator/PWM/ReplicaOfSource_out1_wire', 0, 1, 'cp : 4.228 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_built_in_pwm/pwm_generator/PWM/DTC_output_1_getExpAndMant', 'user2');
annotate_port('gm_multi_module_phase_shift_generator_built_in_pwm/pwm_generator/PWM/DTC_output_1_getExpAndMant', 0, 1, 'cp : 4.228 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_multi_module_phase_shift_generator_built_in_pwm/pwm_generator/PWM/DTC_output_1', 'user1');
annotate_port('gm_multi_module_phase_shift_generator_built_in_pwm/pwm_generator/PWM/DTC_output_1', 0, 1, 'cp : 6.607 ns');
